import 'catalog.dart';

// App-authored experimental runtime UI only. Provider titles, package names,
// repository URLs, signer fingerprints, source IDs and API versions stay exact.
// Shared actions (Add repository, Cancel, Search, Browse, etc.) use the existing
// common/library catalogs instead of overriding their translations here.
final aniyomiTranslations = catalogFromRows(
  _aniyomiRows.trim().split('\n').map((row) => row.split('|')).toList(),
);

const _aniyomiRows = r'''
Reinstall extension|Reinstalar extensión|Reinstalar extensão|Réinstaller l’extension|एक्सटेंशन फिर से इंस्टॉल करें|Erweiterung neu installieren
Extension files missing • reinstall needed|Faltan archivos de la extensión • es necesario reinstalar|Arquivos da extensão ausentes • reinstalação necessária|Fichiers de l’extension manquants • réinstallation nécessaire|एक्सटेंशन की फ़ाइलें गायब हैं • फिर से इंस्टॉल करें|Erweiterungsdateien fehlen • Neuinstallation erforderlich
The extension files are no longer on this device. Reinstall to restore them; your existing approval will still be checked.|Los archivos de la extensión ya no están en este dispositivo. Reinstálala para restaurarlos; se seguirá verificando tu autorización existente.|Os arquivos da extensão não estão mais neste dispositivo. Reinstale para restaurá-los; sua aprovação existente ainda será verificada.|Les fichiers de l’extension ne sont plus sur cet appareil. Réinstallez-la pour les restaurer ; votre autorisation existante sera toujours vérifiée.|एक्सटेंशन की फ़ाइलें अब इस डिवाइस पर नहीं हैं। उन्हें बहाल करने के लिए फिर से इंस्टॉल करें; आपकी मौजूदा अनुमति की जाँच फिर भी होगी।|Die Erweiterungsdateien sind nicht mehr auf diesem Gerät. Installiere die Erweiterung neu; deine bestehende Genehmigung wird weiterhin geprüft.
This extension is no longer in your repositories. Add its repository again to reinstall it.|Esta extensión ya no está en tus repositorios. Añade su repositorio de nuevo para reinstalarla.|Esta extensão não está mais nos seus repositórios. Adicione o repositório novamente para reinstalá-la.|Cette extension n’est plus dans vos dépôts. Ajoutez à nouveau son dépôt pour la réinstaller.|यह एक्सटेंशन अब आपकी रिपॉज़िटरी में नहीं है। फिर से इंस्टॉल करने के लिए इसकी रिपॉज़िटरी दोबारा जोड़ें।|Diese Erweiterung ist nicht mehr in deinen Repositorys. Füge ihr Repository erneut hinzu, um sie neu zu installieren.
Filter extension language|Filtrar idioma de las extensiones|Filtrar idioma das extensões|Filtrer la langue des extensions|एक्सटेंशन की भाषा फ़िल्टर करें|Erweiterungssprache filtern
Multilingual|Multilingüe|Multilíngue|Multilingue|बहुभाषी|Mehrsprachig
Clear filters|Borrar filtros|Limpar filtros|Effacer les filtres|फ़िल्टर साफ़ करें|Filter zurücksetzen
Developer mode enabled. Release history and experimental Aniyomi extensions are now available.|Modo de desarrollador activado. Ya están disponibles el historial de versiones y las extensiones experimentales de Aniyomi.|Modo de desenvolvedor ativado. O histórico de versões e as extensões experimentais do Aniyomi estão disponíveis.|Mode développeur activé. L’historique des versions et les extensions Aniyomi expérimentales sont maintenant disponibles.|डेवलपर मोड चालू है। रिलीज़ इतिहास और प्रयोगात्मक Aniyomi एक्सटेंशन अब उपलब्ध हैं।|Entwicklermodus aktiviert. Versionsverlauf und experimentelle Aniyomi-Erweiterungen sind jetzt verfügbar.
Ready • 1 source|Lista • 1 fuente|Pronta • 1 fonte|Prête • 1 source|तैयार • 1 स्रोत|Bereit • 1 Quelle
Installed • sources not checked|Instalada • fuentes sin comprobar|Instalada • fontes não verificadas|Installée • sources non vérifiées|इंस्टॉल • स्रोतों की जाँच नहीं हुई|Installiert • Quellen nicht geprüft
Installed • checking sources…|Instalada • comprobando fuentes…|Instalada • verificando fontes…|Installée • vérification des sources…|इंस्टॉल • स्रोतों की जाँच जारी…|Installiert • Quellen werden geprüft…
Ready • {count} sources|Lista • {count} fuentes|Pronta • {count} fontes|Prête • {count} sources|तैयार • {count} स्रोत|Bereit • {count} Quellen
Installed • source discovery failed|Instalada • no se pudieron cargar las fuentes|Instalada • falha ao carregar fontes|Installée • échec du chargement des sources|इंस्टॉल • स्रोत लोड नहीं हो सके|Installiert • Quellen konnten nicht geladen werden
Stage: {stage} • Reason: {reason}|Etapa: {stage} • Motivo: {reason}|Etapa: {stage} • Motivo: {reason}|Étape : {stage} • Motif : {reason}|चरण: {stage} • कारण: {reason}|Schritt: {stage} • Grund: {reason}
Retry source discovery|Reintentar cargar fuentes|Tentar carregar fontes novamente|Réessayer de charger les sources|स्रोत फिर से लोड करें|Quellen erneut laden
Extension installed, but source discovery failed. Retry from Installed extensions.|Extensión instalada, pero no se pudieron cargar las fuentes. Reintenta desde Extensiones instaladas.|Extensão instalada, mas as fontes não foram carregadas. Tente novamente em Extensões instaladas.|Extension installée, mais les sources n'ont pas pu être chargées. Réessayez depuis Extensions installées.|एक्सटेंशन इंस्टॉल हुआ, लेकिन स्रोत लोड नहीं हो सके। इंस्टॉल किए गए एक्सटेंशन से फिर कोशिश करें।|Erweiterung installiert, aber die Quellen konnten nicht geladen werden. Versuche es unter Installierte Erweiterungen erneut.
Some repositories or extensions could not load. Refresh repositories or retry the failed extension. Unsupported extensions stay unavailable.|No se pudieron cargar algunos repositorios o extensiones. Actualiza los repositorios o reintenta la extensión que falló. Las extensiones no compatibles siguen sin estar disponibles.|Alguns repositórios ou extensões não foram carregados. Atualize os repositórios ou tente novamente a extensão que falhou. Extensões não compatíveis continuam indisponíveis.|Certains dépôts ou extensions n'ont pas pu être chargés. Actualisez les dépôts ou réessayez l'extension en échec. Les extensions non prises en charge restent indisponibles.|कुछ रिपॉज़िटरी या एक्सटेंशन लोड नहीं हो सके। रिपॉज़िटरी रीफ़्रेश करें या असफल एक्सटेंशन फिर से चलाएँ। असमर्थित एक्सटेंशन उपलब्ध नहीं होंगे।|Einige Repositorys oder Erweiterungen konnten nicht geladen werden. Aktualisiere die Repositorys oder versuche die betroffene Erweiterung erneut. Nicht unterstützte Erweiterungen bleiben nicht verfügbar.
Ready anime sources join the normal show source search. Ready manga sources open the existing reader below.|Las fuentes de anime listas se añaden a la búsqueda habitual de series. Las fuentes de manga listas abren el lector existente desde abajo.|As fontes de anime prontas aparecem na busca normal de séries. As fontes de mangá prontas abaixo abrem o leitor existente.|Les sources d'animes prêtes rejoignent la recherche habituelle de séries. Les sources de mangas prêtes ci-dessous ouvrent le lecteur existant.|तैयार एनीमे स्रोत सामान्य शो खोज में शामिल होते हैं। नीचे दिए गए तैयार मंगा स्रोत मौजूदा रीडर खोलते हैं।|Bereite Anime-Quellen erscheinen in der normalen Serienquellensuche. Die bereiten Manga-Quellen unten öffnen den vorhandenen Reader.
Aniyomi experiments require Developer Mode.|Las funciones experimentales de Aniyomi requieren el modo de desarrollador.|Os recursos experimentais do Aniyomi exigem o modo de desenvolvedor.|Les fonctions expérimentales d'Aniyomi nécessitent le mode développeur.|Aniyomi की प्रयोगात्मक सुविधाओं के लिए डेवलपर मोड ज़रूरी है।|Die experimentellen Aniyomi-Funktionen erfordern den Entwicklermodus.
This extension could not complete the request. It may require an unsupported API, network feature, or repository format.|Esta extensión no pudo completar la solicitud. Puede que necesite una API, una función de red o un formato de repositorio no compatible.|Esta extensão não conseguiu concluir a solicitação. Ela pode exigir uma API, um recurso de rede ou um formato de repositório não compatível.|Cette extension n'a pas pu terminer la requête. Elle peut nécessiter une API, une fonction réseau ou un format de dépôt non pris en charge.|यह एक्सटेंशन अनुरोध पूरा नहीं कर सका। इसे ऐसी API, नेटवर्क सुविधा या रिपॉज़िटरी फ़ॉर्मैट की ज़रूरत हो सकती है जिसका समर्थन नहीं है।|Diese Erweiterung konnte die Anfrage nicht abschließen. Möglicherweise benötigt sie eine nicht unterstützte API, Netzwerkfunktion oder ein nicht unterstütztes Repository-Format.
Trust this experimental extension?|¿Confiar en esta extensión experimental?|Confiar nesta extensão experimental?|Faire confiance à cette extension expérimentale ?|इस प्रयोगात्मक एक्सटेंशन पर भरोसा करें?|Dieser experimentellen Erweiterung vertrauen?
Extensions are third-party executable code. Install only ones you trust. Signature verification checks identity, not safety.|Las extensiones son código ejecutable de terceros. Instala solo aquellas en las que confíes. La verificación de la firma comprueba la identidad, no la seguridad.|Extensões são código executável de terceiros. Instale apenas aquelas em que você confia. A verificação da assinatura confirma a identidade, não a segurança.|Les extensions sont du code exécutable tiers. N'installez que celles auxquelles vous faites confiance. La vérification de la signature contrôle l'identité, pas la sécurité.|एक्सटेंशन तीसरे पक्ष का निष्पादन योग्य कोड हैं। केवल भरोसेमंद एक्सटेंशन इंस्टॉल करें। हस्ताक्षर की जाँच पहचान की पुष्टि करती है, सुरक्षा की नहीं।|Erweiterungen enthalten ausführbaren Code von Drittanbietern. Installiere nur vertrauenswürdige Erweiterungen. Die Signaturprüfung bestätigt die Identität, nicht die Sicherheit.
Verified signer (SHA-256)|Firmante verificado (SHA-256)|Signatário verificado (SHA-256)|Signataire vérifié (SHA-256)|सत्यापित हस्ताक्षरकर्ता (SHA-256)|Verifizierter Unterzeichner (SHA-256)
Changing or disabling Developer Mode revokes execution approval. Seanime is unaffected.|Cambiar o desactivar el modo de desarrollador revoca la autorización de ejecución. Seanime no se ve afectado.|Alterar ou desativar o modo de desenvolvedor revoga a autorização de execução. O Seanime não é afetado.|Modifier ou désactiver le mode développeur révoque l'autorisation d'exécution. Seanime n'est pas affecté.|डेवलपर मोड बदलने या बंद करने से चलाने की अनुमति रद्द हो जाती है। Seanime पर कोई असर नहीं पड़ता।|Eine Änderung oder Deaktivierung des Entwicklermodus widerruft die Ausführungserlaubnis. Seanime bleibt unberührt.
Trust and install|Confiar e instalar|Confiar e instalar|Faire confiance et installer|भरोसा करके इंस्टॉल करें|Vertrauen und installieren
Aniyomi • Experimental|Aniyomi • Experimental|Aniyomi • Experimental|Aniyomi • Expérimental|Aniyomi • प्रयोगात्मक|Aniyomi • Experimentell
Android 8 or newer. Anime APIs 14 and 16 and manga APIs 1.4–1.5 are supported. WebView, custom transports and native-player commands are not supported. No repositories are bundled.|Android 8 o posterior. Se admiten las API 14 y 16 de anime y las API 1.4–1.5 de manga. No se admiten WebView, transportes personalizados ni comandos del reproductor nativo. No se incluyen repositorios.|Android 8 ou mais recente. As APIs 14 e 16 de anime e as APIs 1.4–1.5 de mangá são compatíveis. WebView, transportes personalizados e comandos do reprodutor nativo não são compatíveis. Nenhum repositório vem incluído.|Android 8 ou version ultérieure. Les API 14 et 16 pour les animes et les API 1.4–1.5 pour les mangas sont prises en charge. WebView, les transports personnalisés et les commandes du lecteur natif ne sont pas pris en charge. Aucun dépôt n'est fourni.|Android 8 या नया संस्करण। Anime API 14 और 16 तथा manga API 1.4–1.5 समर्थित हैं। WebView, कस्टम ट्रांसपोर्ट और नेटिव प्लेयर कमांड का समर्थन नहीं है। कोई रिपॉज़िटरी शामिल नहीं है।|Android 8 oder neuer. Anime-APIs 14 und 16 sowie Manga-APIs 1.4–1.5 werden unterstützt. WebView, benutzerdefinierte Transportwege und native Player-Befehle werden nicht unterstützt. Es sind keine Repositorys enthalten.
Waiting for a supported Android runtime.|Esperando un entorno de ejecución Android compatible.|Aguardando um ambiente de execução Android compatível.|En attente d'un environnement d'exécution Android compatible.|समर्थित Android रनटाइम की प्रतीक्षा है।|Warten auf eine unterstützte Android-Laufzeitumgebung.
Add anime repository|Añadir repositorio de anime|Adicionar repositório de anime|Ajouter un dépôt d'animes|एनीमे रिपॉज़िटरी जोड़ें|Anime-Repository hinzufügen
Add manga repository|Añadir repositorio de manga|Adicionar repositório de mangá|Ajouter un dépôt de mangas|मंगा रिपॉज़िटरी जोड़ें|Manga-Repository hinzufügen
Installed extensions|Extensiones instaladas|Extensões instaladas|Extensions installées|इंस्टॉल किए गए एक्सटेंशन|Installierte Erweiterungen
Revoke approval|Revocar autorización|Revogar autorização|Révoquer l'autorisation|अनुमति रद्द करें|Genehmigung widerrufen
Some repositories or extensions could not load. Refresh to try again. Unsupported extensions stay unavailable.|No se pudieron cargar algunos repositorios o extensiones. Actualiza para volver a intentarlo. Las extensiones no compatibles seguirán sin estar disponibles.|Não foi possível carregar alguns repositórios ou extensões. Atualize para tentar novamente. Extensões não compatíveis continuam indisponíveis.|Certains dépôts ou extensions n'ont pas pu être chargés. Actualisez pour réessayer. Les extensions non prises en charge restent indisponibles.|कुछ रिपॉज़िटरी या एक्सटेंशन लोड नहीं हो सके। फिर कोशिश करने के लिए रीफ़्रेश करें। असमर्थित एक्सटेंशन उपलब्ध नहीं होंगे।|Einige Repositorys oder Erweiterungen konnten nicht geladen werden. Aktualisiere, um es erneut zu versuchen. Nicht unterstützte Erweiterungen bleiben nicht verfügbar.
Approved anime sources join the normal show source search. Manga sources open the existing reader below.|Las fuentes de anime autorizadas se añaden a la búsqueda habitual de fuentes de series. Las fuentes de manga abren el lector existente desde abajo.|As fontes de anime autorizadas aparecem na busca normal de fontes de séries. As fontes de mangá abaixo abrem o leitor existente.|Les sources d'animes autorisées rejoignent la recherche habituelle de sources de séries. Les sources de mangas ci-dessous ouvrent le lecteur existant.|अनुमोदित एनीमे स्रोत सामान्य शो स्रोत खोज में जुड़ जाते हैं। नीचे दिए गए मंगा स्रोत मौजूदा रीडर खोलते हैं।|Genehmigte Anime-Quellen werden in die normale Serienquellensuche aufgenommen. Die Manga-Quellen unten öffnen den vorhandenen Reader.
Available extensions|Extensiones disponibles|Extensões disponíveis|Extensions disponibles|उपलब्ध एक्सटेंशन|Verfügbare Erweiterungen
Search extensions|Buscar extensiones|Buscar extensões|Rechercher des extensions|एक्सटेंशन खोजें|Erweiterungen suchen
''';
