import 'catalog.dart';

final commonTranslations = catalogFromRows(const [
  [
    'Retry available in {time}',
    'Puedes reintentar en {time}',
    'Tente novamente em {time}',
    'Nouvel essai possible dans {time}',
    '{time} में फिर कोशिश कर सकते हैं',
    'Erneut versuchen in {time}',
  ],
  [
    'The secure phone-setup service is not available yet.',
    'El servicio de configuración segura con el teléfono aún no está disponible.',
    'O serviço de configuração segura pelo celular ainda não está disponível.',
    "Le service de configuration sécurisée par téléphone n'est pas encore disponible.",
    'सुरक्षित फ़ोन सेटअप सेवा अभी उपलब्ध नहीं है।',
    'Die sichere Einrichtung per Smartphone ist noch nicht verfügbar.',
  ],
  [
    'This phone setup was already completed or changed.',
    'Esta configuración con el teléfono ya se completó o cambió.',
    'Esta configuração pelo celular já foi concluída ou alterada.',
    'Cette configuration par téléphone a déjà été terminée ou modifiée.',
    'यह फ़ोन सेटअप पहले ही पूरा हो चुका है या बदल गया है।',
    'Diese Smartphone-Einrichtung wurde bereits abgeschlossen oder geändert.',
  ],
  [
    'Phone setup is temporarily rate-limited. Wait before trying again.',
    'Se alcanzó el límite temporal de solicitudes de configuración. Espera antes de volver a intentarlo.',
    'O limite temporário de solicitações de configuração foi atingido. Aguarde antes de tentar novamente.',
    'La limite temporaire de demandes de configuration est atteinte. Patientez avant de réessayer.',
    'फ़ोन सेटअप अनुरोधों की अस्थायी सीमा पूरी हो गई है। फिर कोशिश करने से पहले थोड़ा रुकें।',
    'Die Einrichtung ist wegen zu vieler Anfragen vorübergehend begrenzt. Warte, bevor du es erneut versuchst.',
  ],
  [
    'The secure phone-setup service is temporarily busy.',
    'El servicio de configuración segura con el teléfono está ocupado temporalmente.',
    'O serviço de configuração segura pelo celular está temporariamente ocupado.',
    'Le service de configuration sécurisée par téléphone est temporairement occupé.',
    'सुरक्षित फ़ोन सेटअप सेवा अभी व्यस्त है।',
    'Der Dienst für die sichere Smartphone-Einrichtung ist vorübergehend ausgelastet.',
  ],
  [
    'The secure TetoTV phone-setup service could not be reached.',
    'No se pudo conectar con el servicio de configuración segura de TetoTV.',
    'Não foi possível acessar o serviço de configuração segura do TetoTV.',
    'Impossible de joindre le service de configuration sécurisée de TetoTV.',
    'TetoTV की सुरक्षित फ़ोन सेटअप सेवा से संपर्क नहीं हो सका।',
    'Der Dienst für die sichere TetoTV-Einrichtung war nicht erreichbar.',
  ],
  [
    'Update details are available on GitHub.',
    'Los detalles de la actualización están disponibles en GitHub.',
    'Os detalhes da atualização estão disponíveis no GitHub.',
    'Les détails de la mise à jour sont disponibles sur GitHub.',
    'अपडेट की जानकारी GitHub पर उपलब्ध है।',
    'Details zum Update findest du auf GitHub.',
  ],
  ['Back', 'Atrás', 'Voltar', 'Retour', 'वापस', 'Zurück'],
  ['Cancel', 'Cancelar', 'Cancelar', 'Annuler', 'रद्द करें', 'Abbrechen'],
  ['Close', 'Cerrar', 'Fechar', 'Fermer', 'बंद करें', 'Schließen'],
  ['Done', 'Listo', 'Concluído', 'Terminé', 'हो गया', 'Fertig'],
  ['Save', 'Guardar', 'Salvar', 'Enregistrer', 'सहेजें', 'Speichern'],
  ['Apply', 'Aplicar', 'Aplicar', 'Appliquer', 'लागू करें', 'Anwenden'],
  ['Continue', 'Continuar', 'Continuar', 'Continuer', 'जारी रखें', 'Weiter'],
  ['Next', 'Siguiente', 'Próximo', 'Suivant', 'अगला', 'Weiter'],
  ['Previous', 'Anterior', 'Anterior', 'Précédent', 'पिछला', 'Zurück'],
  [
    'Retry',
    'Reintentar',
    'Tentar novamente',
    'Réessayer',
    'फिर कोशिश करें',
    'Erneut versuchen',
  ],
  [
    'Try again',
    'Intentar de nuevo',
    'Tentar novamente',
    'Réessayer',
    'फिर कोशिश करें',
    'Erneut versuchen',
  ],
  [
    'Refresh',
    'Actualizar',
    'Atualizar',
    'Actualiser',
    'रीफ़्रेश करें',
    'Aktualisieren',
  ],
  [
    'Loading',
    'Cargando',
    'Carregando',
    'Chargement',
    'लोड हो रहा है',
    'Wird geladen',
  ],
  [
    'Loading…',
    'Cargando…',
    'Carregando…',
    'Chargement…',
    'लोड हो रहा है…',
    'Wird geladen…',
  ],
  [
    'Loading...',
    'Cargando...',
    'Carregando...',
    'Chargement...',
    'लोड हो रहा है...',
    'Wird geladen...',
  ],
  ['Search', 'Buscar', 'Buscar', 'Rechercher', 'खोजें', 'Suchen'],
  ['Home', 'Inicio', 'Início', 'Accueil', 'होम', 'Start'],
  [
    'My List',
    'Mi lista',
    'Minha lista',
    'Ma liste',
    'मेरी सूची',
    'Meine Liste',
  ],
  ['Discover', 'Descubrir', 'Descobrir', 'Découvrir', 'खोजबीन', 'Entdecken'],
  ['Calendar', 'Calendario', 'Calendário', 'Calendrier', 'कैलेंडर', 'Kalender'],
  [
    'Watch Party',
    'Sala compartida',
    'Sala de exibição',
    'Visionnage partagé',
    'वॉच पार्टी',
    'Watchparty',
  ],
  [
    'Downloads',
    'Descargas',
    'Downloads',
    'Téléchargements',
    'डाउनलोड',
    'Downloads',
  ],
  ['Manga', 'Manga', 'Mangá', 'Manga', 'मंगा', 'Manga'],
  [
    'Settings',
    'Ajustes',
    'Configurações',
    'Paramètres',
    'सेटिंग्स',
    'Einstellungen',
  ],
  ['Accounts', 'Cuentas', 'Contas', 'Comptes', 'खाते', 'Konten'],
  [
    'Notifications',
    'Notificaciones',
    'Notificações',
    'Notifications',
    'सूचनाएँ',
    'Benachrichtigungen',
  ],
  [
    'Appearance',
    'Apariencia',
    'Aparência',
    'Apparence',
    'दिखावट',
    'Darstellung',
  ],
  [
    'Playback',
    'Reproducción',
    'Reprodução',
    'Lecture',
    'प्लेबैक',
    'Wiedergabe',
  ],
  ['Services', 'Servicios', 'Serviços', 'Services', 'सेवाएँ', 'Dienste'],
  ['System', 'Sistema', 'Sistema', 'Système', 'सिस्टम', 'System'],
  ['Language', 'Idioma', 'Idioma', 'Langue', 'भाषा', 'Sprache'],
  ['English', 'Inglés', 'Inglês', 'Anglais', 'अंग्रेज़ी', 'Englisch'],
  ['Spanish', 'Español', 'Espanhol', 'Espagnol', 'स्पेनिश', 'Spanisch'],
  [
    'Portuguese',
    'Portugués',
    'Português',
    'Portugais',
    'पुर्तगाली',
    'Portugiesisch',
  ],
  ['French', 'Francés', 'Francês', 'Français', 'फ़्रेंच', 'Französisch'],
  ['Hindi', 'Hindi', 'Hindi', 'Hindi', 'हिन्दी', 'Hindi'],
  ['German', 'Alemán', 'Alemão', 'Allemand', 'जर्मन', 'Deutsch'],
  ['Japanese', 'Japonés', 'Japonês', 'Japonais', 'जापानी', 'Japanisch'],
  ['Italian', 'Italiano', 'Italiano', 'Italien', 'इतालवी', 'Italienisch'],
  [
    'Automatic',
    'Automático',
    'Automático',
    'Automatique',
    'अपने आप',
    'Automatisch',
  ],
  ['Default', 'Predeterminado', 'Padrão', 'Par défaut', 'डिफ़ॉल्ट', 'Standard'],
  ['None', 'Ninguno', 'Nenhum', 'Aucun', 'कोई नहीं', 'Keine'],
  ['All', 'Todos', 'Todos', 'Tous', 'सभी', 'Alle'],
  ['Any', 'Cualquiera', 'Qualquer', 'Tous', 'कोई भी', 'Beliebig'],
  ['On', 'Activado', 'Ativado', 'Activé', 'चालू', 'Ein'],
  ['Off', 'Desactivado', 'Desativado', 'Désactivé', 'बंद', 'Aus'],
  ['Enabled', 'Activado', 'Ativado', 'Activé', 'सक्रिय', 'Aktiviert'],
  [
    'Disabled',
    'Desactivado',
    'Desativado',
    'Désactivé',
    'निष्क्रिय',
    'Deaktiviert',
  ],
  ['Yes', 'Sí', 'Sim', 'Oui', 'हाँ', 'Ja'],
  ['No', 'No', 'Não', 'Non', 'नहीं', 'Nein'],
  ['OK', 'Aceptar', 'OK', 'OK', 'ठीक है', 'OK'],
  ['Add', 'Añadir', 'Adicionar', 'Ajouter', 'जोड़ें', 'Hinzufügen'],
  ['Remove', 'Quitar', 'Remover', 'Retirer', 'हटाएँ', 'Entfernen'],
  ['Delete', 'Eliminar', 'Excluir', 'Supprimer', 'मिटाएँ', 'Löschen'],
  ['Edit', 'Editar', 'Editar', 'Modifier', 'बदलें', 'Bearbeiten'],
  [
    'Reset',
    'Restablecer',
    'Redefinir',
    'Réinitialiser',
    'रीसेट करें',
    'Zurücksetzen',
  ],
  ['Clear', 'Borrar', 'Limpar', 'Effacer', 'साफ़ करें', 'Leeren'],
  ['Copy', 'Copiar', 'Copiar', 'Copier', 'कॉपी करें', 'Kopieren'],
  ['Copied', 'Copiado', 'Copiado', 'Copié', 'कॉपी हो गया', 'Kopiert'],
  ['Paste', 'Pegar', 'Colar', 'Coller', 'पेस्ट करें', 'Einfügen'],
  ['Open', 'Abrir', 'Abrir', 'Ouvrir', 'खोलें', 'Öffnen'],
  ['Connect', 'Conectar', 'Conectar', 'Connecter', 'जोड़ें', 'Verbinden'],
  [
    'Disconnect',
    'Desconectar',
    'Desconectar',
    'Déconnecter',
    'डिस्कनेक्ट करें',
    'Trennen',
  ],
  ['Connected', 'Conectado', 'Conectado', 'Connecté', 'कनेक्ट है', 'Verbunden'],
  [
    'Not connected',
    'Sin conexión',
    'Não conectado',
    'Non connecté',
    'कनेक्ट नहीं है',
    'Nicht verbunden',
  ],
  ['Linked', 'Vinculado', 'Vinculado', 'Associé', 'लिंक है', 'Verknüpft'],
  [
    'Not linked',
    'Sin vincular',
    'Não vinculado',
    'Non associé',
    'लिंक नहीं है',
    'Nicht verknüpft',
  ],
  ['Optional', 'Opcional', 'Opcional', 'Facultatif', 'वैकल्पिक', 'Optional'],
  [
    'Required',
    'Obligatorio',
    'Obrigatório',
    'Obligatoire',
    'ज़रूरी',
    'Erforderlich',
  ],
  ['Name', 'Nombre', 'Nome', 'Nom', 'नाम', 'Name'],
  [
    'Username',
    'Nombre de usuario',
    'Nome de usuário',
    'Nom d’utilisateur',
    'उपयोगकर्ता नाम',
    'Benutzername',
  ],
  ['Password', 'Contraseña', 'Senha', 'Mot de passe', 'पासवर्ड', 'Passwort'],
  [
    'API key',
    'Clave API',
    'Chave de API',
    'Clé API',
    'API कुंजी',
    'API-Schlüssel',
  ],
  ['Profile', 'Perfil', 'Perfil', 'Profil', 'प्रोफ़ाइल', 'Profil'],
  ['Profiles', 'Perfiles', 'Perfis', 'Profils', 'प्रोफ़ाइल', 'Profile'],
  ['Account', 'Cuenta', 'Conta', 'Compte', 'खाता', 'Konto'],
  [
    'Local profile',
    'Perfil local',
    'Perfil local',
    'Profil local',
    'स्थानीय प्रोफ़ाइल',
    'Lokales Profil',
  ],
  ['Guest', 'Invitado', 'Convidado', 'Invité', 'अतिथि', 'Gast'],
  [
    'Sign in',
    'Iniciar sesión',
    'Entrar',
    'Se connecter',
    'साइन इन करें',
    'Anmelden',
  ],
  [
    'Sign out',
    'Cerrar sesión',
    'Sair',
    'Se déconnecter',
    'साइन आउट करें',
    'Abmelden',
  ],
  [
    'Continue as guest',
    'Continuar como invitado',
    'Continuar como convidado',
    'Continuer en invité',
    'अतिथि के रूप में जारी रखें',
    'Als Gast fortfahren',
  ],
  ['Play', 'Reproducir', 'Reproduzir', 'Lire', 'चलाएँ', 'Abspielen'],
  ['Pause', 'Pausar', 'Pausar', 'Pause', 'रोकें', 'Pause'],
  ['Resume', 'Continuar', 'Continuar', 'Reprendre', 'जारी रखें', 'Fortsetzen'],
  ['Stop', 'Detener', 'Parar', 'Arrêter', 'बंद करें', 'Stoppen'],
  [
    'Retry failed providers',
    'Reintentar proveedores fallidos',
    'Tentar provedores com falha',
    'Réessayer les fournisseurs en échec',
    'विफल प्रदाताओं को फिर आज़माएँ',
    'Fehlgeschlagene Anbieter erneut versuchen',
  ],
  [
    'Watch now',
    'Ver ahora',
    'Assistir agora',
    'Regarder',
    'अभी देखें',
    'Jetzt ansehen',
  ],
  [
    'Watch trailer',
    'Ver tráiler',
    'Ver trailer',
    'Bande-annonce',
    'ट्रेलर देखें',
    'Trailer ansehen',
  ],
  [
    'Cast & crew',
    'Reparto y equipo',
    'Elenco e equipe',
    'Distribution et équipe',
    'कलाकार और टीम',
    'Besetzung und Team',
  ],
  [
    'Related series',
    'Series relacionadas',
    'Séries relacionadas',
    'Séries liées',
    'संबंधित सीरीज़',
    'Verwandte Serien',
  ],
  [
    'Download season',
    'Descargar temporada',
    'Baixar temporada',
    'Télécharger la saison',
    'सीज़न डाउनलोड करें',
    'Staffel herunterladen',
  ],
  ['Episodes', 'Episodios', 'Episódios', 'Épisodes', 'एपिसोड', 'Folgen'],
  ['Episode', 'Episodio', 'Episódio', 'Épisode', 'एपिसोड', 'Folge'],
  ['Season', 'Temporada', 'Temporada', 'Saison', 'सीज़न', 'Staffel'],
  ['Details', 'Detalles', 'Detalhes', 'Détails', 'विवरण', 'Details'],
  [
    'Description',
    'Descripción',
    'Descrição',
    'Description',
    'विवरण',
    'Beschreibung',
  ],
  ['Status', 'Estado', 'Status', 'Statut', 'स्थिति', 'Status'],
  ['Finished', 'Finalizado', 'Finalizado', 'Terminé', 'पूर्ण', 'Abgeschlossen'],
  [
    'Releasing',
    'En emisión',
    'Em lançamento',
    'En cours',
    'प्रसारण जारी',
    'Wird ausgestrahlt',
  ],
  [
    'Not yet released',
    'Aún no estrenado',
    'Ainda não lançado',
    'Pas encore sorti',
    'अभी रिलीज़ नहीं हुआ',
    'Noch nicht erschienen',
  ],
  ['Unknown', 'Desconocido', 'Desconhecido', 'Inconnu', 'अज्ञात', 'Unbekannt'],
  [
    'Unavailable',
    'No disponible',
    'Indisponível',
    'Indisponible',
    'उपलब्ध नहीं',
    'Nicht verfügbar',
  ],
  ['Error', 'Error', 'Erro', 'Erreur', 'त्रुटि', 'Fehler'],
  ['Warning', 'Advertencia', 'Aviso', 'Avertissement', 'चेतावनी', 'Warnung'],
  ['Ready', 'Listo', 'Pronto', 'Prêt', 'तैयार', 'Bereit'],
  ['Pending', 'Pendiente', 'Pendente', 'En attente', 'लंबित', 'Ausstehend'],
  ['Paused', 'Pausado', 'Pausado', 'En pause', 'रुका हुआ', 'Pausiert'],
  [
    'Completed',
    'Completado',
    'Concluído',
    'Terminé',
    'पूरा हुआ',
    'Abgeschlossen',
  ],
  ['Failed', 'Fallido', 'Falhou', 'Échec', 'विफल', 'Fehlgeschlagen'],
  ['Sources', 'Fuentes', 'Fontes', 'Sources', 'स्रोत', 'Quellen'],
  [
    'Providers',
    'Proveedores',
    'Provedores',
    'Fournisseurs',
    'प्रदाता',
    'Anbieter',
  ],
  [
    'Extensions',
    'Extensiones',
    'Extensões',
    'Extensions',
    'एक्सटेंशन',
    'Erweiterungen',
  ],
  [
    'Repositories',
    'Repositorios',
    'Repositórios',
    'Dépôts',
    'रिपॉज़िटरी',
    'Repositorys',
  ],
  [
    'Marketplace',
    'Catálogo de extensiones',
    'Catálogo de extensões',
    'Catalogue d’extensions',
    'एक्सटेंशन बाज़ार',
    'Erweiterungskatalog',
  ],
  [
    'Install',
    'Instalar',
    'Instalar',
    'Installer',
    'इंस्टॉल करें',
    'Installieren',
  ],
  [
    'Installed',
    'Instalado',
    'Instalado',
    'Installé',
    'इंस्टॉल है',
    'Installiert',
  ],
  [
    'Update',
    'Actualizar',
    'Atualizar',
    'Mettre à jour',
    'अपडेट करें',
    'Aktualisieren',
  ],
  [
    'Updates',
    'Actualizaciones',
    'Atualizações',
    'Mises à jour',
    'अपडेट',
    'Updates',
  ],
  [
    'Check for updates',
    'Buscar actualizaciones',
    'Verificar atualizações',
    'Rechercher des mises à jour',
    'अपडेट जाँचें',
    'Nach Updates suchen',
  ],
  ['Dismiss', 'Descartar', 'Dispensar', 'Ignorer', 'हटाएँ', 'Verwerfen'],
  ['NOTICE', 'AVISO', 'AVISO', 'INFORMATION', 'सूचना', 'HINWEIS'],
  ['UPDATE', 'ACTUALIZACIÓN', 'ATUALIZAÇÃO', 'MISE À JOUR', 'अपडेट', 'UPDATE'],
  ['CANCEL', 'CANCELAR', 'CANCELAR', 'ANNULER', 'रद्द करें', 'ABBRECHEN'],
  ['DONE', 'LISTO', 'CONCLUÍDO', 'TERMINÉ', 'हो गया', 'FERTIG'],
  ['CLEAR', 'BORRAR', 'LIMPAR', 'EFFACER', 'साफ़ करें', 'LEEREN'],
  [
    'Start typing...',
    'Empieza a escribir...',
    'Comece a digitar...',
    'Commencez à saisir...',
    'टाइप करना शुरू करें...',
    'Eingabe beginnen...',
  ],
  [
    'Start typing…',
    'Empieza a escribir…',
    'Comece a digitar…',
    'Commencez à saisir…',
    'टाइप करना शुरू करें…',
    'Eingabe beginnen…',
  ],
  [
    'Search anime',
    'Buscar anime',
    'Buscar anime',
    'Rechercher un anime',
    'एनीमे खोजें',
    'Anime suchen',
  ],
  [
    'REMOTE / CONTROLLER / KEYBOARD',
    'MANDO / CONTROL / TECLADO',
    'CONTROLE / GAMEPAD / TECLADO',
    'TÉLÉCOMMANDE / MANETTE / CLAVIER',
    'रिमोट / कंट्रोलर / कीबोर्ड',
    'FERNBEDIENUNG / CONTROLLER / TASTATUR',
  ],
  ['Filters', 'Filtros', 'Filtros', 'Filtres', 'फ़िल्टर', 'Filter'],
  ['Sort', 'Ordenar', 'Ordenar', 'Trier', 'क्रमबद्ध करें', 'Sortieren'],
  [
    'Sort by',
    'Ordenar por',
    'Ordenar por',
    'Trier par',
    'क्रम',
    'Sortieren nach',
  ],
  [
    'Reset filters',
    'Restablecer filtros',
    'Redefinir filtros',
    'Réinitialiser les filtres',
    'फ़िल्टर रीसेट करें',
    'Filter zurücksetzen',
  ],
  [
    'No results',
    'Sin resultados',
    'Sem resultados',
    'Aucun résultat',
    'कोई परिणाम नहीं',
    'Keine Ergebnisse',
  ],
  [
    'No results found',
    'No se encontraron resultados',
    'Nenhum resultado encontrado',
    'Aucun résultat trouvé',
    'कोई परिणाम नहीं मिला',
    'Keine Ergebnisse gefunden',
  ],
  [
    'Try another search',
    'Prueba otra búsqueda',
    'Tente outra busca',
    'Essayez une autre recherche',
    'दूसरी खोज आज़माएँ',
    'Andere Suche versuchen',
  ],
  ['More', 'Más', 'Mais', 'Plus', 'और', 'Mehr'],
  [
    'Show more',
    'Ver más',
    'Mostrar mais',
    'Afficher plus',
    'और दिखाएँ',
    'Mehr anzeigen',
  ],
  [
    'Show less',
    'Ver menos',
    'Mostrar menos',
    'Afficher moins',
    'कम दिखाएँ',
    'Weniger anzeigen',
  ],
  [
    'Expand all',
    'Expandir todo',
    'Expandir tudo',
    'Tout développer',
    'सभी खोलें',
    'Alle aufklappen',
  ],
  [
    'Collapse all',
    'Contraer todo',
    'Recolher tudo',
    'Tout réduire',
    'सभी समेटें',
    'Alle zuklappen',
  ],
  ['Audio', 'Audio', 'Áudio', 'Audio', 'ऑडियो', 'Audio'],
  [
    'Captions',
    'Subtítulos',
    'Legendas',
    'Sous-titres',
    'उपशीर्षक',
    'Untertitel',
  ],
  [
    'Subtitles',
    'Subtítulos',
    'Legendas',
    'Sous-titres',
    'उपशीर्षक',
    'Untertitel',
  ],
  ['Dubbed', 'Doblado', 'Dublado', 'Doublé', 'डब किया गया', 'Synchronisiert'],
  [
    'Subtitled',
    'Subtitulado',
    'Legendado',
    'Sous-titré',
    'उपशीर्षक सहित',
    'Untertitelt',
  ],
  ['Quality', 'Calidad', 'Qualidade', 'Qualité', 'गुणवत्ता', 'Qualität'],
  ['Speed', 'Velocidad', 'Velocidade', 'Vitesse', 'गति', 'Geschwindigkeit'],
  ['Original', 'Original', 'Original', 'Original', 'मूल', 'Original'],
  [
    'Download',
    'Descargar',
    'Baixar',
    'Télécharger',
    'डाउनलोड करें',
    'Herunterladen',
  ],
  [
    'View all',
    'Ver todo',
    'Ver tudo',
    'Tout voir',
    'सभी देखें',
    'Alle anzeigen',
  ],
  ['Today', 'Hoy', 'Hoje', 'Aujourd’hui', 'आज', 'Heute'],
  ['Tomorrow', 'Mañana', 'Amanhã', 'Demain', 'कल', 'Morgen'],
  ['Yesterday', 'Ayer', 'Ontem', 'Hier', 'कल', 'Gestern'],
  ['Date', 'Fecha', 'Data', 'Date', 'तारीख', 'Datum'],
  ['Time', 'Hora', 'Hora', 'Heure', 'समय', 'Zeit'],
  ['Help', 'Ayuda', 'Ajuda', 'Aide', 'मदद', 'Hilfe'],
  [
    'Privacy',
    'Privacidad',
    'Privacidade',
    'Confidentialité',
    'गोपनीयता',
    'Datenschutz',
  ],
  ['About', 'Acerca de', 'Sobre', 'À propos', 'परिचय', 'Über'],
]);
