import 'catalog.dart';

/// User-facing names and disclosures for the optional experimental feature
/// switch. The persisted storage key intentionally stays unchanged so existing
/// installs keep their choice across this terminology change.
final experimentalFeaturesTranslations = catalogFromRows(
  _experimentalFeaturesRows
      .trim()
      .split('\n')
      .map((row) => row.split('|'))
      .toList(),
);

const _experimentalFeaturesRows = r'''
Experimental options|Opciones experimentales|Opções experimentais|Options expérimentales|प्रयोगात्मक विकल्प|Experimentelle Optionen
Turn on to access the manga reader, Aniyomi extensions, and build-switching tools. These options may be unstable.|Actívalas para acceder al lector de manga, las extensiones de Aniyomi y las herramientas para cambiar de versión. Estas opciones pueden ser inestables.|Ative para acessar o leitor de mangá, as extensões do Aniyomi e as ferramentas para trocar de versão. Essas opções podem ser instáveis.|Activez-les pour accéder au lecteur de manga, aux extensions Aniyomi et aux outils de changement de version. Ces options peuvent être instables.|मंगा रीडर, Aniyomi एक्सटेंशन और बिल्ड बदलने के टूल पाने के लिए चालू करें। ये विकल्प अस्थिर हो सकते हैं।|Aktiviere dies für den Manga-Reader, Aniyomi-Erweiterungen und Werkzeuge zum Wechseln der Build-Version. Diese Optionen können instabil sein.
Enabled. Experimental options may be unfinished or unstable.|Activadas. Las opciones experimentales pueden estar incompletas o ser inestables.|Ativadas. As opções experimentais podem estar incompletas ou instáveis.|Activées. Les options expérimentales peuvent être inachevées ou instables.|चालू हैं। प्रयोगात्मक विकल्प अधूरे या अस्थिर हो सकते हैं।|Aktiviert. Experimentelle Optionen können unfertig oder instabil sein.
Manga reader requires Experimental options to be enabled.|El lector de manga requiere activar las Opciones experimentales.|O leitor de mangá exige que as Opções experimentais estejam ativadas.|Le lecteur de manga nécessite l’activation des Options expérimentales.|मंगा रीडर के लिए प्रयोगात्मक विकल्प चालू होने चाहिए।|Für den Manga-Reader müssen die experimentellen Optionen aktiviert sein.
Experimental options enabled. Manga, Aniyomi, and build-switching tools are available.|Opciones experimentales activadas. Están disponibles el manga, Aniyomi y las herramientas para cambiar de versión.|Opções experimentais ativadas. Mangá, Aniyomi e as ferramentas para trocar de versão estão disponíveis.|Options expérimentales activées. Le manga, Aniyomi et les outils de changement de version sont disponibles.|प्रयोगात्मक विकल्प चालू हैं। मंगा, Aniyomi और बिल्ड बदलने के टूल उपलब्ध हैं।|Experimentelle Optionen aktiviert. Manga, Aniyomi und Werkzeuge zum Wechseln der Build-Version sind verfügbar.
Experimental options disabled. Standard features remain available.|Opciones experimentales desactivadas. Las funciones estándar siguen disponibles.|Opções experimentais desativadas. Os recursos padrão continuam disponíveis.|Options expérimentales désactivées. Les fonctions standard restent disponibles.|प्रयोगात्मक विकल्प बंद हैं। सामान्य सुविधाएँ उपलब्ध रहेंगी।|Experimentelle Optionen deaktiviert. Standardfunktionen bleiben verfügbar.
Turn on Experimental options in System to show the manga reader.|Activa las Opciones experimentales en Sistema para mostrar el lector de manga.|Ative as Opções experimentais em Sistema para mostrar o leitor de mangá.|Activez les Options expérimentales dans Système pour afficher le lecteur de manga.|मंगा रीडर दिखाने के लिए सिस्टम में प्रयोगात्मक विकल्प चालू करें।|Aktiviere die experimentellen Optionen unter System, um den Manga-Reader anzuzeigen.
Aniyomi experiments require Experimental options to be enabled.|Los experimentos de Aniyomi requieren activar las Opciones experimentales.|Os experimentos do Aniyomi exigem que as Opções experimentais estejam ativadas.|Les expériences Aniyomi nécessitent l’activation des Options expérimentales.|Aniyomi प्रयोगों के लिए प्रयोगात्मक विकल्प चालू होने चाहिए।|Für Aniyomi-Experimente müssen die experimentellen Optionen aktiviert sein.
Changing or disabling Experimental options revokes execution approval. Seanime is unaffected.|Cambiar o desactivar las Opciones experimentales revoca la autorización de ejecución. Seanime no se ve afectado.|Alterar ou desativar as Opções experimentais revoga a autorização de execução. Seanime não é afetado.|Modifier ou désactiver les Options expérimentales révoque l’autorisation d’exécution. Seanime n’est pas affecté.|प्रयोगात्मक विकल्प बदलने या बंद करने से चलाने की अनुमति रद्द हो जाती है। Seanime पर कोई असर नहीं पड़ता।|Das Ändern oder Deaktivieren der experimentellen Optionen widerruft die Ausführungserlaubnis. Seanime bleibt unberührt.
Entries marked Blocked by Android remain visible for reference but cannot be selected. Android cannot replace this installation with a lower build code; Experimental options cannot bypass that rule. A same-or-higher-code rebuild can roll back while preserving data.|Las entradas Bloqueado por Android se muestran como referencia, pero no se pueden elegir. Android no permite instalar una versión con un código inferior; las Opciones experimentales no evitan esta regla. Una versión recompilada con un código igual o superior puede revertir cambios sin perder datos.|As entradas Bloqueado pelo Android ficam visíveis para consulta, mas não podem ser selecionadas. O Android não instala um código de compilação inferior; as Opções experimentais não contornam essa regra. Uma recompilação com código igual ou superior pode reverter sem perder dados.|Les entrées Bloqué par Android restent visibles, mais ne peuvent pas être choisies. Android ne peut pas installer un code de version inférieur ; les Options expérimentales ne contournent pas cette règle. Une recompilation avec un code identique ou supérieur permet de revenir en arrière sans perdre les données.|Android द्वारा रोकी गई प्रविष्टियाँ संदर्भ के लिए दिखती हैं, लेकिन चुनी नहीं जा सकतीं। Android कम बिल्ड कोड स्थापित नहीं कर सकता; प्रयोगात्मक विकल्प इस नियम को नहीं बदलते। समान या अधिक बिल्ड कोड वाला नया संस्करण डेटा बचाकर वापस जा सकता है।|Von Android blockierte Einträge bleiben sichtbar, können aber nicht gewählt werden. Android kann keinen niedrigeren Build-Code installieren; experimentelle Optionen umgehen diese Regel nicht. Ein Neubau mit gleichem oder höherem Code kann unter Erhalt der Daten zurückrollen.
Experimental features|Funciones experimentales|Recursos experimentais|Fonctionnalités expérimentales|प्रयोगात्मक सुविधाएँ|Experimentelle Funktionen
Turn on to access unfinished features such as Aniyomi extensions and release history. They may be unstable.|Actívalas para acceder a funciones sin terminar, como las extensiones de Aniyomi y el historial de versiones. Pueden ser inestables.|Ative para acessar recursos inacabados, como extensões do Aniyomi e o histórico de versões. Eles podem ser instáveis.|Activez-les pour accéder aux fonctions inachevées, comme les extensions Aniyomi et l’historique des versions. Elles peuvent être instables.|Aniyomi एक्सटेंशन और रिलीज़ इतिहास जैसी अधूरी सुविधाओं तक पहुँचने के लिए चालू करें। ये अस्थिर हो सकती हैं।|Aktiviere dies für unfertige Funktionen wie Aniyomi-Erweiterungen und den Versionsverlauf. Sie können instabil sein.
Enabled. Experimental features may be unfinished or unstable.|Activadas. Las funciones experimentales pueden estar sin terminar o ser inestables.|Ativados. Os recursos experimentais podem estar inacabados ou instáveis.|Activées. Les fonctionnalités expérimentales peuvent être inachevées ou instables.|चालू हैं। प्रयोगात्मक सुविधाएँ अधूरी या अस्थिर हो सकती हैं।|Aktiviert. Experimentelle Funktionen können unfertig oder instabil sein.
Experimental features enabled. Release history and experimental Aniyomi extensions are now available.|Funciones experimentales activadas. Ya están disponibles el historial de versiones y las extensiones experimentales de Aniyomi.|Recursos experimentais ativados. O histórico de versões e as extensões experimentais do Aniyomi estão disponíveis.|Fonctionnalités expérimentales activées. L’historique des versions et les extensions Aniyomi expérimentales sont maintenant disponibles.|प्रयोगात्मक सुविधाएँ चालू हैं। रिलीज़ इतिहास और प्रयोगात्मक Aniyomi एक्सटेंशन अब उपलब्ध हैं।|Experimentelle Funktionen aktiviert. Versionsverlauf und experimentelle Aniyomi-Erweiterungen sind jetzt verfügbar.
Experimental features disabled. Standard features remain available.|Funciones experimentales desactivadas. Las funciones estándar siguen disponibles.|Recursos experimentais desativados. Os recursos padrão continuam disponíveis.|Fonctionnalités expérimentales désactivées. Les fonctions standard restent disponibles.|प्रयोगात्मक सुविधाएँ बंद हैं। सामान्य सुविधाएँ उपलब्ध रहेंगी।|Experimentelle Funktionen deaktiviert. Standardfunktionen bleiben verfügbar.
Experimental update tools|Herramientas experimentales de actualización|Ferramentas experimentais de atualização|Outils de mise à jour expérimentaux|प्रयोगात्मक अपडेट टूल|Experimentelle Update-Werkzeuge
Aniyomi experiments require Experimental features to be enabled.|Los experimentos de Aniyomi requieren activar Funciones experimentales.|Os experimentos do Aniyomi exigem que Recursos experimentais esteja ativado.|Les fonctions expérimentales d’Aniyomi nécessitent l’activation des fonctionnalités expérimentales.|Aniyomi प्रयोगों के लिए प्रयोगात्मक सुविधाएँ चालू होनी चाहिए।|Für Aniyomi-Experimente müssen die experimentellen Funktionen aktiviert sein.
Changing or disabling Experimental features revokes execution approval. Seanime is unaffected.|Cambiar o desactivar las Funciones experimentales revoca la autorización de ejecución. Seanime no se ve afectado.|Alterar ou desativar os Recursos experimentais revoga a autorização de execução. O Seanime não é afetado.|Modifier ou désactiver les fonctionnalités expérimentales révoque l’autorisation d’exécution. Seanime n’est pas affecté.|प्रयोगात्मक सुविधाएँ बदलने या बंद करने से चलाने की अनुमति रद्द हो जाती है। Seanime पर कोई असर नहीं पड़ता।|Eine Änderung oder Deaktivierung der experimentellen Funktionen widerruft die Ausführungserlaubnis. Seanime bleibt unberührt.
Entries marked Blocked by Android remain visible for reference but cannot be selected. Android cannot replace this installation with a lower build code; Experimental features cannot bypass that rule. A same-or-higher-code rebuild can roll back while preserving data.|Las entradas Bloqueado por Android se muestran como referencia, pero no pueden elegirse. Android no permite instalar un código inferior; las Funciones experimentales no evitan esta regla. Una recompilación con código igual o superior permite volver atrás conservando datos.|As entradas Bloqueado pelo Android continuam visíveis como referência, mas não podem ser selecionadas. O Android não substitui esta instalação por um código de compilação inferior; os Recursos experimentais não contornam essa regra. Uma recompilação com código igual ou superior pode reverter preservando os dados.|Les entrées Bloqué par Android restent visibles pour référence, mais ne peuvent pas être sélectionnées. Android ne peut pas remplacer cette installation par un code de version inférieur ; les fonctionnalités expérimentales ne contournent pas cette règle. Une recompilation avec un code identique ou supérieur permet de revenir en arrière tout en conservant les données.|Android द्वारा रोकी गई प्रविष्टियाँ संदर्भ के लिए दिखती हैं, लेकिन चुनी नहीं जा सकतीं। Android इस इंस्टॉलेशन को कम बिल्ड कोड से नहीं बदल सकता; प्रयोगात्मक सुविधाएँ इस नियम को नहीं बदलतीं। समान या अधिक बिल्ड कोड वाला पुनर्निर्माण डेटा बचाकर पीछे जा सकता है।|Von Android blockierte Einträge bleiben als Referenz sichtbar, können aber nicht ausgewählt werden. Android kann diese Installation nicht durch einen niedrigeren Build-Code ersetzen; experimentelle Funktionen umgehen diese Regel nicht. Ein Neubau mit gleichem oder höherem Code kann unter Erhalt der Daten zurückrollen.
Debrid services are paid third-party services and are not affiliated with TetoTV. You need an active paid subscription from your chosen provider to use debrid features.|Los servicios de debrid son servicios de pago de terceros y no están afiliados a TetoTV. Necesitas una suscripción de pago activa del proveedor elegido para usar las funciones de debrid.|Os serviços de debrid são serviços pagos de terceiros e não são afiliados ao TetoTV. Você precisa de uma assinatura paga ativa do provedor escolhido para usar os recursos de debrid.|Les services de débridage sont des services tiers payants qui ne sont pas affiliés à TetoTV. Un abonnement payant actif auprès du fournisseur choisi est nécessaire pour utiliser les fonctions de débridage.|Debrid सेवाएँ तृतीय-पक्ष की सशुल्क सेवाएँ हैं और TetoTV से संबद्ध नहीं हैं। Debrid सुविधाओं के लिए चुने गए प्रदाता की सक्रिय सशुल्क सदस्यता चाहिए।|Debrid-Dienste sind kostenpflichtige Drittanbieterdienste und nicht mit TetoTV verbunden. Für Debrid-Funktionen brauchst du ein aktives kostenpflichtiges Abo beim gewählten Anbieter.
''';
