import 'catalog.dart';

final homeTranslations = catalogFromRows(const [
  [
    'Remove “{value1}” from local Watch History and Continue Watching? Connected anime trackers will not be changed.',
    '¿Eliminar “{value1}” del historial local y de Seguir viendo? Los servicios de seguimiento de anime conectados no se modificarán.',
    'Remover “{value1}” do histórico local e de Continuar assistindo? Os rastreadores de anime conectados não serão alterados.',
    'Supprimer « {value1} » de l’historique local et de Continuer à regarder ? Les services de suivi d’anime connectés ne seront pas modifiés.',
    '“{value1}” को स्थानीय देखने के इतिहास और देखना जारी रखें से हटाएँ? कनेक्ट किए गए एनीमे ट्रैकर नहीं बदले जाएंगे।',
    '„{value1}“ aus dem lokalen Wiedergabeverlauf und „Weiterschauen“ entfernen? Verbundene Anime-Tracker werden nicht geändert.',
  ],
  [
    "Press ↓ to browse all episodes",
    "Pulsa ↓ para ver todos los episodios",
    "Pressione ↓ para ver todos os episódios",
    "Appuyez sur ↓ pour voir tous les épisodes",
    "सभी एपिसोड देखने के लिए ↓ दबाएँ",
    "Drücke ↓, um alle Folgen anzuzeigen",
  ],
  [
    "Swipe up or tap to browse all episodes",
    "Desliza hacia arriba o toca para ver todos los episodios",
    "Deslize para cima ou toque para ver todos os episódios",
    "Balayez vers le haut ou touchez pour voir tous les épisodes",
    "सभी एपिसोड देखने के लिए ऊपर स्वाइप करें या टैप करें",
    "Wische nach oben oder tippe, um alle Folgen anzuzeigen",
  ],
  [
    "Search failed",
    "La búsqueda falló",
    "Falha na busca",
    "Échec de la recherche",
    "खोज विफल रही",
    "Suche fehlgeschlagen",
  ],
  [
    "No matches found",
    "Sin coincidencias",
    "Nenhum resultado",
    "Aucun résultat",
    "कोई मिलान नहीं मिला",
    "Keine Treffer",
  ],
  [
    "Try another title, spelling, or Japanese name.",
    "Prueba otro título, otra escritura o el nombre en japonés.",
    "Tente outro título, grafia ou o nome em japonês.",
    "Essayez un autre titre, une autre orthographe ou le nom japonais.",
    "दूसरा शीर्षक, वर्तनी या जापानी नाम आज़माएँ।",
    "Versuche einen anderen Titel, eine andere Schreibweise oder den japanischen Namen.",
  ],
  [
    "Find your next show",
    "Encuentra tu próxima serie",
    "Encontre sua próxima série",
    "Trouvez votre prochaine série",
    "अपना अगला शो खोजें",
    "Finde deine nächste Serie",
  ],
  [
    "Search results will appear here.",
    "Los resultados aparecerán aquí.",
    "Os resultados aparecerão aqui.",
    "Les résultats s’afficheront ici.",
    "खोज के परिणाम यहाँ दिखेंगे।",
    "Suchergebnisse werden hier angezeigt.",
  ],
  ["Current", "Actual", "Atual", "Actuel", "वर्तमान", "Aktuell"],
  ["Prequel", "Precuela", "Prequela", "Préquelle", "पूर्वकथा", "Vorgeschichte"],
  ["Sequel", "Secuela", "Sequência", "Suite", "अगली कड़ी", "Fortsetzung"],
  [
    "Spin-off",
    "Serie derivada",
    "Spin-off",
    "Série dérivée",
    "स्पिन-ऑफ़",
    "Ableger",
  ],
  [
    "Side story",
    "Historia paralela",
    "História paralela",
    "Histoire parallèle",
    "सहायक कहानी",
    "Nebengeschichte",
  ],
  [
    "Alternative",
    "Alternativa",
    "Alternativa",
    "Alternative",
    "वैकल्पिक",
    "Alternative",
  ],
  ["Summary", "Resumen", "Resumo", "Résumé", "सारांश", "Zusammenfassung"],
  [
    "Adaptation",
    "Adaptación",
    "Adaptação",
    "Adaptation",
    "रूपांतरण",
    "Adaption",
  ],
  ["Related", "Relacionada", "Relacionada", "Lié", "संबंधित", "Verwandt"],
  [
    "TV short",
    "Corto de TV",
    "Curta de TV",
    "Format court TV",
    "टीवी शॉर्ट",
    "TV-Kurzserie",
  ],
  [
    "Episode {episode} has not aired yet.",
    "El episodio {episode} aún no se ha emitido.",
    "O episódio {episode} ainda não foi ao ar.",
    "L’épisode {episode} n’a pas encore été diffusé.",
    "एपिसोड {episode} अभी प्रसारित नहीं हुआ है।",
    "Folge {episode} wurde noch nicht ausgestrahlt.",
  ],
  [
    "Not aired yet",
    "Aún no se ha emitido",
    "Ainda não foi ao ar",
    "Pas encore diffusé",
    "अभी प्रसारित नहीं हुआ",
    "Noch nicht ausgestrahlt",
  ],
  [
    "Start watching",
    "Empezar a ver",
    "Começar a assistir",
    "Commencer à regarder",
    "देखना शुरू करें",
    "Jetzt ansehen",
  ],
  [
    "Checking for updates…",
    "Buscando actualizaciones…",
    "Verificando atualizações…",
    "Recherche de mises à jour…",
    "अपडेट जाँचे जा रहे हैं…",
    "Suche nach Updates…",
  ],
  [
    "TetoTV is up to date",
    "TetoTV está actualizado",
    "TetoTV está atualizado",
    "TetoTV est à jour",
    "TetoTV अप-टू-डेट है",
    "TetoTV ist aktuell",
  ],
  [
    "Search and sort",
    "Buscar y ordenar",
    "Busca e ordenação",
    "Recherche et tri",
    "खोजें और क्रमबद्ध करें",
    "Suchen und sortieren",
  ],
  [
    "Type and themes",
    "Tipo y temas",
    "Tipo e temas",
    "Type et thèmes",
    "प्रकार और विषय",
    "Art und Themen",
  ],
  [
    "All genres",
    "Todos los géneros",
    "Todos os gêneros",
    "Tous les genres",
    "सभी शैलियाँ",
    "Alle Genres",
  ],
  [
    "All tags",
    "Todas las etiquetas",
    "Todas as tags",
    "Tous les tags",
    "सभी टैग",
    "Alle Tags",
  ],
  [
    "All formats",
    "Todos los formatos",
    "Todos os formatos",
    "Tous les formats",
    "सभी प्रारूप",
    "Alle Formate",
  ],
  [
    "All seasons",
    "Todas las temporadas",
    "Todas as temporadas",
    "Toutes les saisons",
    "सभी सीज़न",
    "Alle Saisons",
  ],
  [
    "Any year",
    "Cualquier año",
    "Qualquer ano",
    "Toutes les années",
    "कोई भी वर्ष",
    "Beliebiges Jahr",
  ],
  [
    "All statuses",
    "Todos los estados",
    "Todos os status",
    "Tous les statuts",
    "सभी स्थितियाँ",
    "Alle Status",
  ],
  [
    "All scores",
    "Todas las puntuaciones",
    "Todas as notas",
    "Toutes les notes",
    "सभी रेटिंग",
    "Alle Bewertungen",
  ],
  [
    "{score}/10 or higher",
    "{score}/10 o más",
    "{score}/10 ou mais",
    "{score}/10 ou plus",
    "{score}/10 या अधिक",
    "{score}/10 oder höher",
  ],
  [
    "Most popular",
    "Más populares",
    "Mais populares",
    "Les plus populaires",
    "सबसे लोकप्रिय",
    "Am beliebtesten",
  ],
  [
    "Trending now",
    "Tendencias",
    "Em alta",
    "Tendances du moment",
    "अभी ट्रेंड में",
    "Aktuell im Trend",
  ],
  [
    "Highest score",
    "Mejor puntuación",
    "Melhor nota",
    "Meilleures notes",
    "सबसे अधिक रेटिंग",
    "Höchste Bewertung",
  ],
  [
    "Newest releases",
    "Estrenos recientes",
    "Lançamentos recentes",
    "Dernières sorties",
    "नई रिलीज़",
    "Neueste Veröffentlichungen",
  ],
  [
    "Most favorited",
    "Más favoritos",
    "Mais favoritados",
    "Les plus appréciés",
    "सबसे अधिक पसंद किए गए",
    "Am häufigsten favorisiert",
  ],
  [
    "Title A–Z",
    "Título A–Z",
    "Título A–Z",
    "Titre A–Z",
    "शीर्षक A–Z",
    "Titel A–Z",
  ],
  [
    "TV Short",
    "Corto de TV",
    "Curta de TV",
    "Format court TV",
    "टीवी शॉर्ट",
    "TV-Kurzserie",
  ],
  ["Music", "Música", "Música", "Musique", "संगीत", "Musik"],
  [
    "Unreleased",
    "Sin estrenar",
    "Não lançado",
    "Pas encore sorti",
    "अप्रकाशित",
    "Unveröffentlicht",
  ],
  ["Cancelled", "Cancelado", "Cancelado", "Annulé", "रद्द", "Abgebrochen"],
  ["On hiatus", "En pausa", "Em pausa", "En pause", "विराम पर", "Pausiert"],
  [
    "Psychological",
    "Psicológico",
    "Psicológico",
    "Psychologique",
    "मनोवैज्ञानिक",
    "Psychologisch",
  ],
  ["School", "Escolar", "Escolar", "École", "स्कूल", "Schule"],
  [
    "Romantic Comedy",
    "Comedia romántica",
    "Comédia romântica",
    "Comédie romantique",
    "रोमांटिक कॉमेडी",
    "Romantische Komödie",
  ],
  [
    "Time Manipulation",
    "Manipulación del tiempo",
    "Manipulação do tempo",
    "Manipulation du temps",
    "समय में बदलाव",
    "Zeitmanipulation",
  ],
  [
    "Super Power",
    "Superpoderes",
    "Superpoderes",
    "Super-pouvoirs",
    "महाशक्ति",
    "Superkräfte",
  ],
  [
    "Martial Arts",
    "Artes marciales",
    "Artes marciais",
    "Arts martiaux",
    "मार्शल आर्ट",
    "Kampfsport",
  ],
  [
    "Historical",
    "Histórico",
    "Histórico",
    "Historique",
    "ऐतिहासिक",
    "Historisch",
  ],
  ["Military", "Militar", "Militar", "Militaire", "सैन्य", "Militär"],
  ["Demons", "Demonios", "Demônios", "Démons", "राक्षस", "Dämonen"],
  ["Vampire", "Vampiros", "Vampiros", "Vampires", "वैम्पायर", "Vampire"],
  ["Space", "Espacio", "Espaço", "Espace", "अंतरिक्ष", "Weltraum"],
  [
    "AniList rejected that filter combination. Reset the filters or try again.",
    "AniList rechazó esa combinación de filtros. Restablécelos o inténtalo de nuevo.",
    "O AniList rejeitou essa combinação de filtros. Redefina os filtros ou tente novamente.",
    "AniList a refusé cette combinaison de filtres. Réinitialisez-les ou réessayez.",
    "AniList ने फ़िल्टर का यह संयोजन अस्वीकार किया। फ़िल्टर रीसेट करें या फिर कोशिश करें।",
    "AniList hat diese Filterkombination abgelehnt. Setze die Filter zurück oder versuche es erneut.",
  ],
  [
    "Discover could not reach AniList. Check the connection and try again.",
    "Descubrir no pudo conectar con AniList. Comprueba la conexión e inténtalo de nuevo.",
    "Descobrir não conseguiu acessar o AniList. Verifique a conexão e tente novamente.",
    "Découvrir n’a pas pu joindre AniList. Vérifiez la connexion et réessayez.",
    "डिस्कवर AniList से जुड़ नहीं पाया। कनेक्शन जाँचें और फिर कोशिश करें।",
    "Entdecken konnte AniList nicht erreichen. Prüfe die Verbindung und versuche es erneut.",
  ],
  [
    "Discover could not load right now. Try again or reset the filters.",
    "No se pudo cargar Descubrir. Inténtalo de nuevo o restablece los filtros.",
    "Não foi possível carregar Descobrir. Tente novamente ou redefina os filtros.",
    "Impossible de charger Découvrir. Réessayez ou réinitialisez les filtres.",
    "अभी डिस्कवर लोड नहीं हुआ। फिर कोशिश करें या फ़िल्टर रीसेट करें।",
    "Entdecken konnte nicht geladen werden. Versuche es erneut oder setze die Filter zurück.",
  ],
  [
    "{count} titles",
    "{count} títulos",
    "{count} títulos",
    "{count} titres",
    "{count} शीर्षक",
    "{count} Titel",
  ],
  [
    "{count} episodes",
    "{count} episodios",
    "{count} episódios",
    "{count} épisodes",
    "{count} एपिसोड",
    "{count} Folgen",
  ],
  ["— watched", "— visto", "— assistido", "— regardé", "— देखा", "— gesehen"],
  [
    "{count}m watched",
    "{count} min vistos",
    "{count} min assistidos",
    "{count} min regardées",
    "{count} मिनट देखा",
    "{count} Min. gesehen",
  ],
  [
    "{count}h watched",
    "{count} h vistas",
    "{count} h assistidas",
    "{count} h regardées",
    "{count} घंटे देखा",
    "{count} Std. gesehen",
  ],
  [
    "Mean {score}/{maximum}",
    "Media {score}/{maximum}",
    "Média {score}/{maximum}",
    "Moyenne {score}/{maximum}",
    "औसत {score}/{maximum}",
    "Durchschnitt {score}/{maximum}",
  ],
  [
    "Add or update this show on every connected anime tracker.",
    "Añade o actualiza esta serie en todos los servicios de seguimiento de anime conectados.",
    "Adicione ou atualize esta série em todos os rastreadores de anime conectados.",
    "Ajoutez ou mettez à jour cette série sur tous les services de suivi d’anime connectés.",
    "हर जुड़े एनीमे ट्रैकर पर यह शो जोड़ें या अपडेट करें।",
    "Füge diese Serie bei allen verbundenen Anime-Trackern hinzu oder aktualisiere sie dort.",
  ],
  [
    "Connect an anime tracker to change this show's list status.",
    "Conecta un servicio de seguimiento de anime para cambiar el estado de esta serie en tu lista.",
    "Conecte um rastreador de anime para alterar o status desta série na sua lista.",
    "Connectez un service de suivi d’anime pour modifier le statut de cette série dans votre liste.",
    "सूची में इस शो की स्थिति बदलने के लिए कोई एनीमे ट्रैकर जोड़ें।",
    "Verbinde einen Anime-Tracker, um den Listenstatus dieser Serie zu ändern.",
  ],
  [
    "No followed shows are airing this week. Add a show to Watching or Planning on a connected tracker, then refresh your list.",
    "Ninguna serie seguida se emite esta semana. Añade una serie a En curso o Pendientes en un servicio de seguimiento conectado y actualiza la lista.",
    "Nenhuma série acompanhada vai ao ar esta semana. Adicione uma série a Assistindo ou Planejados em um rastreador conectado e atualize sua lista.",
    "Aucune série suivie n’est diffusée cette semaine. Ajoutez une série à En cours ou À voir sur un service de suivi connecté, puis actualisez votre liste.",
    "इस सप्ताह आपके फ़ॉलो किए शो प्रसारित नहीं हो रहे। किसी जुड़े ट्रैकर में शो को देख रहे हैं या देखने की योजना में जोड़ें, फिर सूची रीफ़्रेश करें।",
    "Diese Woche wird keine verfolgte Serie ausgestrahlt. Füge bei einem verbundenen Tracker eine Serie zu „Schaue ich“ oder „Geplant“ hinzu und aktualisiere deine Liste.",
  ],
  [
    "Your tracker calendar could not be loaded. Check the tracker connection in Settings, then select Refresh.",
    "No se pudo cargar tu calendario de seguimiento. Comprueba la conexión en Ajustes y selecciona Actualizar.",
    "Não foi possível carregar seu calendário de acompanhamento. Verifique a conexão nas Configurações e selecione Atualizar.",
    "Impossible de charger votre calendrier de suivi. Vérifiez la connexion dans les paramètres, puis sélectionnez Actualiser.",
    "आपका ट्रैकर कैलेंडर लोड नहीं हुआ। सेटिंग में ट्रैकर कनेक्शन जाँचें और रीफ़्रेश चुनें।",
    "Dein Tracker-Kalender konnte nicht geladen werden. Prüfe die Verbindung in den Einstellungen und wähle Aktualisieren.",
  ],
  [
    "REMOTE  /  CONTROLLER  /  KEYBOARD",
    "MANDO  /  CONTROL  /  TECLADO",
    "CONTROLE REMOTO  /  CONTROLE  /  TECLADO",
    "TÉLÉCOMMANDE  /  MANETTE  /  CLAVIER",
    "रिमोट  /  कंट्रोलर  /  कीबोर्ड",
    "FERNBEDIENUNG  /  CONTROLLER  /  TASTATUR",
  ],
  [
    "Activate to enter search text",
    "Activa para escribir la búsqueda",
    "Ative para digitar a busca",
    "Activez pour saisir la recherche",
    "खोजने के लिए चुनें",
    "Aktivieren, um einen Suchtext einzugeben",
  ],
  [
    "This link is invalid or incomplete.",
    "Este enlace no es válido o está incompleto.",
    "Este link é inválido ou está incompleto.",
    "Ce lien est invalide ou incomplet.",
    "यह लिंक अमान्य या अधूरा है।",
    "Dieser Link ist ungültig oder unvollständig.",
  ],
  [
    "Go home",
    "Ir al inicio",
    "Ir para o início",
    "Aller à l’accueil",
    "होम पर जाएँ",
    "Zur Startseite",
  ],
  [
    "Recently released titles are temporarily unavailable.",
    "Los estrenos no están disponibles temporalmente.",
    "Os lançamentos estão temporariamente indisponíveis.",
    "Les nouveautés sont temporairement indisponibles.",
    "हाल की रिलीज़ अभी उपलब्ध नहीं हैं।",
    "Neuerscheinungen sind vorübergehend nicht verfügbar.",
  ],
  [
    "No recently released titles are available yet.",
    "Aún no hay estrenos disponibles.",
    "Ainda não há lançamentos disponíveis.",
    "Aucune nouveauté disponible pour le moment.",
    "अभी कोई नई रिलीज़ उपलब्ध नहीं है।",
    "Es sind noch keine Neuerscheinungen verfügbar.",
  ],
  [
    "Episode {episode} airing soon",
    "Episodio {episode} se emite pronto",
    "Episódio {episode} vai ao ar em breve",
    "Épisode {episode} bientôt diffusé",
    "एपिसोड {episode} जल्द प्रसारित होगा",
    "Folge {episode} wird bald ausgestrahlt",
  ],
  [
    "next episode in less than an hour",
    "próximo episodio en menos de una hora",
    "próximo episódio em menos de uma hora",
    "prochain épisode dans moins d’une heure",
    "अगला एपिसोड एक घंटे से कम में",
    "nächste Folge in weniger als einer Stunde",
  ],
  [
    "next episode in {count} hour",
    "próximo episodio en {count} hora",
    "próximo episódio em {count} hora",
    "prochain épisode dans {count} heure",
    "अगला एपिसोड {count} घंटे में",
    "nächste Folge in {count} Stunde",
  ],
  [
    "next episode in {count} hours",
    "próximo episodio en {count} horas",
    "próximo episódio em {count} horas",
    "prochain épisode dans {count} heures",
    "अगला एपिसोड {count} घंटे में",
    "nächste Folge in {count} Stunden",
  ],
  [
    "next episode in {count} day",
    "próximo episodio en {count} día",
    "próximo episódio em {count} dia",
    "prochain épisode dans {count} jour",
    "अगला एपिसोड {count} दिन में",
    "nächste Folge in {count} Tag",
  ],
  [
    "next episode in {count} days",
    "próximo episodio en {count} días",
    "próximo episódio em {count} dias",
    "prochain épisode dans {count} jours",
    "अगला एपिसोड {count} दिन में",
    "nächste Folge in {count} Tagen",
  ],
  [
    "Episode {episode} has not aired yet",
    "El episodio {episode} aún no se ha emitido",
    "O episódio {episode} ainda não foi ao ar",
    "L’épisode {episode} n’a pas encore été diffusé",
    "एपिसोड {episode} अभी प्रसारित नहीं हुआ है",
    "Folge {episode} wurde noch nicht ausgestrahlt",
  ],
  [
    "This series has not aired yet.",
    "Esta serie aún no se ha estrenado.",
    "Esta série ainda não estreou.",
    "Cette série n’a pas encore été diffusée.",
    "यह सीरीज़ अभी प्रसारित नहीं हुई है।",
    "Diese Serie wurde noch nicht ausgestrahlt.",
  ],
  [
    "Expected premiere date: {date}",
    "Estreno previsto: {date}",
    "Estreia prevista: {date}",
    "Première prévue : {date}",
    "संभावित प्रीमियर तारीख: {date}",
    "Voraussichtlicher Serienstart: {date}",
  ],
  [
    "Expected air date: {date}",
    "Emisión prevista: {date}",
    "Exibição prevista: {date}",
    "Diffusion prévue : {date}",
    "संभावित प्रसारण तारीख: {date}",
    "Voraussichtliche Ausstrahlung: {date}",
  ],
  [
    "Title unavailable",
    "Título no disponible",
    "Título indisponível",
    "Titre indisponible",
    "शीर्षक उपलब्ध नहीं है",
    "Titel nicht verfügbar",
  ],
  [
    "Unaired",
    "Sin emitir",
    "Não exibido",
    "Non diffusé",
    "अप्रसारित",
    "Noch nicht ausgestrahlt",
  ],
  [
    "Not Yet Released",
    "Sin estrenar",
    "Ainda não lançado",
    "Pas encore sorti",
    "अभी रिलीज़ नहीं हुआ",
    "Noch nicht erschienen",
  ],
  [
    "Finished",
    "Finalizado",
    "Finalizado",
    "Terminé",
    "समाप्त",
    "Abgeschlossen",
  ],
  [
    "Releasing",
    "En emisión",
    "Em exibição",
    "En cours de diffusion",
    "प्रसारित हो रहा है",
    "Wird ausgestrahlt",
  ],
  [
    "Airing",
    "En emisión",
    "Em exibição",
    "En cours de diffusion",
    "प्रसारित हो रहा है",
    "Wird ausgestrahlt",
  ],
  [
    "Ready to check for updates",
    "Listo para buscar actualizaciones",
    "Pronto para verificar atualizações",
    "Prêt à rechercher des mises à jour",
    "अपडेट जाँचने के लिए तैयार",
    "Bereit zur Updatesuche",
  ],
  [
    "The update check failed",
    "No se pudieron buscar actualizaciones",
    "Não foi possível verificar atualizações",
    "La recherche de mises à jour a échoué",
    "अपडेट की जाँच विफल रही",
    "Die Updatesuche ist fehlgeschlagen",
  ],
  [
    "Downloading… {percent}%",
    "Descargando… {percent}%",
    "Baixando… {percent}%",
    "Téléchargement… {percent}%",
    "डाउनलोड हो रहा है… {percent}%",
    "Wird heruntergeladen… {percent}%",
  ],
  [
    "{count} min",
    "{count} min",
    "{count} min",
    "{count} min",
    "{count} मिनट",
    "{count} Min.",
  ],
  [
    'AUTOFILL',
    'AUTOCOMPLETAR',
    'PREENCHER',
    'REMPLISSAGE AUTO',
    'अपने आप भरें',
    'AUTOFÜLLEN',
  ],
  [
    'Add or manage profiles',
    'Añadir o gestionar perfiles',
    'Adicionar ou gerenciar perfis',
    'Ajouter ou gérer les profils',
    'प्रोफ़ाइल जोड़ें या प्रबंधित करें',
    'Profile hinzufügen oder verwalten',
  ],
  [
    'Airing calendar',
    'Calendario de emisión',
    'Calendário de exibição',
    'Calendrier de diffusion',
    'प्रसारण कैलेंडर',
    'Ausstrahlungskalender',
  ],
  [
    'Anime credits',
    'Créditos del anime',
    'Créditos do anime',
    'Crédits de l’anime',
    'एनीमे की टीम',
    'Anime-Mitwirkende',
  ],
  [
    'CHARACTERS & ENGLISH CAST',
    'PERSONAJES Y REPARTO EN INGLÉS',
    'PERSONAGENS E ELENCO EM INGLÊS',
    'PERSONNAGES ET VOIX ANGLAISES',
    'पात्र और अंग्रेज़ी कलाकार',
    'FIGUREN UND ENGLISCHE SPRECHER',
  ],
  ['Check', 'Comprobar', 'Verificar', 'Vérifier', 'जाँचें', 'Prüfen'],
  [
    'Choose only the filters you care about.',
    'Elige solo los filtros que te interesen.',
    'Escolha apenas os filtros que desejar.',
    'Choisissez uniquement les filtres utiles.',
    'केवल अपने काम के फ़िल्टर चुनें।',
    'Wähle nur die gewünschten Filter.',
  ],
  [
    'Clipboard is unavailable on this device.',
    'El portapapeles no está disponible en este dispositivo.',
    'A área de transferência não está disponível neste dispositivo.',
    'Le presse-papiers est indisponible sur cet appareil.',
    'इस डिवाइस पर क्लिपबोर्ड उपलब्ध नहीं है।',
    'Die Zwischenablage ist auf diesem Gerät nicht verfügbar.',
  ],
  [
    'Close notifications',
    'Cerrar notificaciones',
    'Fechar notificações',
    'Fermer les notifications',
    'सूचनाएँ बंद करें',
    'Benachrichtigungen schließen',
  ],
  [
    'Could not load anime',
    'No se pudo cargar el anime',
    'Não foi possível carregar o anime',
    'Impossible de charger l’anime',
    'एनीमे लोड नहीं हो सका',
    'Anime konnte nicht geladen werden',
  ],
  [
    'Could not build franchise: {value1}',
    'No se pudo cargar la franquicia: {value1}',
    'Não foi possível carregar a franquia: {value1}',
    'Impossible de charger la franchise : {value1}',
    'फ़्रैंचाइज़ लोड नहीं हो सकी: {value1}',
    'Franchise konnte nicht geladen werden: {value1}',
  ],
  [
    'Could not load credits: {value1}',
    'No se pudieron cargar los créditos: {value1}',
    'Não foi possível carregar os créditos: {value1}',
    'Impossible de charger les crédits : {value1}',
    'टीम की जानकारी लोड नहीं हो सकी: {value1}',
    'Mitwirkende konnten nicht geladen werden: {value1}',
  ],
  [
    'Could not load schedule: {value1}',
    'No se pudo cargar el calendario: {value1}',
    'Não foi possível carregar o calendário: {value1}',
    'Impossible de charger le calendrier : {value1}',
    'समय-सारणी लोड नहीं हो सकी: {value1}',
    'Zeitplan konnte nicht geladen werden: {value1}',
  ],
  [
    'Could not load titles: {value1}',
    'No se pudieron cargar los títulos: {value1}',
    'Não foi possível carregar os títulos: {value1}',
    'Impossible de charger les titres : {value1}',
    'शीर्षक लोड नहीं हो सके: {value1}',
    'Titel konnten nicht geladen werden: {value1}',
  ],
  [
    'Could not open SIMKL on this device.',
    'No se pudo abrir SIMKL en este dispositivo.',
    'Não foi possível abrir o SIMKL neste dispositivo.',
    'Impossible d’ouvrir SIMKL sur cet appareil.',
    'इस डिवाइस पर SIMKL नहीं खुल सका।',
    'SIMKL konnte auf diesem Gerät nicht geöffnet werden.',
  ],
  [
    'Could not remove local watch history.',
    'No se pudo borrar el historial local.',
    'Não foi possível remover o histórico local.',
    'Impossible de supprimer l’historique local.',
    'स्थानीय देखने का इतिहास नहीं हट सका।',
    'Der lokale Wiedergabeverlauf konnte nicht entfernt werden.',
  ],
  [
    'Discover title',
    'Explorar título',
    'Explorar título',
    'Découvrir un titre',
    'शीर्षक खोजें',
    'Titel entdecken',
  ],
  [
    'Episode {value1}',
    'Episodio {value1}',
    'Episódio {value1}',
    'Épisode {value1}',
    'एपिसोड {value1}',
    'Folge {value1}',
  ],
  [
    'Episode {value1} of {value2}',
    'Episodio {value1} de {value2}',
    'Episódio {value1} de {value2}',
    'Épisode {value1} sur {value2}',
    '{value2} में से एपिसोड {value1}',
    'Folge {value1} von {value2}',
  ],
  [
    'Episode {value1} of {value2}. Choose episode number',
    'Episodio {value1} de {value2}. Elegir número de episodio',
    'Episódio {value1} de {value2}. Escolher número do episódio',
    'Épisode {value1} sur {value2}. Choisir le numéro',
    '{value2} में से एपिसोड {value1}। एपिसोड संख्या चुनें',
    'Folge {value1} von {value2}. Folgennummer wählen',
  ],
  [
    'Episode {value1}{value2}',
    'Episodio {value1}{value2}',
    'Episódio {value1}{value2}',
    'Épisode {value1}{value2}',
    'एपिसोड {value1}{value2}',
    'Folge {value1}{value2}',
  ],
  [
    'EP {value1}',
    'EP {value1}',
    'EP {value1}',
    'ÉP {value1}',
    'एपि {value1}',
    'FOLGE {value1}',
  ],
  [
    'EP {value1} / {value2}',
    'EP {value1} / {value2}',
    'EP {value1} / {value2}',
    'ÉP {value1} / {value2}',
    'एपि {value1} / {value2}',
    'FOLGE {value1} / {value2}',
  ],
  [
    'EPISODE {value1} OF {value2}',
    'EPISODIO {value1} DE {value2}',
    'EPISÓDIO {value1} DE {value2}',
    'ÉPISODE {value1} SUR {value2}',
    '{value2} में से एपिसोड {value1}',
    'FOLGE {value1} VON {value2}',
  ],
  ['FEATURED', 'DESTACADO', 'DESTAQUE', 'À LA UNE', 'खास', 'EMPFOHLEN'],
  [
    'Find your next anime',
    'Encuentra tu próximo anime',
    'Encontre seu próximo anime',
    'Trouvez votre prochain anime',
    'अपना अगला एनीमे खोजें',
    'Finde deinen nächsten Anime',
  ],
  [
    'Home refreshed.',
    'Inicio actualizado.',
    'Início atualizado.',
    'Accueil actualisé.',
    'होम रीफ़्रेश हो गया।',
    'Startseite aktualisiert.',
  ],
  [
    'Refreshing Home…',
    'Actualizando inicio…',
    'Atualizando início…',
    'Actualisation de l’accueil…',
    'होम रीफ़्रेश हो रहा है…',
    'Startseite wird aktualisiert…',
  ],
  [
    'Include adult titles',
    'Incluir títulos para adultos',
    'Incluir títulos adultos',
    'Inclure les titres pour adultes',
    'वयस्क सामग्री शामिल करें',
    'Titel für Erwachsene einschließen',
  ],
  ['LOCAL', 'LOCAL', 'LOCAL', 'LOCAL', 'स्थानीय', 'LOKAL'],
  [
    'Leave Party',
    'Salir de la sala',
    'Sair da sala',
    'Quitter la salle',
    'पार्टी छोड़ें',
    'Watchparty verlassen',
  ],
  [
    'Left or Back closes notifications',
    'Izquierda o Atrás cierra las notificaciones',
    'Esquerda ou Voltar fecha as notificações',
    'Gauche ou Retour ferme les notifications',
    'बाएँ या वापस से सूचनाएँ बंद होती हैं',
    'Links oder Zurück schließt die Benachrichtigungen',
  ],
  [
    'Left or Back closes this menu',
    'Izquierda o Atrás cierra este menú',
    'Esquerda ou Voltar fecha este menu',
    'Gauche ou Retour ferme ce menu',
    'बाएँ या वापस से यह मेनू बंद होता है',
    'Links oder Zurück schließt dieses Menü',
  ],
  [
    'Loading artwork',
    'Cargando imágenes',
    'Carregando imagens',
    'Chargement des images',
    'चित्र लोड हो रहे हैं',
    'Bilder werden geladen',
  ],
  [
    'No anime matched these filters.',
    'Ningún anime coincide con estos filtros.',
    'Nenhum anime corresponde a estes filtros.',
    'Aucun anime ne correspond à ces filtres.',
    'इन फ़िल्टर से कोई एनीमे नहीं मिला।',
    'Kein Anime entspricht diesen Filtern.',
  ],
  [
    'No synopsis is available.',
    'No hay sinopsis disponible.',
    'Nenhuma sinopse disponível.',
    'Aucun synopsis disponible.',
    'सारांश उपलब्ध नहीं है।',
    'Keine Inhaltsangabe verfügbar.',
  ],
  [
    'Notifications, {value1}',
    'Notificaciones, {value1}',
    'Notificações, {value1}',
    'Notifications, {value1}',
    'सूचनाएँ, {value1}',
    'Benachrichtigungen, {value1}',
  ],
  [
    'Off by default',
    'Desactivado por defecto',
    'Desativado por padrão',
    'Désactivé par défaut',
    'डिफ़ॉल्ट रूप से बंद',
    'Standardmäßig aus',
  ],
  [
    'Open show',
    'Abrir serie',
    'Abrir série',
    'Ouvrir la série',
    'सीरीज़ खोलें',
    'Serie öffnen',
  ],
  [
    'Prequels, sequels, movies, OVAs, specials, and spin-offs',
    'Precuelas, secuelas, películas, OVA, especiales y series derivadas',
    'Prequelas, sequências, filmes, OVAs, especiais e derivados',
    'Pré suites, suites, films, OVA, épisodes spéciaux et séries dérivées',
    'प्रीक्वल, सीक्वल, फ़िल्में, OVA, विशेष एपिसोड और स्पिन-ऑफ़',
    'Vorgeschichten, Fortsetzungen, Filme, OVAs, Specials und Ableger',
  ],
  [
    'Recommended watch order',
    'Orden de visualización recomendado',
    'Ordem recomendada para assistir',
    'Ordre de visionnage recommandé',
    'देखने का सुझाया गया क्रम',
    'Empfohlene Reihenfolge',
  ],
  [
    'Refresh calendar',
    'Actualizar calendario',
    'Atualizar calendário',
    'Actualiser le calendrier',
    'कैलेंडर रीफ़्रेश करें',
    'Kalender aktualisieren',
  ],
  [
    'Reminder set for 10 minutes before airtime.',
    'Recordatorio programado 10 minutos antes de la emisión.',
    'Lembrete definido para 10 minutos antes da exibição.',
    'Rappel programmé 10 minutes avant la diffusion.',
    'प्रसारण से 10 मिनट पहले का रिमाइंडर सेट है।',
    'Erinnerung auf 10 Minuten vor Ausstrahlung gesetzt.',
  ],
  [
    'Remove from this TV?',
    '¿Quitar de este televisor?',
    'Remover desta TV?',
    'Supprimer de cette TV ?',
    'इस टीवी से हटाएँ?',
    'Von diesem Fernseher entfernen?',
  ],
  [
    'Remove locally',
    'Quitar de este dispositivo',
    'Remover deste dispositivo',
    'Supprimer localement',
    'स्थानीय रूप से हटाएँ',
    'Lokal entfernen',
  ],
  [
    'Results for “{value1}”',
    'Resultados para «{value1}»',
    'Resultados para “{value1}”',
    'Résultats pour « {value1} »',
    '“{value1}” के परिणाम',
    'Ergebnisse für „{value1}“',
  ],
  [
    'SERIES ART',
    'IMAGEN DE LA SERIE',
    'IMAGEM DA SÉRIE',
    'ILLUSTRATION DE LA SÉRIE',
    'सीरीज़ का चित्र',
    'SERIENBILD',
  ],
  ['STAFF', 'EQUIPO', 'EQUIPE', 'ÉQUIPE', 'टीम', 'TEAM'],
  ['STUDIOS', 'ESTUDIOS', 'ESTÚDIOS', 'STUDIOS', 'स्टूडियो', 'STUDIOS'],
  [
    'SWITCH PROFILE',
    'CAMBIAR PERFIL',
    'TROCAR PERFIL',
    'CHANGER DE PROFIL',
    'प्रोफ़ाइल बदलें',
    'PROFIL WECHSELN',
  ],
  [
    'Search by title',
    'Buscar por título',
    'Buscar por título',
    'Rechercher par titre',
    'शीर्षक से खोजें',
    'Nach Titel suchen',
  ],
  [
    'Show results',
    'Mostrar resultados',
    'Mostrar resultados',
    'Afficher les résultats',
    'परिणाम दिखाएँ',
    'Ergebnisse anzeigen',
  ],
  [
    'Skip filler',
    'Saltar relleno',
    'Pular fillers',
    'Passer les hors-série',
    'फ़िलर छोड़ें',
    'Filler überspringen',
  ],
  [
    'Skip filler preference could not be saved.',
    'No se pudo guardar la preferencia de relleno.',
    'Não foi possível salvar a preferência de fillers.',
    'Impossible d’enregistrer le réglage des hors-série.',
    'फ़िलर छोड़ने की पसंद सहेजी नहीं जा सकी।',
    'Filler-Einstellung konnte nicht gespeichert werden.',
  ],
  [
    'Some Home shelves could not be refreshed.',
    'No se pudieron actualizar algunas secciones de inicio.',
    'Algumas seções do início não puderam ser atualizadas.',
    'Certaines sections de l’accueil n’ont pas pu être actualisées.',
    'होम के कुछ भाग रीफ़्रेश नहीं हो सके।',
    'Einige Startseitenbereiche konnten nicht aktualisiert werden.',
  ],
  [
    'Start Watch Party',
    'Crear sala compartida',
    'Criar sala de exibição',
    'Créer un visionnage partagé',
    'वॉच पार्टी शुरू करें',
    'Watchparty starten',
  ],
  [
    'Start typing to search anime',
    'Escribe para buscar anime',
    'Digite para buscar anime',
    'Saisissez un nom pour rechercher un anime',
    'एनीमे खोजने के लिए टाइप करें',
    'Tippe, um Anime zu suchen',
  ],
  [
    'Starting…',
    'Iniciando…',
    'Iniciando…',
    'Démarrage…',
    'शुरू हो रहा है…',
    'Wird gestartet…',
  ],
  [
    'Status: {value1}',
    'Estado: {value1}',
    'Status: {value1}',
    'Statut : {value1}',
    'स्थिति: {value1}',
    'Status: {value1}',
  ],
  [
    'Stopped preparing the remaining season downloads.',
    'Se detuvo la preparación de las descargas restantes.',
    'A preparação dos downloads restantes foi interrompida.',
    'Préparation des téléchargements restants arrêtée.',
    'सीज़न के बाकी डाउनलोड की तैयारी रोक दी गई।',
    'Vorbereitung der übrigen Staffel-Downloads gestoppt.',
  ],
  [
    'Stored only on this device • no tracker login required',
    'Guardado solo aquí • no requiere cuenta de seguimiento',
    'Salvo só neste dispositivo • não exige conta de rastreamento',
    'Stocké sur cet appareil • aucun compte de suivi requis',
    'केवल इस डिवाइस पर • ट्रैकर में लॉगिन ज़रूरी नहीं',
    'Nur auf diesem Gerät • kein Tracker-Konto nötig',
  ],
  [
    'Studio titles',
    'Títulos del estudio',
    'Títulos do estúdio',
    'Titres du studio',
    'स्टूडियो के शीर्षक',
    'Titel des Studios',
  ],
  [
    'This airing is too soon for a reminder.',
    'Esta emisión empieza demasiado pronto para un recordatorio.',
    'Esta exibição está próxima demais para um lembrete.',
    'Cette diffusion est trop proche pour un rappel.',
    'इस प्रसारण के लिए रिमाइंडर का समय निकल चुका है।',
    'Diese Ausstrahlung beginnt zu bald für eine Erinnerung.',
  ],
  [
    'Times use your device timezone',
    'Las horas usan la zona horaria de tu dispositivo',
    'Os horários usam o fuso do dispositivo',
    'Les horaires utilisent le fuseau de votre appareil',
    'समय आपके डिवाइस के समय क्षेत्र में हैं',
    'Zeiten entsprechen der Zeitzone deines Geräts',
  ],
  ['Title', 'Título', 'Título', 'Titre', 'शीर्षक', 'Titel'],
  [
    'Title, synonym, or Japanese name',
    'Título, nombre alternativo o nombre japonés',
    'Título, nome alternativo ou nome japonês',
    'Titre, nom alternatif ou nom japonais',
    'शीर्षक, वैकल्पिक नाम या जापानी नाम',
    'Titel, Alternativname oder japanischer Name',
  ],
  [
    'Update status on {value1}',
    'Actualizar estado en {value1}',
    'Atualizar status no {value1}',
    'Mettre à jour le statut sur {value1}',
    '{value1} पर स्थिति अपडेट करें',
    'Status auf {value1} aktualisieren',
  ],
  [
    'View on SIMKL',
    'Ver en SIMKL',
    'Ver no SIMKL',
    'Voir sur SIMKL',
    'SIMKL पर देखें',
    'Auf SIMKL ansehen',
  ],
  [
    "What's new in TetoTV",
    'Novedades de TetoTV',
    'Novidades do TetoTV',
    'Nouveautés de TetoTV',
    'TetoTV में नया क्या है',
    'Neu in TetoTV',
  ],
  [
    "You're all caught up",
    'Estás al día',
    'Tudo em dia',
    'Vous êtes à jour',
    'आप पूरी तरह अपडेट हैं',
    'Du bist auf dem neuesten Stand',
  ],
  [
    '{value1} episodes',
    '{value1} episodios',
    '{value1} episódios',
    '{value1} épisodes',
    '{value1} एपिसोड',
    '{value1} Folgen',
  ],
  [
    '{value1} moved to {value2}.',
    '{value1} se movió a {value2}.',
    '{value1} movido para {value2}.',
    '{value1} déplacé vers {value2}.',
    '{value1} को {value2} में ले जाया गया।',
    '{value1} nach {value2} verschoben.',
  ],
  [
    '{value1} of {value2}',
    '{value1} de {value2}',
    '{value1} de {value2}',
    '{value1} sur {value2}',
    '{value2} में से {value1}',
    '{value1} von {value2}',
  ],
  [
    '{value1} of {value2} selected',
    '{value1} de {value2} seleccionado',
    '{value1} de {value2} selecionado',
    '{value1} sur {value2} sélectionné',
    '{value2} में से {value1} चुना गया',
    '{value1} von {value2} ausgewählt',
  ],
  [
    '{value1} people in this Watch Party room',
    '{value1} personas en esta sala',
    '{value1} pessoas nesta sala',
    '{value1} personnes dans cette salle',
    'इस वॉच पार्टी में {value1} लोग',
    '{value1} Personen in dieser Watchparty',
  ],
  [
    '{value1} • Episode {value2}',
    '{value1} • Episodio {value2}',
    '{value1} • Episódio {value2}',
    '{value1} • Épisode {value2}',
    '{value1} • एपिसोड {value2}',
    '{value1} • Folge {value2}',
  ],
  [
    '{value1}. Double select to copy code.',
    '{value1}. Pulsa dos veces para copiar el código.',
    '{value1}. Pressione duas vezes para copiar o código.',
    '{value1}. Appuyez deux fois pour copier le code.',
    '{value1}। कोड कॉपी करने के लिए दो बार चुनें।',
    '{value1}. Zweimal auswählen, um den Code zu kopieren.',
  ],
  [
    '{value1}. Double select to copy link.',
    '{value1}. Pulsa dos veces para copiar el enlace.',
    '{value1}. Pressione duas vezes para copiar o link.',
    '{value1}. Appuyez deux fois pour copier le lien.',
    '{value1}। लिंक कॉपी करने के लिए दो बार चुनें।',
    '{value1}. Zweimal auswählen, um den Link zu kopieren.',
  ],
  [
    'Continue watching',
    'Seguir viendo',
    'Continuar assistindo',
    'Continuer à regarder',
    'देखना जारी रखें',
    'Weiterschauen',
  ],
  [
    'Recently released',
    'Recién estrenados',
    'Lançados recentemente',
    'Sorties récentes',
    'हाल में रिलीज़',
    'Kürzlich erschienen',
  ],
  [
    'Recently watched',
    'Vistos recientemente',
    'Assistidos recentemente',
    'Vus récemment',
    'हाल में देखे गए',
    'Kürzlich angesehen',
  ],
  ['Trending', 'Tendencias', 'Em alta', 'Tendances', 'ट्रेंडिंग', 'Im Trend'],
  ['Popular', 'Populares', 'Populares', 'Populaires', 'लोकप्रिय', 'Beliebt'],
  [
    'Top rated',
    'Mejor valorados',
    'Mais bem avaliados',
    'Les mieux notés',
    'सबसे अधिक रेटिंग',
    'Bestbewertet',
  ],
  [
    'Upcoming',
    'Próximamente',
    'Em breve',
    'À venir',
    'जल्द आ रहा है',
    'Demnächst',
  ],
  [
    'Watching',
    'Viendo',
    'Assistindo',
    'En cours',
    'देख रहे हैं',
    'Wird angesehen',
  ],
  [
    'Planning',
    'Pendiente',
    'Planejados',
    'À voir',
    'देखने की योजना',
    'Geplant',
  ],
  [
    'Dropped',
    'Abandonado',
    'Abandonado',
    'Abandonné',
    'छोड़ा गया',
    'Abgebrochen',
  ],
  [
    'Repeating',
    'Volviendo a ver',
    'Reassistindo',
    'Revisionnage',
    'फिर से देख रहे हैं',
    'Erneut ansehen',
  ],
  ['Genre', 'Género', 'Gênero', 'Genre', 'शैली', 'Genre'],
  ['Tag', 'Etiqueta', 'Tag', 'Étiquette', 'टैग', 'Schlagwort'],
  ['Format', 'Formato', 'Formato', 'Format', 'प्रारूप', 'Format'],
  ['Year', 'Año', 'Ano', 'Année', 'साल', 'Jahr'],
  [
    'Release year',
    'Año de estreno',
    'Ano de lançamento',
    'Année de sortie',
    'रिलीज़ का साल',
    'Erscheinungsjahr',
  ],
  [
    'Release status',
    'Estado de emisión',
    'Status de lançamento',
    'Statut de diffusion',
    'रिलीज़ की स्थिति',
    'Veröffentlichungsstatus',
  ],
  [
    'Minimum score',
    'Puntuación mínima',
    'Nota mínima',
    'Note minimale',
    'न्यूनतम रेटिंग',
    'Mindestbewertung',
  ],
  [
    'Sort results',
    'Ordenar resultados',
    'Ordenar resultados',
    'Trier les résultats',
    'परिणाम क्रमबद्ध करें',
    'Ergebnisse sortieren',
  ],
  ['Winter', 'Invierno', 'Inverno', 'Hiver', 'सर्दी', 'Winter'],
  ['Spring', 'Primavera', 'Primavera', 'Printemps', 'वसंत', 'Frühling'],
  ['Summer', 'Verano', 'Verão', 'Été', 'गर्मी', 'Sommer'],
  ['Fall', 'Otoño', 'Outono', 'Automne', 'पतझड़', 'Herbst'],
  ['Movie', 'Película', 'Filme', 'Film', 'फ़िल्म', 'Film'],
  ['Special', 'Especial', 'Especial', 'Spécial', 'विशेष', 'Special'],
  ['Action', 'Acción', 'Ação', 'Action', 'ऐक्शन', 'Action'],
  ['Adventure', 'Aventura', 'Aventura', 'Aventure', 'रोमांच', 'Abenteuer'],
  ['Comedy', 'Comedia', 'Comédia', 'Comédie', 'कॉमेडी', 'Komödie'],
  ['Drama', 'Drama', 'Drama', 'Drame', 'ड्रामा', 'Drama'],
  ['Fantasy', 'Fantasía', 'Fantasia', 'Fantastique', 'फ़ैंटेसी', 'Fantasy'],
  ['Horror', 'Terror', 'Terror', 'Horreur', 'हॉरर', 'Horror'],
  ['Mystery', 'Misterio', 'Mistério', 'Mystère', 'रहस्य', 'Mystery'],
  ['Romance', 'Romance', 'Romance', 'Romance', 'रोमांस', 'Romantik'],
  [
    'Sci-Fi',
    'Ciencia ficción',
    'Ficção científica',
    'Science-fiction',
    'विज्ञान कथा',
    'Science-Fiction',
  ],
  [
    'Slice of Life',
    'Vida cotidiana',
    'Cotidiano',
    'Tranche de vie',
    'रोज़मर्रा की ज़िंदगी',
    'Alltag',
  ],
  ['Sports', 'Deportes', 'Esportes', 'Sport', 'खेल', 'Sport'],
  [
    'Supernatural',
    'Sobrenatural',
    'Sobrenatural',
    'Surnaturel',
    'अलौकिक',
    'Übernatürlich',
  ],
  ['Thriller', 'Suspense', 'Suspense', 'Thriller', 'थ्रिलर', 'Thriller'],
]);
