import 'catalog.dart';

// App-owned reader, chapter controls and safe page-loading errors only.
// Titles, source responses and ephemeral request capabilities are never keys.
final mangaReaderTranslations = catalogFromRows(
  _mangaReaderRows.trim().split('\n').map((row) => row.split('|')).toList(),
);

const _mangaReaderRows = r'''
You can change this later in Settings.|Puedes cambiarlo más tarde en Ajustes.|Você pode alterar isso depois nas Configurações.|Vous pourrez modifier ce choix plus tard dans les paramètres.|आप इसे बाद में सेटिंग्स में बदल सकते हैं।|Du kannst dies später in den Einstellungen ändern.
Manga reader|Lector de manga|Leitor de mangá|Lecteur de mangas|मंगा रीडर|Manga-Reader
Manage local libraries, Manga, Watch Party, and offline viewing.|Gestiona bibliotecas locales, manga, salas de reproducción y contenido sin conexión.|Gerencie bibliotecas locais, mangá, Sala de reprodução e conteúdo offline.|Gérez les bibliothèques locales, les mangas, le visionnage partagé et la lecture hors ligne.|स्थानीय लाइब्रेरी, मंगा, वॉच पार्टी और ऑफ़लाइन सामग्री प्रबंधित करें।|Verwalte lokale Bibliotheken, Manga, Watch Party und Offline-Wiedergabe.
Available in navigation with your library, sources, downloads, and reader settings.|Disponible en la navegación con tu biblioteca, fuentes, descargas y ajustes del lector.|Disponível na navegação com sua biblioteca, fontes, downloads e configurações do leitor.|Disponible dans la navigation avec votre bibliothèque, vos sources, vos téléchargements et les paramètres du lecteur.|नेविगेशन में आपकी लाइब्रेरी, स्रोतों, डाउनलोड और रीडर सेटिंग के साथ उपलब्ध है।|In der Navigation mit Bibliothek, Quellen, Downloads und Leseeinstellungen verfügbar.
Hidden from navigation. Your manga library and downloads stay safely on this device.|Oculto de la navegación. Tu biblioteca de manga y tus descargas permanecen seguras en este dispositivo.|Oculto da navegação. Sua biblioteca de mangá e seus downloads permanecem seguros neste dispositivo.|Masqué de la navigation. Votre bibliothèque de mangas et vos téléchargements restent en sécurité sur cet appareil.|नेविगेशन से छिपा हुआ है। आपकी मंगा लाइब्रेरी और डाउनलोड इस डिवाइस पर सुरक्षित रहते हैं।|Aus der Navigation ausgeblendet. Deine Manga-Bibliothek und Downloads bleiben sicher auf diesem Gerät.
Zoom and pan|Ampliar y desplazar|Ampliar e mover|Zoom et déplacement|ज़ूम और पैन|Zoomen und verschieben
Zoom out|Alejar|Diminuir zoom|Dézoomer|ज़ूम घटाएँ|Verkleinern
Zoom in|Acercar|Aumentar zoom|Zoomer|ज़ूम बढ़ाएँ|Vergrößern
Exit zoom|Salir del zoom|Sair do zoom|Quitter le zoom|ज़ूम से बाहर निकलें|Zoom beenden
Zoom mode • Arrows pan • OK zooms in • Page Down zooms out • Back resets|Modo zoom • Flechas: desplazar • OK: acercar • Av Pág: alejar • Atrás: restablecer|Modo zoom • Setas: mover • OK: ampliar • Page Down: reduzir • Voltar: redefinir|Mode zoom • Flèches : déplacer • OK : agrandir • Page suivante : réduire • Retour : réinitialiser|ज़ूम मोड • तीर: पैन • OK: ज़ूम बढ़ाएँ • Page Down: ज़ूम घटाएँ • वापस: रीसेट|Zoommodus • Pfeile: verschieben • OK: vergrößern • Bild ab: verkleinern • Zurück: zurücksetzen
Previous chapter|Capítulo anterior|Capítulo anterior|Chapitre précédent|पिछला अध्याय|Vorheriges Kapitel
Next chapter|Capítulo siguiente|Próximo capítulo|Chapitre suivant|अगला अध्याय|Nächstes Kapitel
Chapter complete|Capítulo terminado|Capítulo concluído|Chapitre terminé|अध्याय पूरा हुआ|Kapitel abgeschlossen
Chapter complete • Next chapter|Capítulo terminado • Capítulo siguiente|Capítulo concluído • Próximo capítulo|Chapitre terminé • Chapitre suivant|अध्याय पूरा हुआ • अगला अध्याय|Kapitel abgeschlossen • Nächstes Kapitel
Retry page|Reintentar página|Tentar página novamente|Réessayer la page|पृष्ठ फिर लोड करें|Seite erneut laden
Reload page|Recargar página|Recarregar página|Recharger la page|पृष्ठ दोबारा लोड करें|Seite neu laden
If retry fails, return to the chapter list and reopen this chapter to refresh source access.|Si falla el reintento, vuelve a la lista de capítulos y abre este capítulo de nuevo para renovar el acceso a la fuente.|Se falhar novamente, volte à lista de capítulos e reabra este capítulo para renovar o acesso à fonte.|Si la nouvelle tentative échoue, revenez à la liste des chapitres et rouvrez ce chapitre pour renouveler l’accès à la source.|यदि फिर कोशिश करने पर भी लोड न हो, तो स्रोत की पहुँच ताज़ा करने के लिए अध्याय सूची पर लौटकर यह अध्याय दोबारा खोलें।|Falls es erneut fehlschlägt, zur Kapitelliste zurückkehren und dieses Kapitel erneut öffnen, um den Quellenzugriff zu erneuern.
Check your connection and retry this page. Your reading position is unchanged.|Comprueba la conexión y vuelve a intentar esta página. Tu posición de lectura no ha cambiado.|Verifique a conexão e tente carregar esta página novamente. Sua posição de leitura não mudou.|Vérifiez votre connexion et réessayez cette page. Votre position de lecture est inchangée.|कनेक्शन जाँचें और यह पृष्ठ फिर लोड करें। आपकी पढ़ने की जगह नहीं बदली है।|Verbindung prüfen und diese Seite erneut laden. Deine Leseposition bleibt unverändert.
This chapter could not be opened. Your current page is unchanged. Check the source and try again.|No se pudo abrir este capítulo. Tu página actual no ha cambiado. Comprueba la fuente e inténtalo de nuevo.|Não foi possível abrir este capítulo. Sua página atual não mudou. Verifique a fonte e tente novamente.|Impossible d’ouvrir ce chapitre. Votre page actuelle est inchangée. Vérifiez la source et réessayez.|यह अध्याय नहीं खुल सका। आपका मौजूदा पृष्ठ नहीं बदला है। स्रोत जाँचें और फिर कोशिश करें।|Dieses Kapitel konnte nicht geöffnet werden. Deine aktuelle Seite bleibt unverändert. Quelle prüfen und erneut versuchen.
Manga page {page}|Página de manga {page}|Página de mangá {page}|Page de manga {page}|मंगा पृष्ठ {page}|Manga-Seite {page}
Back to Manga|Volver a Manga|Voltar para Mangá|Retour aux mangas|मंगा पर वापस जाएँ|Zurück zu Manga
Reader settings|Ajustes del lector|Configurações do leitor|Paramètres du lecteur|रीडर की सेटिंग|Leseeinstellungen
Page {value1} of {value2}|Página {value1} de {value2}|Página {value1} de {value2}|Page {value1} sur {value2}|पृष्ठ {value1} / {value2}|Seite {value1} von {value2}
Page {value1}|Página {value1}|Página {value1}|Page {value1}|पृष्ठ {value1}|Seite {value1}
This manga page could not be loaded. Try again.|No se pudo cargar esta página de manga. Inténtalo de nuevo.|Não foi possível carregar esta página de mangá. Tente novamente.|Impossible de charger cette page de manga. Réessayez.|यह मंगा पृष्ठ लोड नहीं हो सका। फिर कोशिश करें।|Diese Manga-Seite konnte nicht geladen werden. Erneut versuchen.
This page could not be decoded safely.|No se pudo decodificar esta página de forma segura.|Não foi possível decodificar esta página com segurança.|Impossible de décoder cette page en toute sécurité.|यह पृष्ठ सुरक्षित रूप से डिकोड नहीं हो सका।|Diese Seite konnte nicht sicher dekodiert werden.
This page could not be decoded.|No se pudo decodificar esta página.|Não foi possível decodificar esta página.|Impossible de décoder cette page.|यह पृष्ठ डिकोड नहीं हो सका।|Diese Seite konnte nicht dekodiert werden.
This downloaded page is unavailable.|Esta página descargada no está disponible.|Esta página baixada está indisponível.|Cette page téléchargée est indisponible.|यह डाउनलोड किया गया पृष्ठ उपलब्ध नहीं है।|Diese heruntergeladene Seite ist nicht verfügbar.
This downloaded page failed its safety check.|Esta página descargada no superó la comprobación de seguridad.|Esta página baixada não passou na verificação de segurança.|Cette page téléchargée a échoué au contrôle de sécurité.|यह डाउनलोड किया गया पृष्ठ सुरक्षा जाँच में विफल रहा।|Die Sicherheitsprüfung dieser heruntergeladenen Seite ist fehlgeschlagen.
This page could not be loaded.|No se pudo cargar esta página.|Não foi possível carregar esta página.|Impossible de charger cette page.|यह पृष्ठ लोड नहीं हो सका।|Diese Seite konnte nicht geladen werden.
The manga page loader is closed.|El cargador de páginas de manga está cerrado.|O carregador de páginas de mangá está fechado.|Le chargeur de pages de manga est fermé.|मंगा पृष्ठ लोडर बंद है।|Der Manga-Seitenlader ist geschlossen.
Too many manga pages are already loading. Try again shortly.|Ya se están cargando demasiadas páginas de manga. Inténtalo en un momento.|Muitas páginas de mangá já estão sendo carregadas. Tente novamente em breve.|Trop de pages de manga sont déjà en cours de chargement. Réessayez dans un instant.|अभी बहुत सारे मंगा पृष्ठ लोड हो रहे हैं। थोड़ी देर में फिर कोशिश करें।|Es werden bereits zu viele Manga-Seiten geladen. Gleich erneut versuchen.
The manga page took too long to load.|La página de manga tardó demasiado en cargar.|A página de mangá demorou muito para carregar.|Le chargement de la page de manga a pris trop de temps.|मंगा पृष्ठ लोड होने में बहुत समय लगा।|Das Laden der Manga-Seite hat zu lange gedauert.
The manga page loader was interrupted.|Se interrumpió el cargador de páginas de manga.|O carregador de páginas de mangá foi interrompido.|Le chargement des pages de manga a été interrompu.|मंगा पृष्ठ लोडर बाधित हो गया।|Der Manga-Seitenlader wurde unterbrochen.
The manga page host could not be reached. Check the connection and try again.|No se pudo contactar con el servidor de la página de manga. Comprueba la conexión e inténtalo de nuevo.|Não foi possível acessar o servidor da página de mangá. Verifique a conexão e tente novamente.|Impossible de joindre le serveur de la page de manga. Vérifiez la connexion et réessayez.|मंगा पृष्ठ के सर्वर से संपर्क नहीं हो सका। कनेक्शन जाँचें और फिर कोशिश करें।|Der Server der Manga-Seite ist nicht erreichbar. Verbindung prüfen und erneut versuchen.
The manga page could not be loaded.|No se pudo cargar la página de manga.|Não foi possível carregar a página de mangá.|Impossible de charger la page de manga.|मंगा पृष्ठ लोड नहीं हो सका।|Die Manga-Seite konnte nicht geladen werden.
The manga page redirected too many times.|La página de manga redirigió demasiadas veces.|A página de mangá redirecionou muitas vezes.|La page de manga a effectué trop de redirections.|मंगा पृष्ठ ने बहुत बार रीडायरेक्ट किया।|Die Manga-Seite wurde zu oft umgeleitet.
The manga page returned an invalid redirect.|La página de manga devolvió una redirección no válida.|A página de mangá retornou um redirecionamento inválido.|La page de manga a renvoyé une redirection invalide.|मंगा पृष्ठ ने अमान्य रीडायरेक्ट दिया।|Die Manga-Seite hat eine ungültige Umleitung zurückgegeben.
This manga page is larger than the safe limit.|Esta página de manga supera el límite de tamaño seguro.|Esta página de mangá excede o limite seguro de tamanho.|Cette page de manga dépasse la limite de taille sûre.|यह मंगा पृष्ठ सुरक्षित आकार सीमा से बड़ा है।|Diese Manga-Seite überschreitet die sichere Größenbegrenzung.
The manga page was empty.|La página de manga estaba vacía.|A página de mangá estava vazia.|La page de manga était vide.|मंगा पृष्ठ खाली था।|Die Manga-Seite war leer.
The manga source rejected its access credential.|La fuente de manga rechazó la credencial de acceso.|A fonte de mangá rejeitou a credencial de acesso.|La source de manga a rejeté l’identifiant d’accès.|मंगा स्रोत ने पहुँच क्रेडेंशियल अस्वीकार कर दिया।|Die Manga-Quelle hat die Zugangsdaten abgelehnt.
The manga source refused this page request.|La fuente de manga rechazó esta solicitud de página.|A fonte de mangá recusou esta solicitação de página.|La source de manga a refusé cette demande de page.|मंगा स्रोत ने इस पृष्ठ का अनुरोध अस्वीकार कर दिया।|Die Manga-Quelle hat diese Seitenanfrage abgelehnt.
This manga page is no longer available from the source.|Esta página de manga ya no está disponible en la fuente.|Esta página de mangá não está mais disponível na fonte.|Cette page de manga n’est plus disponible auprès de la source.|यह मंगा पृष्ठ अब स्रोत पर उपलब्ध नहीं है।|Diese Manga-Seite ist bei der Quelle nicht mehr verfügbar.
The manga source is temporarily limiting requests. Try again shortly.|La fuente de manga está limitando temporalmente las solicitudes. Inténtalo en un momento.|A fonte de mangá está limitando as solicitações temporariamente. Tente novamente em breve.|La source de manga limite temporairement les requêtes. Réessayez dans un instant.|मंगा स्रोत अभी अनुरोधों को सीमित कर रहा है। थोड़ी देर में फिर कोशिश करें।|Die Manga-Quelle begrenzt vorübergehend die Anfragen. Gleich erneut versuchen.
The manga source is temporarily unavailable. Try again shortly.|La fuente de manga no está disponible temporalmente. Inténtalo en un momento.|A fonte de mangá está temporariamente indisponível. Tente novamente em breve.|La source de manga est temporairement indisponible. Réessayez dans un instant.|मंगा स्रोत अभी उपलब्ध नहीं है। थोड़ी देर में फिर कोशिश करें।|Die Manga-Quelle ist vorübergehend nicht verfügbar. Gleich erneut versuchen.
This manga page could not be loaded.|No se pudo cargar esta página de manga.|Não foi possível carregar esta página de mangá.|Impossible de charger cette page de manga.|यह मंगा पृष्ठ लोड नहीं हो सका।|Diese Manga-Seite konnte nicht geladen werden.
Profile changed. Close and reopen this manga.|El perfil ha cambiado. Cierra y vuelve a abrir este manga.|O perfil mudou. Feche e reabra este mangá.|Le profil a changé. Fermez et rouvrez ce manga.|प्रोफ़ाइल बदल गई है। इस मंगा को बंद करके दोबारा खोलें।|Das Profil wurde gewechselt. Diesen Manga schließen und erneut öffnen.
Your library could not be updated. Try again.|No se pudo actualizar tu biblioteca. Inténtalo de nuevo.|Não foi possível atualizar sua biblioteca. Tente novamente.|Impossible de mettre à jour votre bibliothèque. Réessayez.|आपकी लाइब्रेरी अपडेट नहीं हो सकी। फिर कोशिश करें।|Deine Bibliothek konnte nicht aktualisiert werden. Erneut versuchen.
This chapter could not be opened. Check the source and try again.|No se pudo abrir este capítulo. Comprueba la fuente e inténtalo de nuevo.|Não foi possível abrir este capítulo. Verifique a fonte e tente novamente.|Impossible d’ouvrir ce chapitre. Vérifiez la source et réessayez.|यह अध्याय नहीं खुल सका। स्रोत जाँचें और फिर कोशिश करें।|Dieses Kapitel konnte nicht geöffnet werden. Quelle prüfen und erneut versuchen.
Downloads could not be queued. Check the source and try again.|No se pudieron poner las descargas en cola. Comprueba la fuente e inténtalo de nuevo.|Não foi possível adicionar os downloads à fila. Verifique a fonte e tente novamente.|Impossible d’ajouter les téléchargements à la file. Vérifiez la source et réessayez.|डाउनलोड कतार में नहीं जोड़े जा सके। स्रोत जाँचें और फिर कोशिश करें।|Downloads konnten nicht eingereiht werden. Quelle prüfen und erneut versuchen.
Chapter status could not be saved. Try again.|No se pudo guardar el estado del capítulo. Inténtalo de nuevo.|Não foi possível salvar o status do capítulo. Tente novamente.|Impossible d’enregistrer l’état du chapitre. Réessayez.|अध्याय की स्थिति सहेजी नहीं जा सकी। फिर कोशिश करें।|Der Kapitelstatus konnte nicht gespeichert werden. Erneut versuchen.
Chapters|Capítulos|Capítulos|Chapitres|अध्याय|Kapitel
Continue reading|Seguir leyendo|Continuar lendo|Continuer la lecture|पढ़ना जारी रखें|Weiterlesen
Reading status could not be loaded. Retry before using progress filters or batch downloads.|No se pudo cargar el estado de lectura. Reintenta antes de usar filtros de progreso o descargas por lotes.|Não foi possível carregar o status de leitura. Tente novamente antes de usar filtros de progresso ou downloads em lote.|Impossible de charger l’état de lecture. Réessayez avant d’utiliser les filtres de progression ou les téléchargements groupés.|पढ़ने की स्थिति लोड नहीं हो सकी। प्रगति फ़िल्टर या एक साथ कई डाउनलोड का उपयोग करने से पहले फिर कोशिश करें।|Der Lesestatus konnte nicht geladen werden. Vor Fortschrittsfiltern oder Sammeldownloads erneut versuchen.
Descending|Descendente|Decrescente|Décroissant|घटता क्रम|Absteigend
Ascending|Ascendente|Crescente|Croissant|बढ़ता क्रम|Aufsteigend
Unread only|Solo no leídos|Apenas não lidos|Non lus uniquement|सिर्फ़ अपठित|Nur ungelesene
Bookmarks only|Solo marcadores|Apenas favoritos|Favoris uniquement|सिर्फ़ बुकमार्क|Nur Lesezeichen
Download next 5 unread|Descargar los próximos 5 no leídos|Baixar os próximos 5 não lidos|Télécharger les 5 prochains non lus|अगले 5 अपठित अध्याय डाउनलोड करें|Nächste 5 ungelesene herunterladen
Download next 10 unread|Descargar los próximos 10 no leídos|Baixar os próximos 10 não lidos|Télécharger les 10 prochains non lus|अगले 10 अपठित अध्याय डाउनलोड करें|Nächste 10 ungelesene herunterladen
{count} chapters|{count} capítulos|{count} capítulos|{count} chapitres|{count} अध्याय|{count} Kapitel
All chapters read|Todos los capítulos leídos|Todos os capítulos lidos|Tous les chapitres sont lus|सभी अध्याय पढ़ लिए गए|Alle Kapitel gelesen
No chapters match these filters.|Ningún capítulo coincide con estos filtros.|Nenhum capítulo corresponde a esses filtros.|Aucun chapitre ne correspond à ces filtres.|इन फ़िल्टर से कोई अध्याय मेल नहीं खाता।|Keine Kapitel entsprechen diesen Filtern.
Read|Leer|Ler|Lire|पढ़ें|Lesen
Already read|Ya leído|Já lido|Déjà lu|पढ़ा हुआ|Bereits gelesen
Unread|No leído|Não lido|Non lu|अपठित|Ungelesen
Bookmarked|Marcado|Marcado como favorito|Ajouté aux favoris|बुकमार्क किया गया|Mit Lesezeichen
Page {page} of {total}|Página {page} de {total}|Página {page} de {total}|Page {page} sur {total}|पृष्ठ {page} / {total}|Seite {page} von {total}
Mark unread|Marcar como no leído|Marcar como não lido|Marquer comme non lu|अपठित चिह्नित करें|Als ungelesen markieren
Mark read|Marcar como leído|Marcar como lido|Marquer comme lu|पढ़ा हुआ चिह्नित करें|Als gelesen markieren
Remove bookmark|Quitar marcador|Remover favorito|Retirer des favoris|बुकमार्क हटाएँ|Lesezeichen entfernen
Bookmark|Añadir marcador|Adicionar favorito|Ajouter aux favoris|बुकमार्क करें|Lesezeichen setzen
Close|Cerrar|Fechar|Fermer|बंद करें|Schließen
Updating…|Actualizando…|Atualizando…|Mise à jour…|अपडेट हो रहा है…|Aktualisierung…
Remove from library|Quitar de la biblioteca|Remover da biblioteca|Retirer de la bibliothèque|लाइब्रेरी से हटाएँ|Aus Bibliothek entfernen
Add to library|Añadir a la biblioteca|Adicionar à biblioteca|Ajouter à la bibliothèque|लाइब्रेरी में जोड़ें|Zur Bibliothek hinzufügen
This manga source could not load its chapters.|Esta fuente de manga no pudo cargar sus capítulos.|Esta fonte de mangá não conseguiu carregar seus capítulos.|Cette source de manga n’a pas pu charger ses chapitres.|यह मंगा स्रोत अपने अध्याय लोड नहीं कर सका।|Diese Manga-Quelle konnte ihre Kapitel nicht laden.
No chapters found|No se encontraron capítulos|Nenhum capítulo encontrado|Aucun chapitre trouvé|कोई अध्याय नहीं मिला|Keine Kapitel gefunden
Retry|Reintentar|Tentar novamente|Réessayer|फिर कोशिश करें|Erneut versuchen
Download|Descargar|Baixar|Télécharger|डाउनलोड करें|Herunterladen
''';
