import 'catalog.dart';

// App-authored tracking and download-recovery messages only. Provider names,
// manga titles, tracker IDs/URLs, formats and account values remain unchanged.
final mangaTrackingTranslations = catalogFromRows(
  _mangaTrackingRows.trim().split('\n').map((row) => row.split('|')).toList(),
);

const _mangaTrackingRows = r'''
Manga tracking|Seguimiento de manga|Acompanhamento de mangá|Suivi des mangas|मंगा प्रगति ट्रैकिंग|Manga-Tracking
Choose the exact manga on AniList or MAL. Nothing syncs until you confirm a match.|Elige el manga exacto en AniList o MAL. No se sincroniza nada hasta que confirmes la coincidencia.|Escolha o mangá exato no AniList ou MAL. Nada será sincronizado até você confirmar a correspondência.|Choisissez le manga exact sur AniList ou MAL. Rien ne sera synchronisé avant votre confirmation.|AniList या MAL पर सही मंगा चुनें। मिलान की पुष्टि करने तक कुछ भी सिंक नहीं होगा।|Wähle den passenden Manga auf AniList oder MAL. Erst nach deiner Bestätigung wird synchronisiert.
Linked manga|Manga vinculado|Mangá vinculado|Manga associé|लिंक किया गया मंगा|Verknüpfter Manga
Tracker account {value1}|Cuenta del servicio de seguimiento {value1}|Conta de acompanhamento {value1}|Compte de suivi {value1}|ट्रैकिंग खाता {value1}|Tracking-Konto {value1}
Chapter {count} waiting to sync.|Capítulo {count} pendiente de sincronización.|Capítulo {count} aguardando sincronização.|Chapitre {count} en attente de synchronisation.|अध्याय {count} सिंक होने की प्रतीक्षा में है।|Kapitel {count} wartet auf Synchronisierung.
Needs attention|Requiere atención|Precisa de atenção|Intervention requise|ध्यान देने की ज़रूरत है|Aktion erforderlich
Retry scheduled|Reintento programado|Nova tentativa agendada|Nouvelle tentative prévue|दोबारा कोशिश तय है|Neuer Versuch geplant
Unlink manga|Desvincular manga|Desvincular mangá|Dissocier le manga|मंगा अनलिंक करें|Manga-Verknüpfung lösen
Retry pending updates|Reintentar actualizaciones pendientes|Tentar atualizações pendentes novamente|Réessayer les mises à jour en attente|लंबित अपडेट फिर आज़माएँ|Ausstehende Updates erneut versuchen
Not linked to this tracker.|No está vinculado a este servicio de seguimiento.|Não vinculado a este serviço de acompanhamento.|Non associé à ce service de suivi.|इस ट्रैकिंग सेवा से लिंक नहीं है।|Nicht mit diesem Tracking-Dienst verknüpft.
Search manga title|Buscar título del manga|Buscar título do mangá|Rechercher un titre de manga|मंगा का नाम खोजें|Manga-Titel suchen
Search catalog|Buscar en el catálogo|Buscar no catálogo|Rechercher dans le catalogue|कैटलॉग में खोजें|Katalog durchsuchen
No manga found. Try another title.|No se encontró ningún manga. Prueba con otro título.|Nenhum mangá encontrado. Tente outro título.|Aucun manga trouvé. Essayez un autre titre.|कोई मंगा नहीं मिला। कोई दूसरा नाम आज़माएँ।|Kein Manga gefunden. Versuche einen anderen Titel.
Select a result to review|Selecciona un resultado para revisarlo|Selecione um resultado para conferir|Sélectionnez un résultat à vérifier|जाँचने के लिए एक नतीजा चुनें|Ergebnis zur Prüfung auswählen
Confirm manga match|Confirmar coincidencia del manga|Confirmar correspondência do mangá|Confirmer le manga correspondant|मंगा के मिलान की पुष्टि करें|Manga-Zuordnung bestätigen
Confirm this is the same manga and edition before enabling chapter updates.|Confirma que es el mismo manga y la misma edición antes de activar las actualizaciones de capítulos.|Confirme que é o mesmo mangá e a mesma edição antes de ativar as atualizações de capítulos.|Vérifiez qu'il s'agit du même manga et de la même édition avant d'activer le suivi des chapitres.|अध्याय अपडेट चालू करने से पहले पुष्टि करें कि यह वही मंगा और संस्करण है।|Bestätige vor dem Aktivieren der Kapitel-Updates, dass Manga und Ausgabe übereinstimmen.
Confirm and link manga|Confirmar y vincular manga|Confirmar e vincular mangá|Confirmer et associer le manga|पुष्टि करके मंगा लिंक करें|Bestätigen und Manga verknüpfen
Only future completed, whole-number chapters sync. Scores, volumes and list status stay unchanged.|Solo se sincronizan los capítulos con número entero que completes a partir de ahora. Las puntuaciones, los tomos y el estado en la lista no cambian.|Só os capítulos de número inteiro concluídos a partir de agora serão sincronizados. Notas, volumes e status na lista não mudam.|Seuls les chapitres à numéro entier terminés à l'avenir seront synchronisés. Notes, volumes et statut dans la liste restent inchangés.|आगे पूरे किए गए पूर्णांक संख्या वाले अध्याय ही सिंक होंगे। रेटिंग, खंड और सूची की स्थिति नहीं बदलेंगे।|Nur künftig abgeschlossene Kapitel mit ganzzahliger Nummer werden synchronisiert. Bewertungen, Bände und Listenstatus bleiben unverändert.
For specials, gaps, or numbering that restarts by volume, review your chapter count on the tracker.|Si hay especiales, saltos o numeración que se reinicia por tomo, revisa el número de capítulos en el servicio de seguimiento.|Para especiais, lacunas ou numeração que recomeça a cada volume, confira a contagem de capítulos no serviço de acompanhamento.|Pour les chapitres spéciaux, les numéros manquants ou une numérotation par volume, vérifiez le nombre de chapitres sur le service de suivi.|विशेष अध्यायों, छूटी हुई संख्याओं या हर खंड से दोबारा शुरू होने वाली संख्या के लिए ट्रैकिंग सेवा पर अध्यायों की गिनती जाँचें।|Prüfe bei Sonderkapiteln, Lücken oder je Band neu beginnender Nummerierung den Kapitelstand im Tracking-Dienst.
Tracker ID {value1}|ID de seguimiento {value1}|ID no serviço {value1}|Identifiant de suivi {value1}|ट्रैकिंग ID {value1}|Tracking-ID {value1}
Chapter count unknown|Número de capítulos desconocido|Quantidade de capítulos desconhecida|Nombre de chapitres inconnu|अध्यायों की संख्या अज्ञात है|Kapitelanzahl unbekannt
{count} chapters|{count} capítulos|{count} capítulos|{count} chapitres|{count} अध्याय|{count} Kapitel
Manga tracking could not be updated. Try again.|No se pudo actualizar el seguimiento del manga. Inténtalo de nuevo.|Não foi possível atualizar o acompanhamento do mangá. Tente novamente.|Impossible de mettre à jour le suivi du manga. Réessayez.|मंगा ट्रैकिंग अपडेट नहीं हो सकी। फिर कोशिश करें।|Manga-Tracking konnte nicht aktualisiert werden. Versuche es erneut.
Manga linked. Future completed chapters can sync.|Manga vinculado. Los capítulos que completes a partir de ahora podrán sincronizarse.|Mangá vinculado. Os próximos capítulos concluídos poderão ser sincronizados.|Manga associé. Les prochains chapitres terminés pourront être synchronisés.|मंगा लिंक हो गया। आगे पूरे किए गए अध्याय सिंक हो सकेंगे।|Manga verknüpft. Künftig abgeschlossene Kapitel können synchronisiert werden.
Manga unlinked. Your tracker list entry was not removed.|Manga desvinculado. No se eliminó la entrada de tu lista de seguimiento.|Mangá desvinculado. A entrada na sua lista de acompanhamento não foi removida.|Manga dissocié. L'entrée de votre liste de suivi n'a pas été supprimée.|मंगा अनलिंक हो गया। ट्रैकिंग सूची में आपकी प्रविष्टि नहीं हटाई गई।|Manga-Verknüpfung gelöst. Der Eintrag in deiner Tracking-Liste wurde nicht entfernt.
Manga tracking is up to date.|El seguimiento del manga está actualizado.|O acompanhamento do mangá está atualizado.|Le suivi du manga est à jour.|मंगा ट्रैकिंग अद्यतित है।|Manga-Tracking ist aktuell.
Progress remains queued. Check the account or wait for the next retry.|El progreso sigue en cola. Comprueba la cuenta o espera al próximo reintento.|O progresso continua na fila. Verifique a conta ou aguarde a próxima tentativa.|La progression reste en attente. Vérifiez le compte ou attendez la prochaine tentative.|प्रगति अभी कतार में है। खाता जाँचें या अगली कोशिश का इंतज़ार करें।|Der Fortschritt bleibt vorgemerkt. Prüfe das Konto oder warte auf den nächsten Versuch.
Enable Manga before syncing reading progress.|Activa Manga antes de sincronizar el progreso de lectura.|Ative o Manga antes de sincronizar o progresso de leitura.|Activez Manga avant de synchroniser la progression de lecture.|पढ़ने की प्रगति सिंक करने से पहले मंगा चालू करें।|Aktiviere Manga, bevor du den Lesefortschritt synchronisierst.
Enable Manga before using manga tracking.|Activa Manga antes de usar el seguimiento de manga.|Ative o Manga antes de usar o acompanhamento de mangá.|Activez Manga avant d’utiliser le suivi des mangas.|मंगा ट्रैकिंग का उपयोग करने से पहले मंगा चालू करें।|Aktiviere Manga, bevor du Manga-Tracking verwendest.
Choose and confirm the matching manga before enabling tracking.|Elige y confirma el manga correspondiente antes de activar el seguimiento.|Escolha e confirme o mangá correspondente antes de ativar o acompanhamento.|Choisissez et confirmez le manga correspondant avant d'activer le suivi.|ट्रैकिंग चालू करने से पहले सही मंगा चुनकर पुष्टि करें।|Wähle und bestätige den passenden Manga, bevor du Tracking aktivierst.
The tracker returned a different manga. Choose the match again.|El servicio devolvió un manga distinto. Selecciona de nuevo la coincidencia.|O serviço retornou um mangá diferente. Escolha a correspondência novamente.|Le service a renvoyé un autre manga. Sélectionnez à nouveau la correspondance.|ट्रैकिंग सेवा ने अलग मंगा लौटाया। सही मिलान फिर चुनें।|Der Tracking-Dienst hat einen anderen Manga geliefert. Wähle die Zuordnung erneut.
Select the tracking account originally linked to this manga.|Selecciona la cuenta de seguimiento vinculada originalmente a este manga.|Selecione a conta de acompanhamento originalmente vinculada a este mangá.|Sélectionnez le compte de suivi associé à l'origine à ce manga.|इस मंगा से मूल रूप से लिंक किया गया ट्रैकिंग खाता चुनें।|Wähle das ursprünglich mit diesem Manga verknüpfte Tracking-Konto.
The chapter count exceeds the linked manga. Check the selected record.|El número de capítulos supera el del manga vinculado. Comprueba la ficha seleccionada.|A contagem de capítulos excede a do mangá vinculado. Verifique o registro selecionado.|Le nombre de chapitres dépasse celui du manga associé. Vérifiez la fiche sélectionnée.|अध्यायों की गिनती लिंक किए गए मंगा से अधिक है। चुनी हुई प्रविष्टि जाँचें।|Der Kapitelstand überschreitet die Kapitelzahl des verknüpften Mangas. Prüfe den ausgewählten Eintrag.
Manga tracking is temporarily unavailable. Progress is saved for retry.|El seguimiento del manga no está disponible temporalmente. El progreso se guardó para reintentarlo.|O acompanhamento de mangá está temporariamente indisponível. O progresso foi salvo para uma nova tentativa.|Le suivi des mangas est temporairement indisponible. La progression est enregistrée pour une nouvelle tentative.|मंगा ट्रैकिंग अभी उपलब्ध नहीं है। दोबारा कोशिश के लिए प्रगति सहेज ली गई है।|Manga-Tracking ist vorübergehend nicht verfügbar. Der Fortschritt ist für einen neuen Versuch gespeichert.
Manga tracking supports AniList and MAL only.|El seguimiento de manga solo admite AniList y MAL.|O acompanhamento de mangá é compatível apenas com AniList e MAL.|Le suivi des mangas est disponible uniquement avec AniList et MAL.|मंगा ट्रैकिंग केवल AniList और MAL का समर्थन करती है।|Manga-Tracking unterstützt nur AniList und MAL.
Reconnect the linked manga tracking account in Settings.|Vuelve a conectar la cuenta de seguimiento del manga en Ajustes.|Reconecte a conta de acompanhamento de mangá nas Configurações.|Reconnectez le compte de suivi associé dans les paramètres.|सेटिंग में लिंक किया गया मंगा ट्रैकिंग खाता फिर जोड़ें।|Verbinde das verknüpfte Manga-Tracking-Konto in den Einstellungen erneut.
The active profile changed. Open manga tracking again.|El perfil activo cambió. Abre de nuevo el seguimiento del manga.|O perfil ativo mudou. Abra o acompanhamento de mangá novamente.|Le profil actif a changé. Rouvrez le suivi des mangas.|सक्रिय प्रोफ़ाइल बदल गई। मंगा ट्रैकिंग फिर खोलें।|Das aktive Profil hat sich geändert. Öffne Manga-Tracking erneut.
The tracking account changed. Retry with the linked account.|La cuenta de seguimiento cambió. Reinténtalo con la cuenta vinculada.|A conta de acompanhamento mudou. Tente novamente com a conta vinculada.|Le compte de suivi a changé. Réessayez avec le compte associé.|ट्रैकिंग खाता बदल गया। लिंक किए गए खाते से फिर कोशिश करें।|Das Tracking-Konto hat sich geändert. Versuche es mit dem verknüpften Konto erneut.
Saved manga tracking could not be read. No tracker changes were sent.|No se pudo leer el seguimiento guardado. No se envió ningún cambio al servicio.|Não foi possível ler o acompanhamento salvo. Nenhuma alteração foi enviada ao serviço.|Impossible de lire le suivi enregistré. Aucune modification n'a été envoyée au service.|सहेजी गई मंगा ट्रैकिंग पढ़ी नहीं जा सकी। ट्रैकिंग सेवा को कोई बदलाव नहीं भेजा गया।|Gespeichertes Manga-Tracking konnte nicht gelesen werden. Es wurden keine Änderungen gesendet.
The manga tracking queue is full. Retry pending updates or unlink unused titles.|La cola de seguimiento está llena. Reintenta las actualizaciones pendientes o desvincula títulos que no uses.|A fila de acompanhamento está cheia. Tente as atualizações pendentes novamente ou desvincule títulos sem uso.|La file de suivi est pleine. Réessayez les mises à jour en attente ou dissociez les titres inutilisés.|मंगा ट्रैकिंग कतार भर गई है। लंबित अपडेट फिर आज़माएँ या अनुपयोगी शीर्षक अनलिंक करें।|Die Manga-Tracking-Warteschlange ist voll. Wiederhole ausstehende Updates oder löse ungenutzte Titelverknüpfungen.
Manga tracking could not be saved securely. Free device storage and try again.|No se pudo guardar el seguimiento de forma segura. Libera espacio en el dispositivo e inténtalo de nuevo.|Não foi possível salvar o acompanhamento com segurança. Libere espaço no dispositivo e tente novamente.|Impossible d'enregistrer le suivi de manière sécurisée. Libérez de l'espace sur l'appareil et réessayez.|मंगा ट्रैकिंग सुरक्षित रूप से सहेजी नहीं जा सकी। डिवाइस में जगह खाली करके फिर कोशिश करें।|Manga-Tracking konnte nicht sicher gespeichert werden. Schaffe Speicherplatz auf dem Gerät und versuche es erneut.
Connect AniList or MAL to track manga.|Conecta AniList o MAL para seguir manga.|Conecte AniList ou MAL para acompanhar mangás.|Connectez AniList ou MAL pour suivre les mangas.|मंगा ट्रैक करने के लिए AniList या MAL जोड़ें।|Verbinde AniList oder MAL, um Manga-Fortschritt zu verfolgen.
Enter at least two characters to search manga.|Introduce al menos dos caracteres para buscar manga.|Digite pelo menos dois caracteres para buscar mangás.|Saisissez au moins deux caractères pour rechercher un manga.|मंगा खोजने के लिए कम से कम दो अक्षर दर्ज करें।|Gib mindestens zwei Zeichen ein, um nach Manga zu suchen.
Manga tracking is rate limited. It will retry later.|Se alcanzó el límite de solicitudes de seguimiento. Se reintentará más tarde.|O limite de solicitações de acompanhamento foi atingido. Uma nova tentativa será feita depois.|La limite de requêtes de suivi est atteinte. Une nouvelle tentative aura lieu plus tard.|मंगा ट्रैकिंग की अनुरोध सीमा पूरी हो गई है। बाद में फिर कोशिश होगी।|Das Anfragelimit für Manga-Tracking ist erreicht. Ein neuer Versuch erfolgt später.
The manga tracker rejected this request. Check the linked record.|El servicio de seguimiento rechazó la solicitud. Comprueba la ficha vinculada.|O serviço de acompanhamento rejeitou a solicitação. Verifique o registro vinculado.|Le service de suivi a refusé cette requête. Vérifiez la fiche associée.|मंगा ट्रैकिंग सेवा ने यह अनुरोध अस्वीकार किया। लिंक की गई प्रविष्टि जाँचें।|Der Manga-Tracking-Dienst hat die Anfrage abgelehnt. Prüfe den verknüpften Eintrag.
The manga tracker returned an invalid response.|El servicio de seguimiento devolvió una respuesta no válida.|O serviço de acompanhamento retornou uma resposta inválida.|Le service de suivi a renvoyé une réponse non valide.|मंगा ट्रैकिंग सेवा ने अमान्य उत्तर दिया।|Der Manga-Tracking-Dienst hat eine ungültige Antwort geliefert.
The manga download queue is full. Wait for downloads to finish.|La cola de descargas de manga está llena. Espera a que terminen las descargas.|A fila de downloads de mangá está cheia. Aguarde os downloads terminarem.|La file de téléchargement des mangas est pleine. Attendez la fin des téléchargements.|मंगा डाउनलोड कतार भर गई है। डाउनलोड पूरे होने का इंतज़ार करें।|Die Manga-Download-Warteschlange ist voll. Warte, bis Downloads abgeschlossen sind.
Reconnect to the manga source before resuming this download.|Vuelve a conectar la fuente de manga antes de reanudar esta descarga.|Reconecte a fonte de mangá antes de retomar este download.|Reconnectez la source de mangas avant de reprendre ce téléchargement.|यह डाउनलोड फिर शुरू करने से पहले मंगा स्रोत फिर जोड़ें।|Verbinde die Manga-Quelle erneut, bevor du diesen Download fortsetzt.
This manga source is unavailable. Reconnect to it and try again.|Esta fuente de manga no está disponible. Vuelve a conectarla e inténtalo de nuevo.|Esta fonte de mangá está indisponível. Reconecte-a e tente novamente.|Cette source de mangas est indisponible. Reconnectez-la et réessayez.|यह मंगा स्रोत उपलब्ध नहीं है। इसे फिर जोड़कर कोशिश करें।|Diese Manga-Quelle ist nicht verfügbar. Verbinde sie erneut und versuche es noch einmal.
Reconnect to the manga source to retry this download.|Vuelve a conectar la fuente de manga para reintentar esta descarga.|Reconecte a fonte de mangá para tentar este download novamente.|Reconnectez la source de mangas pour réessayer ce téléchargement.|यह डाउनलोड फिर आज़माने के लिए मंगा स्रोत फिर जोड़ें।|Verbinde die Manga-Quelle erneut, um diesen Download zu wiederholen.
Manga pages could not be saved. Free device storage and resume the download.|No se pudieron guardar las páginas del manga. Libera espacio en el dispositivo y reanuda la descarga.|Não foi possível salvar as páginas do mangá. Libere espaço no dispositivo e retome o download.|Impossible d'enregistrer les pages du manga. Libérez de l'espace sur l'appareil et reprenez le téléchargement.|मंगा पृष्ठ सहेजे नहीं जा सके। डिवाइस में जगह खाली करके डाउनलोड फिर शुरू करें।|Manga-Seiten konnten nicht gespeichert werden. Schaffe Speicherplatz auf dem Gerät und setze den Download fort.
The manga download is paused. Resume it when you are ready.|La descarga del manga está en pausa. Reanúdala cuando quieras.|O download do mangá está pausado. Retome quando quiser.|Le téléchargement du manga est en pause. Reprenez-le lorsque vous le souhaitez.|मंगा डाउनलोड रुका हुआ है। तैयार होने पर इसे फिर शुरू करें।|Der Manga-Download ist pausiert. Setze ihn fort, wenn du bereit bist.
Manga download storage is full. Delete downloaded chapters and try again.|El almacenamiento de descargas de manga está lleno. Elimina capítulos descargados e inténtalo de nuevo.|O armazenamento de downloads de mangá está cheio. Exclua capítulos baixados e tente novamente.|L'espace de téléchargement des mangas est plein. Supprimez des chapitres téléchargés et réessayez.|मंगा डाउनलोड का संग्रहण भर गया है। डाउनलोड किए गए अध्याय हटाकर फिर कोशिश करें।|Der Manga-Download-Speicher ist voll. Lösche heruntergeladene Kapitel und versuche es erneut.
''';
