import 'catalog.dart';

// App-authored backup and migration copy only. User titles, source labels,
// encrypted contents, passphrases and raw validation errors are never keys.
final mangaBackupTranslations = catalogFromRows(
  _mangaBackupRows.trim().split('\n').map((row) => row.split('|')).toList(),
);

const _mangaBackupRows = r'''
Manga backup|Copia de seguridad de manga|Backup de mangá|Sauvegarde des mangas|मंगा बैकअप|Manga-Sicherung
Encrypted library, chapter progress, bookmarks, and reader settings. No account credentials or downloaded pages.|Biblioteca, progreso de capítulos, marcadores y ajustes del lector cifrados. Sin credenciales de cuentas ni páginas descargadas.|Biblioteca, progresso dos capítulos, marcadores e configurações do leitor criptografados. Sem credenciais de contas nem páginas baixadas.|Bibliothèque, progression des chapitres, marque-pages et réglages du lecteur chiffrés. Aucun identifiant de compte ni page téléchargée.|लाइब्रेरी, अध्याय की प्रगति, बुकमार्क और रीडर सेटिंग्स एन्क्रिप्ट की जाती हैं। खाते के क्रेडेंशियल या डाउनलोड किए गए पेज शामिल नहीं हैं।|Verschlüsselte Bibliothek, Kapitelfortschritt, Lesezeichen und Leseeinstellungen. Keine Kontozugangsdaten oder heruntergeladenen Seiten.
Export backup|Exportar copia de seguridad|Exportar backup|Exporter une sauvegarde|बैकअप निर्यात करें|Sicherung exportieren
Import backup|Importar copia de seguridad|Importar backup|Importer une sauvegarde|बैकअप आयात करें|Sicherung importieren
Choose encrypted backup|Elegir copia cifrada|Escolher backup criptografado|Choisir une sauvegarde chiffrée|एन्क्रिप्ट किया गया बैकअप चुनें|Verschlüsselte Sicherung wählen
Choose another backup|Elegir otra copia|Escolher outro backup|Choisir une autre sauvegarde|दूसरा बैकअप चुनें|Andere Sicherung wählen
Backup passphrase|Frase de contraseña de la copia|Frase secreta do backup|Phrase secrète de la sauvegarde|बैकअप पासफ़्रेज़|Sicherungspassphrase
Confirm passphrase|Confirmar frase de contraseña|Confirmar frase secreta|Confirmer la phrase secrète|पासफ़्रेज़ की पुष्टि करें|Passphrase bestätigen
At least 12 characters. This passphrase cannot be recovered.|Al menos 12 caracteres. Esta frase no se puede recuperar.|Pelo menos 12 caracteres. Esta frase secreta não pode ser recuperada.|Au moins 12 caractères. Cette phrase secrète ne peut pas être récupérée.|कम से कम 12 अक्षर। यह पासफ़्रेज़ पुनर्प्राप्त नहीं किया जा सकता।|Mindestens 12 Zeichen. Diese Passphrase kann nicht wiederhergestellt werden.
Use a passphrase of at least 12 characters.|Usa una frase de contraseña de al menos 12 caracteres.|Use uma frase secreta com pelo menos 12 caracteres.|Utilisez une phrase secrète d’au moins 12 caractères.|कम से कम 12 अक्षरों का पासफ़्रेज़ उपयोग करें।|Verwenden Sie eine Passphrase mit mindestens 12 Zeichen.
The passphrases do not match.|Las frases de contraseña no coinciden.|As frases secretas não coincidem.|Les phrases secrètes ne correspondent pas.|पासफ़्रेज़ मेल नहीं खाते।|Die Passphrasen stimmen nicht überein.
Encrypted backup selected. Enter its passphrase to preview.|Copia cifrada seleccionada. Introduce su frase de contraseña para revisarla.|Backup criptografado selecionado. Digite a frase secreta para visualizar.|Sauvegarde chiffrée sélectionnée. Saisissez sa phrase secrète pour l’examiner.|एन्क्रिप्ट किया गया बैकअप चुना गया। पूर्वावलोकन के लिए उसका पासफ़्रेज़ दर्ज करें।|Verschlüsselte Sicherung ausgewählt. Passphrase für die Vorschau eingeben.
Save encrypted backup|Guardar copia cifrada|Salvar backup criptografado|Enregistrer la sauvegarde chiffrée|एन्क्रिप्ट किया गया बैकअप सहेजें|Verschlüsselte Sicherung speichern
Encrypted backup saved. Keep its passphrase somewhere safe.|Copia cifrada guardada. Conserva su frase de contraseña en un lugar seguro.|Backup criptografado salvo. Guarde a frase secreta em um local seguro.|Sauvegarde chiffrée enregistrée. Conservez sa phrase secrète en lieu sûr.|एन्क्रिप्ट किया गया बैकअप सहेजा गया। उसका पासफ़्रेज़ सुरक्षित जगह रखें।|Verschlüsselte Sicherung gespeichert. Bewahren Sie die Passphrase sicher auf.
Backup export cancelled.|Exportación de la copia cancelada.|Exportação do backup cancelada.|Exportation de la sauvegarde annulée.|बैकअप निर्यात रद्द किया गया।|Sicherungsexport abgebrochen.
Preview import|Revisar importación|Visualizar importação|Aperçu de l’importation|आयात का पूर्वावलोकन|Importvorschau
Review backup import|Revisar importación de la copia|Revisar importação do backup|Vérifier l’importation de la sauvegarde|बैकअप आयात की समीक्षा करें|Sicherungsimport prüfen
Confirm import|Confirmar importación|Confirmar importação|Confirmer l’importation|आयात की पुष्टि करें|Import bestätigen
{newCount} new titles · {conflictCount} existing titles · {settingsCount} reader settings|{newCount} títulos nuevos · {conflictCount} títulos existentes · {settingsCount} ajustes del lector|{newCount} títulos novos · {conflictCount} títulos existentes · {settingsCount} configurações do leitor|{newCount} nouveaux titres · {conflictCount} titres existants · {settingsCount} réglages du lecteur|{newCount} नए शीर्षक · {conflictCount} मौजूदा शीर्षक · {settingsCount} रीडर सेटिंग्स|{newCount} neue Titel · {conflictCount} vorhandene Titel · {settingsCount} Leseeinstellungen
{count} titles need their manga extension enabled or source identity reselected.|{count} títulos necesitan activar su extensión de manga o volver a seleccionar su identidad de origen.|{count} títulos precisam da extensão de mangá ativada ou da identidade da fonte selecionada novamente.|Pour {count} titres, activez l’extension manga ou sélectionnez à nouveau leur identité dans la source.|{count} शीर्षकों के लिए मंगा एक्सटेंशन चालू करना या स्रोत की पहचान फिर चुनना ज़रूरी है।|Für {count} Titel muss die Manga-Erweiterung aktiviert oder die Quellidentität erneut ausgewählt werden.
{count} older non-Seanime titles were not included in this backup.|Esta copia no incluye {count} títulos antiguos ajenos a Seanime.|Este backup não inclui {count} títulos antigos que não são do Seanime.|Cette sauvegarde n’inclut pas {count} anciens titres hors Seanime.|इस बैकअप में {count} पुराने गैर-Seanime शीर्षक शामिल नहीं हैं।|{count} ältere Nicht-Seanime-Titel sind in dieser Sicherung nicht enthalten.
And {count} more titles.|Y {count} títulos más.|E mais {count} títulos.|Et {count} autres titres.|और {count} शीर्षक।|Und {count} weitere Titel.
Existing data|Datos existentes|Dados existentes|Données existantes|मौजूदा डेटा|Vorhandene Daten
Merge newer progress|Combinar el progreso más reciente|Mesclar o progresso mais recente|Fusionner la progression la plus récente|नई प्रगति मिलाएँ|Neueren Fortschritt zusammenführen
Keep existing data and settings|Conservar datos y ajustes existentes|Manter dados e configurações existentes|Conserver les données et réglages existants|मौजूदा डेटा और सेटिंग्स रखें|Vorhandene Daten und Einstellungen behalten
{count} chapter records · {historyCount} from unsaved titles · {conflictCount} existing history records|{count} registros de capítulos · {historyCount} de títulos no guardados · {conflictCount} registros de historial existentes|{count} registros de capítulos · {historyCount} de títulos não salvos · {conflictCount} registros de histórico existentes|{count} états de chapitres · {historyCount} de titres non enregistrés · {conflictCount} états d’historique existants|{count} अध्याय रिकॉर्ड · {historyCount} बिना सहेजे शीर्षकों से · {conflictCount} मौजूदा इतिहास रिकॉर्ड|{count} Kapitelstände · {historyCount} aus nicht gespeicherten Titeln · {conflictCount} vorhandene Verlaufseinträge
Unsaved history reconnects when you open the same title from the same extension. No library titles are added.|El historial no guardado se recupera al abrir el mismo título desde la misma extensión. No se añaden títulos a la biblioteca.|O histórico não salvo é reconectado ao abrir o mesmo título na mesma extensão. Nenhum título é adicionado à biblioteca.|L’historique des titres non enregistrés est retrouvé en ouvrant le même titre avec la même extension. Aucun titre n’est ajouté à la bibliothèque.|उसी एक्सटेंशन से वही शीर्षक खोलने पर बिना सहेजे शीर्षकों का इतिहास फिर जुड़ता है। लाइब्रेरी में कोई शीर्षक नहीं जोड़ा जाता।|Der Verlauf nicht gespeicherter Titel wird beim Öffnen desselben Titels über dieselbe Erweiterung wieder zugeordnet. Es werden keine Bibliothekstitel hinzugefügt.
Merge keeps newer chapter progress and restores backed-up reader settings. Nothing missing from the backup is deleted. Downloads are unchanged.|La combinación conserva el progreso de capítulos más reciente y restaura los ajustes del lector guardados. No elimina nada que falte en la copia. Las descargas no cambian.|A mesclagem mantém o progresso mais recente e restaura as configurações do leitor salvas. Nada ausente no backup é excluído. Os downloads não mudam.|La fusion conserve la progression la plus récente et restaure les réglages sauvegardés. Les éléments absents de la sauvegarde ne sont pas supprimés. Les téléchargements restent inchangés.|मिलाने पर अध्याय की नई प्रगति रखी जाती है और बैकअप की रीडर सेटिंग्स बहाल होती हैं। बैकअप में न होने वाला डेटा नहीं मिटता। डाउनलोड नहीं बदलते।|Die Zusammenführung behält den neueren Kapitelfortschritt und stellt gesicherte Leseeinstellungen wieder her. Fehlende Einträge werden nicht gelöscht. Downloads bleiben unverändert.
Backup files are available on Android devices.|Los archivos de copia de seguridad están disponibles en dispositivos Android.|Arquivos de backup estão disponíveis em dispositivos Android.|Les fichiers de sauvegarde sont disponibles sur les appareils Android.|बैकअप फ़ाइलें Android डिवाइस पर उपलब्ध हैं।|Sicherungsdateien sind auf Android-Geräten verfügbar.
Could not import this backup. Check the passphrase and file, then preview it again.|No se pudo importar esta copia. Comprueba la frase de contraseña y el archivo y vuelve a revisarla.|Não foi possível importar este backup. Verifique a frase secreta e o arquivo e visualize novamente.|Impossible d’importer cette sauvegarde. Vérifiez la phrase secrète et le fichier, puis relancez l’aperçu.|यह बैकअप आयात नहीं हो सका। पासफ़्रेज़ और फ़ाइल जाँचकर फिर पूर्वावलोकन करें।|Diese Sicherung konnte nicht importiert werden. Prüfen Sie Passphrase und Datei und öffnen Sie die Vorschau erneut.
Could not save the encrypted backup. Check the selected storage and try again.|No se pudo guardar la copia cifrada. Comprueba el almacenamiento seleccionado e inténtalo de nuevo.|Não foi possível salvar o backup criptografado. Verifique o armazenamento selecionado e tente novamente.|Impossible d’enregistrer la sauvegarde chiffrée. Vérifiez le stockage sélectionné et réessayez.|एन्क्रिप्ट किया गया बैकअप नहीं सहेजा जा सका। चुना गया स्टोरेज जाँचें और फिर कोशिश करें।|Die verschlüsselte Sicherung konnte nicht gespeichert werden. Prüfen Sie den gewählten Speicher und versuchen Sie es erneut.
Import was rolled back. Reconnect affected sources and check reader settings before trying again.|Se revirtió la importación. Vuelve a conectar los orígenes afectados y revisa los ajustes del lector antes de intentarlo de nuevo.|A importação foi revertida. Reconecte as fontes afetadas e verifique as configurações do leitor antes de tentar novamente.|L’importation a été annulée. Reconnectez les sources concernées et vérifiez les réglages du lecteur avant de réessayer.|आयात वापस लिया गया। फिर कोशिश करने से पहले प्रभावित स्रोत दोबारा जोड़ें और रीडर सेटिंग्स जाँचें।|Der Import wurde zurückgesetzt. Verbinden Sie betroffene Quellen erneut und prüfen Sie die Leseeinstellungen vor einem weiteren Versuch.
The source title is no longer in your library.|El título de origen ya no está en tu biblioteca.|O título da fonte não está mais na sua biblioteca.|Le titre source n’est plus dans votre bibliothèque.|स्रोत का शीर्षक अब आपकी लाइब्रेरी में नहीं है।|Der Quelltitel befindet sich nicht mehr in Ihrer Bibliothek.
Source migration requires explicit confirmation.|La migración de origen requiere confirmación explícita.|A migração de fonte exige confirmação explícita.|La migration de source nécessite une confirmation explicite.|स्रोत बदलने के लिए स्पष्ट पुष्टि ज़रूरी है।|Die Quellenmigration erfordert eine ausdrückliche Bestätigung.
Library data changed. Preview the source migration again.|Los datos de la biblioteca cambiaron. Revisa de nuevo la migración de origen.|Os dados da biblioteca mudaram. Revise a migração de fonte novamente.|Les données de la bibliothèque ont changé. Vérifiez à nouveau la migration de source.|लाइब्रेरी डेटा बदल गया। स्रोत बदलने का फिर पूर्वावलोकन करें।|Bibliotheksdaten wurden geändert. Prüfen Sie die Quellenmigration erneut.
Choose a different title source in the same profile.|Elige otro origen del título en el mismo perfil.|Escolha outra fonte do título no mesmo perfil.|Choisissez une autre source du titre dans le même profil.|इसी प्रोफ़ाइल में शीर्षक का दूसरा स्रोत चुनें।|Wählen Sie im selben Profil eine andere Titelquelle.
The selected profile changed.|El perfil seleccionado cambió.|O perfil selecionado mudou.|Le profil sélectionné a changé.|चुनी गई प्रोफ़ाइल बदल गई।|Das ausgewählte Profil wurde geändert.
Manga data changed. Preview the backup again before importing.|Los datos de manga cambiaron. Revisa la copia de nuevo antes de importarla.|Os dados de mangá mudaram. Visualize o backup novamente antes de importar.|Les données manga ont changé. Vérifiez à nouveau la sauvegarde avant de l’importer.|मंगा डेटा बदल गया। आयात से पहले बैकअप का फिर पूर्वावलोकन करें।|Manga-Daten wurden geändert. Prüfen Sie die Sicherung vor dem Import erneut.
The passphrase is incorrect or the backup is damaged.|La frase de contraseña es incorrecta o la copia está dañada.|A frase secreta está incorreta ou o backup está danificado.|La phrase secrète est incorrecte ou la sauvegarde est endommagée.|पासफ़्रेज़ गलत है या बैकअप खराब है।|Die Passphrase ist falsch oder die Sicherung ist beschädigt.
''';
