import 'catalog.dart';

final mangaLibraryTranslations = catalogFromRows(
  _rows.trim().split('\n').map((row) => row.split('|')).toList(),
);

const _rows = r'''
Plan to read|Por leer|Quero ler|À lire|पढ़ने की योजना|Geplant
Reading|Leyendo|Lendo|En cours de lecture|पढ़ रहे हैं|Wird gelesen
Completed|Completado|Concluído|Terminé|पूरा हुआ|Abgeschlossen
On hold|En pausa|Em pausa|En pause|रुका हुआ|Pausiert
Dropped|Abandonado|Abandonado|Abandonné|छोड़ दिया|Abgebrochen
Chapter updates could not be checked. Try again.|No se pudieron comprobar los capítulos nuevos. Inténtalo de nuevo.|Não foi possível verificar novos capítulos. Tente novamente.|Impossible de vérifier les nouveaux chapitres. Réessayez.|नए अध्यायों की जाँच नहीं हो सकी। फिर कोशिश करें।|Neue Kapitel konnten nicht geprüft werden. Versuche es erneut.
Organize manga|Organizar manga|Organizar mangá|Organiser le manga|मंगा व्यवस्थित करें|Manga organisieren
Category|Categoría|Categoria|Catégorie|श्रेणी|Kategorie
Your library changes could not be saved. Try again.|No se pudieron guardar los cambios de tu biblioteca. Inténtalo de nuevo.|Não foi possível salvar as alterações da biblioteca. Tente novamente.|Impossible d’enregistrer les modifications de la bibliothèque. Réessayez.|लाइब्रेरी के बदलाव सहेजे नहीं जा सके। फिर कोशिश करें।|Bibliotheksänderungen konnten nicht gespeichert werden. Versuche es erneut.
Search library|Buscar en la biblioteca|Buscar na biblioteca|Rechercher dans la bibliothèque|लाइब्रेरी में खोजें|Bibliothek durchsuchen
All categories|Todas las categorías|Todas as categorias|Toutes les catégories|सभी श्रेणियाँ|Alle Kategorien
All statuses|Todos los estados|Todos os status|Tous les statuts|सभी स्थितियाँ|Alle Status
Recently read|Leído recientemente|Lidos recentemente|Lus récemment|हाल ही में पढ़े गए|Zuletzt gelesen
Recently added|Añadido recientemente|Adicionados recentemente|Ajoutés récemment|हाल ही में जोड़े गए|Zuletzt hinzugefügt
New chapters|Capítulos nuevos|Novos capítulos|Nouveaux chapitres|नए अध्याय|Neue Kapitel
Downloaded|Descargado|Baixado|Téléchargé|डाउनलोड किए गए|Heruntergeladen
Checking…|Comprobando…|Verificando…|Vérification…|जाँच हो रही है…|Wird geprüft…
Check chapter updates|Buscar capítulos nuevos|Verificar novos capítulos|Vérifier les nouveaux chapitres|नए अध्याय जाँचें|Neue Kapitel prüfen
Backup & restore|Copia de seguridad y restauración|Backup e restauração|Sauvegarde et restauration|बैकअप और पुनर्स्थापना|Sichern und wiederherstellen
Your manga library is empty|Tu biblioteca de manga está vacía|Sua biblioteca de mangá está vazia|Votre bibliothèque de mangas est vide|आपकी मंगा लाइब्रेरी खाली है|Deine Manga-Bibliothek ist leer
No manga matches these filters|Ningún manga coincide con estos filtros|Nenhum mangá corresponde a estes filtros|Aucun manga ne correspond à ces filtres|इन फ़िल्टर से कोई मंगा नहीं मिला|Kein Manga entspricht diesen Filtern
{count} new chapters|{count} capítulos nuevos|{count} novos capítulos|{count} nouveaux chapitres|{count} नए अध्याय|{count} neue Kapitel
Last read: chapter {chapter}, page {page}|Última lectura: capítulo {chapter}, página {page}|Última leitura: capítulo {chapter}, página {page}|Dernière lecture : chapitre {chapter}, page {page}|पिछली बार पढ़ा: अध्याय {chapter}, पृष्ठ {page}|Zuletzt gelesen: Kapitel {chapter}, Seite {page}
Start reading|Empezar a leer|Começar a ler|Commencer la lecture|पढ़ना शुरू करें|Lesen beginnen
Organize|Organizar|Organizar|Organiser|व्यवस्थित करें|Organisieren
Change source|Cambiar fuente|Trocar fonte|Changer de source|स्रोत बदलें|Quelle wechseln
Remove from library?|¿Quitar de la biblioteca?|Remover da biblioteca?|Retirer de la bibliothèque ?|लाइब्रेरी से हटाएँ?|Aus der Bibliothek entfernen?
Downloaded chapters and reading history will be kept.|Se conservarán los capítulos descargados y el historial de lectura.|Os capítulos baixados e o histórico de leitura serão mantidos.|Les chapitres téléchargés et l’historique de lecture seront conservés.|डाउनलोड किए गए अध्याय और पढ़ने का इतिहास बने रहेंगे।|Heruntergeladene Kapitel und Leseverlauf bleiben erhalten.
Checked {checked} titles • {new} new chapters • {failed} unavailable|{checked} títulos comprobados • {new} capítulos nuevos • {failed} no disponibles|{checked} títulos verificados • {new} novos capítulos • {failed} indisponíveis|{checked} titres vérifiés • {new} nouveaux chapitres • {failed} indisponibles|{checked} शीर्षक जाँचे • {new} नए अध्याय • {failed} अनुपलब्ध|{checked} Titel geprüft • {new} neue Kapitel • {failed} nicht verfügbar
Add this manga from your new Seanime source to the library first, then choose Change source.|Primero añade este manga desde tu nueva fuente Seanime a la biblioteca y luego elige Cambiar fuente.|Primeiro adicione este mangá à biblioteca pela nova fonte Seanime e escolha Trocar fonte.|Ajoutez d’abord ce manga à la bibliothèque depuis votre nouvelle source Seanime, puis choisissez Changer de source.|पहले नए Seanime स्रोत से यह मंगा लाइब्रेरी में जोड़ें, फिर स्रोत बदलें चुनें।|Füge diesen Manga zuerst aus deiner neuen Seanime-Quelle zur Bibliothek hinzu und wähle dann Quelle wechseln.
Choose the new source edition|Elige la edición de la nueva fuente|Escolha a edição da nova fonte|Choisir l’édition de la nouvelle source|नए स्रोत का संस्करण चुनें|Ausgabe der neuen Quelle wählen
Copy reading history?|¿Copiar el historial de lectura?|Copiar histórico de leitura?|Copier l’historique de lecture ?|पढ़ने का इतिहास कॉपी करें?|Leseverlauf kopieren?
Copy {matched} matched chapters to {title} on {source}. {unmatched} chapters could not be matched. Check that these are the same edition and chapter numbering. Your original manga, history and downloads will stay untouched.|Copiar {matched} capítulos coincidentes a {title} en {source}. No se pudieron asociar {unmatched} capítulos. Comprueba que la edición y la numeración coincidan. Tu manga original, historial y descargas no se modificarán.|Copiar {matched} capítulos correspondentes para {title} em {source}. {unmatched} capítulos não foram associados. Confira se a edição e a numeração são iguais. O mangá original, o histórico e os downloads permanecerão intactos.|Copier {matched} chapitres correspondants vers {title} sur {source}. {unmatched} chapitres n’ont pas pu être associés. Vérifiez l’édition et la numérotation. Le manga d’origine, l’historique et les téléchargements resteront intacts.|{matched} मेल खाने वाले अध्याय {source} के {title} में कॉपी करें। {unmatched} अध्यायों का मिलान नहीं हुआ। सुनिश्चित करें कि संस्करण और अध्याय संख्या समान हैं। मूल मंगा, इतिहास और डाउनलोड नहीं बदलेंगे।|{matched} passende Kapitel zu {title} auf {source} kopieren. {unmatched} Kapitel konnten nicht zugeordnet werden. Prüfe, ob Ausgabe und Kapitelnummerierung übereinstimmen. Original, Verlauf und Downloads bleiben unverändert.
Copy history|Copiar historial|Copiar histórico|Copier l’historique|इतिहास कॉपी करें|Verlauf kopieren
Reading history copied. Your original source is still in the library.|Historial copiado. La fuente original sigue en la biblioteca.|Histórico copiado. A fonte original continua na biblioteca.|Historique copié. La source d’origine est toujours dans la bibliothèque.|पढ़ने का इतिहास कॉपी हो गया। मूल स्रोत अभी भी लाइब्रेरी में है।|Leseverlauf kopiert. Die ursprüngliche Quelle bleibt in der Bibliothek.
Source migration could not be completed. Your original library is unchanged.|No se pudo completar el cambio de fuente. Tu biblioteca original no ha cambiado.|Não foi possível concluir a troca de fonte. Sua biblioteca original não foi alterada.|Le changement de source a échoué. Votre bibliothèque d’origine est inchangée.|स्रोत बदलना पूरा नहीं हुआ। मूल लाइब्रेरी में कोई बदलाव नहीं हुआ।|Quellenwechsel fehlgeschlagen. Deine ursprüngliche Bibliothek ist unverändert.
You have read all available chapters.|Has leído todos los capítulos disponibles.|Você leu todos os capítulos disponíveis.|Vous avez lu tous les chapitres disponibles.|आपने सभी उपलब्ध अध्याय पढ़ लिए हैं।|Du hast alle verfügbaren Kapitel gelesen.
This manga could not be resumed. Open Chapters to retry, or read a saved download.|No se pudo reanudar este manga. Abre Capítulos para reintentarlo o lee una descarga guardada.|Não foi possível retomar este mangá. Abra Capítulos para tentar novamente ou leia um download salvo.|Impossible de reprendre ce manga. Ouvrez Chapitres pour réessayer ou lisez un téléchargement.|यह मंगा फिर से नहीं खुल सका। दोबारा कोशिश के लिए अध्याय खोलें या सहेजा डाउनलोड पढ़ें।|Dieser Manga konnte nicht fortgesetzt werden. Öffne Kapitel, um es erneut zu versuchen, oder lies einen gespeicherten Download.
This download could not be paused. Try again.|No se pudo pausar esta descarga. Inténtalo de nuevo.|Não foi possível pausar este download. Tente novamente.|Impossible de suspendre ce téléchargement. Réessayez.|यह डाउनलोड रोका नहीं जा सका। फिर कोशिश करें।|Dieser Download konnte nicht pausiert werden. Versuche es erneut.
Previously saved catalogs|Catálogos guardados anteriormente|Catálogos salvos anteriormente|Catalogues déjà enregistrés|पहले सहेजे गए कैटलॉग|Zuvor gespeicherte Kataloge
Your existing catalogs remain available. Add new sources through Seanime extension repositories.|Tus catálogos actuales siguen disponibles. Añade nuevas fuentes mediante repositorios de extensiones Seanime.|Seus catálogos atuais continuam disponíveis. Adicione novas fontes por repositórios de extensões Seanime.|Vos catalogues restent disponibles. Ajoutez de nouvelles sources via les dépôts d’extensions Seanime.|मौजूदा कैटलॉग उपलब्ध रहेंगे। नए स्रोत Seanime एक्सटेंशन रिपॉज़िटरी से जोड़ें।|Deine vorhandenen Kataloge bleiben verfügbar. Füge neue Quellen über Seanime-Erweiterungs-Repositories hinzu.
This manga belongs to another profile.|Este manga pertenece a otro perfil.|Este mangá pertence a outro perfil.|Ce manga appartient à un autre profil.|यह मंगा दूसरे प्रोफ़ाइल का है।|Dieser Manga gehört zu einem anderen Profil.
Open this download from the profile that saved the manga.|Abre esta descarga desde el perfil que guardó el manga.|Abra este download pelo perfil que salvou o mangá.|Ouvrez ce téléchargement depuis le profil qui a enregistré le manga.|यह डाउनलोड उस प्रोफ़ाइल से खोलें जिसने मंगा सहेजा था।|Öffne diesen Download mit dem Profil, das den Manga gespeichert hat.
Reopen this chapter from its original source to download it.|Vuelve a abrir este capítulo desde su fuente original para descargarlo.|Reabra este capítulo na fonte original para baixá-lo.|Rouvrez ce chapitre depuis sa source d’origine pour le télécharger.|डाउनलोड करने के लिए यह अध्याय मूल स्रोत से फिर खोलें।|Öffne dieses Kapitel zum Herunterladen erneut aus seiner ursprünglichen Quelle.
This chapter is no longer available from its source.|Este capítulo ya no está disponible en su fuente.|Este capítulo não está mais disponível na fonte.|Ce chapitre n’est plus disponible auprès de sa source.|यह अध्याय अब अपने स्रोत पर उपलब्ध नहीं है।|Dieses Kapitel ist bei seiner Quelle nicht mehr verfügbar.
Manga tracking|Seguimiento de manga|Acompanhamento de mangá|Suivi des mangas|मंगा ट्रैकिंग|Manga-Tracking
Reading history could not be loaded. Retry before continuing.|No se pudo cargar el historial. Reinténtalo antes de continuar.|Não foi possível carregar o histórico. Tente novamente antes de continuar.|Impossible de charger l’historique. Réessayez avant de continuer.|पढ़ने का इतिहास लोड नहीं हुआ। आगे बढ़ने से पहले फिर कोशिश करें।|Der Leseverlauf konnte nicht geladen werden. Versuche es vor dem Fortfahren erneut.
Retry history|Reintentar historial|Tentar histórico novamente|Recharger l’historique|इतिहास फिर लोड करें|Verlauf erneut laden
Share the manga title and public cover. Turn off to hide both and show only “Reading manga”.|Comparte el título y la portada pública del manga. Desactívalo para ocultarlos y mostrar solo «Leyendo manga».|Compartilhe o título e a capa pública do mangá. Desative para ocultar ambos e mostrar apenas “Lendo mangá”.|Partagez le titre et la couverture publique du manga. Désactivez pour les masquer et afficher seulement « Lecture de manga ».|मंगा का शीर्षक और सार्वजनिक कवर साझा करें। दोनों छिपाने और केवल “मंगा पढ़ रहे हैं” दिखाने के लिए बंद करें।|Teile Mangatitel und öffentliches Cover. Deaktiviere dies, um beides auszublenden und nur „Liest Manga“ anzuzeigen.
Checked {checked} titles • {new} new chapters • {failed} unavailable • {remaining} left to check|{checked} títulos comprobados • {new} capítulos nuevos • {failed} no disponibles • {remaining} por comprobar|{checked} títulos verificados • {new} novos capítulos • {failed} indisponíveis • {remaining} restantes|{checked} titres vérifiés • {new} nouveaux chapitres • {failed} indisponibles • {remaining} restants|{checked} शीर्षक जाँचे • {new} नए अध्याय • {failed} अनुपलब्ध • {remaining} बाकी|{checked} Titel geprüft • {new} neue Kapitel • {failed} nicht verfügbar • {remaining} verbleibend
Backup & restore could not be opened. Try again.|No se pudo abrir Copia y restauración. Inténtalo de nuevo.|Não foi possível abrir Backup e restauração. Tente novamente.|Impossible d’ouvrir Sauvegarde et restauration. Réessayez.|बैकअप और बहाली नहीं खोली जा सकी। फिर कोशिश करें।|Sicherung und Wiederherstellung konnte nicht geöffnet werden. Versuche es erneut.
Mark updates seen|Marcar novedades como vistas|Marcar novidades como vistas|Marquer les nouveautés comme vues|नए अध्याय देखे गए चिह्नित करें|Neue Kapitel als gesehen markieren
Chapter updates marked as seen.|Capítulos nuevos marcados como vistos.|Novos capítulos marcados como vistos.|Nouveaux chapitres marqués comme vus.|नए अध्याय देखे गए चिह्नित हुए।|Neue Kapitel als gesehen markiert.
Chapter updates could not be marked as seen. Try again.|No se pudieron marcar las novedades como vistas. Inténtalo de nuevo.|Não foi possível marcar as novidades como vistas. Tente novamente.|Impossible de marquer les nouveautés comme vues. Réessayez.|नए अध्याय देखे गए चिह्नित नहीं हुए। फिर कोशिश करें।|Neue Kapitel konnten nicht als gesehen markiert werden. Versuche es erneut.
Your original manga is no longer saved. Reopen the library.|Tu manga original ya no está guardado. Vuelve a abrir la biblioteca.|Seu mangá original não está mais salvo. Reabra a biblioteca.|Votre manga d’origine n’est plus enregistré. Rouvrez la bibliothèque.|मूल मंगा अब सहेजा नहीं है। लाइब्रेरी फिर खोलें।|Dein ursprünglicher Manga ist nicht mehr gespeichert. Öffne die Bibliothek erneut.
No completed download is available for this chapter.|No hay una descarga completa de este capítulo.|Não há download concluído para este capítulo.|Aucun téléchargement complet n’est disponible pour ce chapitre.|इस अध्याय का पूरा डाउनलोड उपलब्ध नहीं है।|Für dieses Kapitel ist kein vollständiger Download verfügbar.
''';
