/// App-authored playback, source selection, download and private-library copy.
/// Row order: Spanish, Brazilian Portuguese, French, Hindi, German.
/// Media titles, server/provider text and identifiers are never catalog entries.
const playbackTranslationRows = <String, List<String>>{
  ..._playbackStatusTranslations,
  'PARTY {code} • {status}{connection}': [
    'SALA {code} • {status}{connection}',
    'SALA {code} • {status}{connection}',
    'SALON {code} • {status}{connection}',
    'पार्टी {code} • {status}{connection}',
    'PARTY {code} • {status}{connection}',
  ],
  'HOST': ['ANFITRIÓN', 'ANFITRIÃO', 'HÔTE', 'होस्ट', 'HOST'],
  'RECONNECTING': [
    'RECONECTANDO',
    'RECONECTANDO',
    'RECONNEXION',
    'फिर कनेक्ट हो रहा है',
    'VERBINDUNG WIRD HERGESTELLT',
  ],
  'EXACT SOURCE': [
    'MISMA FUENTE',
    'MESMA FONTE',
    'MÊME SOURCE',
    'एक ही स्रोत',
    'IDENTISCHE QUELLE',
  ],
  'SOURCE ALIGNED': [
    'FUENTE ALINEADA',
    'FONTE ALINHADA',
    'SOURCE ALIGNÉE',
    'स्रोत सिंक है',
    'QUELLE ABGESTIMMT',
  ],
  'TIMELINE ADJUSTED': [
    'TIEMPOS AJUSTADOS',
    'TEMPOS AJUSTADOS',
    'TIMING AJUSTÉ',
    'समय समायोजित',
    'ZEITABLAUF ANGEPASST',
  ],
  'DIFFERENT CUT': [
    'OTRA EDICIÓN',
    'EDIÇÃO DIFERENTE',
    'MONTAGE DIFFÉRENT',
    'अलग संस्करण',
    'ANDERE SCHNITTFASSUNG',
  ],
  'VERIFYING': [
    'VERIFICANDO',
    'VERIFICANDO',
    'VÉRIFICATION',
    'जाँच हो रही है',
    'WIRD GEPRÜFT',
  ],
  'Play': ['Reproducir', 'Reproduzir', 'Lire', 'चलाएँ', 'Abspielen'],
  'Pause': ['Pausar', 'Pausar', 'Pause', 'रोकें', 'Pausieren'],
  'Resume': ['Reanudar', 'Retomar', 'Reprendre', 'फिर चलाएँ', 'Fortsetzen'],
  'Cancel': ['Cancelar', 'Cancelar', 'Annuler', 'रद्द करें', 'Abbrechen'],
  'Continue': ['Continuar', 'Continuar', 'Continuer', 'जारी रखें', 'Weiter'],
  'Close': ['Cerrar', 'Fechar', 'Fermer', 'बंद करें', 'Schließen'],
  'Back': ['Atrás', 'Voltar', 'Retour', 'वापस', 'Zurück'],
  'Go back': ['Volver', 'Voltar', 'Revenir', 'वापस जाएँ', 'Zurückgehen'],
  'Up': ['Subir', 'Subir', 'Remonter', 'ऊपर', 'Nach oben'],
  'Clear': ['Borrar', 'Limpar', 'Effacer', 'साफ़ करें', 'Leeren'],
  'Refresh': [
    'Actualizar',
    'Atualizar',
    'Actualiser',
    'रीफ़्रेश करें',
    'Aktualisieren',
  ],
  'Retry': [
    'Reintentar',
    'Tentar novamente',
    'Réessayer',
    'फिर कोशिश करें',
    'Erneut versuchen',
  ],
  'Try again': [
    'Intentar de nuevo',
    'Tentar novamente',
    'Réessayer',
    'फिर कोशिश करें',
    'Erneut versuchen',
  ],
  'Delete': ['Eliminar', 'Excluir', 'Supprimer', 'मिटाएँ', 'Löschen'],
  'Remove': ['Quitar', 'Remover', 'Retirer', 'हटाएँ', 'Entfernen'],
  'Search': ['Buscar', 'Pesquisar', 'Rechercher', 'खोजें', 'Suchen'],
  'Off': ['Desactivado', 'Desativado', 'Désactivé', 'बंद', 'Aus'],
  'Automatic': [
    'Automático',
    'Automático',
    'Automatique',
    'अपने आप',
    'Automatisch',
  ],
  'Small': ['Pequeño', 'Pequeno', 'Petit', 'छोटा', 'Klein'],
  'Medium': ['Mediano', 'Médio', 'Moyen', 'मध्यम', 'Mittel'],
  'Large': ['Grande', 'Grande', 'Grand', 'बड़ा', 'Groß'],
  'Extra large': [
    'Muy grande',
    'Muito grande',
    'Très grand',
    'बहुत बड़ा',
    'Sehr groß',
  ],
  'Audio': ['Audio', 'Áudio', 'Audio', 'ऑडियो', 'Audio'],
  'CC': ['CC', 'CC', 'ST', 'CC', 'UT'],
  'Closed captions': [
    'Subtítulos',
    'Legendas',
    'Sous-titres',
    'उपशीर्षक',
    'Untertitel',
  ],
  'Choose caption size': [
    'Elegir tamaño de subtítulos',
    'Escolher tamanho das legendas',
    'Taille des sous-titres',
    'उपशीर्षक का आकार चुनें',
    'Untertitelgröße wählen',
  ],
  'Playback speed': [
    'Velocidad de reproducción',
    'Velocidade de reprodução',
    'Vitesse de lecture',
    'प्लेबैक की गति',
    'Wiedergabegeschwindigkeit',
  ],
  'Playback Speed': [
    'Velocidad de reproducción',
    'Velocidade de reprodução',
    'Vitesse de lecture',
    'प्लेबैक की गति',
    'Wiedergabegeschwindigkeit',
  ],
  'Previous Episode': [
    'Episodio anterior',
    'Episódio anterior',
    'Épisode précédent',
    'पिछला एपिसोड',
    'Vorherige Folge',
  ],
  'Next Episode': [
    'Siguiente episodio',
    'Próximo episódio',
    'Épisode suivant',
    'अगला एपिसोड',
    'Nächste Folge',
  ],
  'Back {value1}s': [
    'Retroceder {value1} s',
    'Voltar {value1} s',
    'Reculer de {value1} s',
    '{value1} सेकंड पीछे',
    '{value1} s zurück',
  ],
  'Forward {value1}s': [
    'Avanzar {value1} s',
    'Avançar {value1} s',
    'Avancer de {value1} s',
    '{value1} सेकंड आगे',
    '{value1} s vor',
  ],
  'Seek {value1}': [
    'Ir a {value1}',
    'Ir para {value1}',
    'Aller à {value1}',
    '{value1} पर जाएँ',
    'Zu {value1} springen',
  ],
  'Picture': ['Imagen', 'Imagem', 'Image', 'चित्र', 'Bild'],
  'Options': ['Opciones', 'Opções', 'Options', 'विकल्प', 'Optionen'],
  'Playback options': [
    'Opciones de reproducción',
    'Opções de reprodução',
    'Options de lecture',
    'प्लेबैक विकल्प',
    'Wiedergabeoptionen',
  ],
  'Changes apply immediately': [
    'Los cambios se aplican al instante',
    'As alterações são aplicadas imediatamente',
    'Les changements sont immédiats',
    'बदलाव तुरंत लागू होंगे',
    'Änderungen werden sofort angewendet',
  ],
  'DECODER': [
    'DECODIFICADOR',
    'DECODIFICADOR',
    'DÉCODEUR',
    'डिकोडर',
    'DECODER',
  ],
  'Hardware': ['Hardware', 'Hardware', 'Matériel', 'हार्डवेयर', 'Hardware'],
  'Software': ['Software', 'Software', 'Logiciel', 'सॉफ़्टवेयर', 'Software'],
  'Hardware (copy)': [
    'Hardware (copia)',
    'Hardware (cópia)',
    'Matériel (copie)',
    'हार्डवेयर (कॉपी)',
    'Hardware (Kopie)',
  ],
  'PICTURE': ['IMAGEN', 'IMAGEM', 'IMAGE', 'चित्र', 'BILD'],
  'Fit': ['Ajustar', 'Ajustar', 'Adapter', 'फ़िट करें', 'Einpassen'],
  'Fill screen': [
    'Llenar pantalla',
    'Preencher tela',
    'Remplir l’écran',
    'स्क्रीन भरें',
    'Bildschirm füllen',
  ],
  'Stretch': ['Estirar', 'Esticar', 'Étirer', 'खींचें', 'Strecken'],
  'SPEED': ['VELOCIDAD', 'VELOCIDADE', 'VITESSE', 'गति', 'GESCHWINDIGKEIT'],
  'SUBTITLE SIZE': [
    'TAMAÑO DE SUBTÍTULOS',
    'TAMANHO DAS LEGENDAS',
    'TAILLE DES SOUS-TITRES',
    'उपशीर्षक का आकार',
    'UNTERTITELGRÖSSE',
  ],
  'SUBTITLE STYLE': [
    'ESTILO DE SUBTÍTULOS',
    'ESTILO DAS LEGENDAS',
    'STYLE DES SOUS-TITRES',
    'उपशीर्षक की शैली',
    'UNTERTITELSTIL',
  ],
  'Bottom': ['Abajo', 'Embaixo', 'En bas', 'नीचे', 'Unten'],
  'Raised': ['Elevado', 'Elevado', 'Surélevé', 'थोड़ा ऊपर', 'Angehoben'],
  'Higher': ['Más arriba', 'Mais alto', 'Plus haut', 'और ऊपर', 'Höher'],
  'High contrast off': [
    'Alto contraste desactivado',
    'Alto contraste desativado',
    'Contraste élevé désactivé',
    'उच्च कंट्रास्ट बंद',
    'Hoher Kontrast aus',
  ],
  'High contrast on': [
    'Alto contraste activado',
    'Alto contraste ativado',
    'Contraste élevé activé',
    'उच्च कंट्रास्ट चालू',
    'Hoher Kontrast an',
  ],
  'SYNC': [
    'SINCRONIZACIÓN',
    'SINCRONIZAÇÃO',
    'SYNCHRONISATION',
    'सिंक',
    'SYNCHRONISIERUNG',
  ],
  'Subs {value1}{value2}ms': [
    'Subtítulos {value1}{value2} ms',
    'Legendas {value1}{value2} ms',
    'Sous-titres {value1}{value2} ms',
    'उपशीर्षक {value1}{value2} मि.से.',
    'Untertitel {value1}{value2} ms',
  ],
  'Audio {value1}{value2}ms': [
    'Audio {value1}{value2} ms',
    'Áudio {value1}{value2} ms',
    'Audio {value1}{value2} ms',
    'ऑडियो {value1}{value2} मि.से.',
    'Audio {value1}{value2} ms',
  ],
  'Select with D-pad': [
    'Selecciona con la cruceta',
    'Selecione com o direcional',
    'Sélectionner avec les flèches',
    'दिशा बटन से चुनें',
    'Mit Steuerkreuz auswählen',
  ],
  'Audio track (1 found)': [
    'Pista de audio (1 encontrada)',
    'Faixa de áudio (1 encontrada)',
    'Piste audio (1 trouvée)',
    'ऑडियो ट्रैक (1 मिला)',
    'Audiospur (1 gefunden)',
  ],
  'Audio track (only 1 detected)': [
    'Pista de audio (solo 1 detectada)',
    'Faixa de áudio (apenas 1 detectada)',
    'Piste audio (1 seule détectée)',
    'ऑडियो ट्रैक (केवल 1 मिला)',
    'Audiospur (nur 1 erkannt)',
  ],
  'Audio tracks ({value1} found)': [
    'Pistas de audio ({value1} encontradas)',
    'Faixas de áudio ({value1} encontradas)',
    'Pistes audio ({value1} trouvées)',
    'ऑडियो ट्रैक ({value1} मिले)',
    'Audiospuren ({value1} gefunden)',
  ],
  'Track {value1}': [
    'Pista {value1}',
    'Faixa {value1}',
    'Piste {value1}',
    'ट्रैक {value1}',
    'Spur {value1}',
  ],
  'Audio and caption timing offsets are available in MPV. Switch the built-in player in Playback settings when a stream needs manual timing adjustment.': [
    'MPV permite ajustar la sincronización de audio y subtítulos. Cambia el reproductor integrado en Ajustes de reproducción si necesitas un ajuste manual.',
    'O MPV permite ajustar o tempo do áudio e das legendas. Altere o reprodutor integrado nas configurações de reprodução se precisar de ajuste manual.',
    'MPV permet de décaler l’audio et les sous-titres. Changez le lecteur intégré dans les paramètres de lecture si un réglage manuel est nécessaire.',
    'MPV में ऑडियो और उपशीर्षक का समय बदला जा सकता है। हाथ से समय ठीक करना हो तो प्लेबैक सेटिंग में बिल्ट-इन प्लेयर बदलें।',
    'MPV unterstützt Zeitversatz für Audio und Untertitel. Wechsle den integrierten Player in den Wiedergabeeinstellungen, wenn eine manuelle Anpassung nötig ist.',
  ],
  'Exit video': [
    'Salir del video',
    'Sair do vídeo',
    'Quitter la vidéo',
    'वीडियो से बाहर जाएँ',
    'Video verlassen',
  ],
  'Exit video?': [
    '¿Salir del video?',
    'Sair do vídeo?',
    'Quitter la vidéo ?',
    'वीडियो से बाहर जाएँ?',
    'Video verlassen?',
  ],
  'Continue watching': [
    'Seguir viendo',
    'Continuar assistindo',
    'Continuer à regarder',
    'देखना जारी रखें',
    'Weiterschauen',
  ],
  'Your current playback position will be saved.': [
    'Se guardará tu posición de reproducción.',
    'Sua posição de reprodução será salva.',
    'Votre position de lecture sera enregistrée.',
    'आपकी मौजूदा प्लेबैक स्थिति सहेजी जाएगी।',
    'Deine aktuelle Wiedergabeposition wird gespeichert.',
  ],
  'Playback blocked': [
    'Reproducción bloqueada',
    'Reprodução bloqueada',
    'Lecture bloquée',
    'प्लेबैक अवरुद्ध है',
    'Wiedergabe blockiert',
  ],
  'TetoTV only accepts streams resolved through a connected supported debrid account.': [
    'TetoTV solo acepta enlaces obtenidos mediante una cuenta debrid compatible y conectada.',
    'O TetoTV só aceita transmissões obtidas por uma conta debrid compatível e conectada.',
    'TetoTV accepte uniquement les flux obtenus via un compte debrid compatible et connecté.',
    'TetoTV केवल जुड़े हुए समर्थित debrid खाते से प्राप्त स्ट्रीम स्वीकार करता है।',
    'TetoTV akzeptiert nur Streams, die über ein verbundenes unterstütztes Debrid-Konto aufgelöst wurden.',
  ],
  'Sources': ['Fuentes', 'Fontes', 'Sources', 'स्रोत', 'Quellen'],
  'Source': ['Fuente', 'Fonte', 'Source', 'स्रोत', 'Quelle'],
  'Quality': ['Calidad', 'Qualidade', 'Qualité', 'गुणवत्ता', 'Qualität'],
  'Sources & quality': [
    'Fuentes y calidad',
    'Fontes e qualidade',
    'Sources et qualité',
    'स्रोत और गुणवत्ता',
    'Quellen und Qualität',
  ],
  'Sources and quality': [
    'Fuentes y calidad',
    'Fontes e qualidade',
    'Sources et qualité',
    'स्रोत और गुणवत्ता',
    'Quellen und Qualität',
  ],
  'Refresh sources': [
    'Actualizar fuentes',
    'Atualizar fontes',
    'Actualiser les sources',
    'स्रोत रीफ़्रेश करें',
    'Quellen aktualisieren',
  ],
  'Choose your stream': [
    'Elige tu fuente',
    'Escolha sua transmissão',
    'Choisissez votre flux',
    'अपनी स्ट्रीम चुनें',
    'Stream auswählen',
  ],
  'Choose source': [
    'Elegir fuente',
    'Escolher fonte',
    'Choisir une source',
    'स्रोत चुनें',
    'Quelle auswählen',
  ],
  'Choose stream': [
    'Elegir transmisión',
    'Escolher transmissão',
    'Choisir un flux',
    'स्ट्रीम चुनें',
    'Stream auswählen',
  ],
  'Restart stream': [
    'Reiniciar transmisión',
    'Reiniciar transmissão',
    'Relancer le flux',
    'स्ट्रीम फिर शुरू करें',
    'Stream neu starten',
  ],
  'Retry stream': [
    'Reintentar transmisión',
    'Tentar transmissão novamente',
    'Réessayer le flux',
    'स्ट्रीम फिर आज़माएँ',
    'Stream erneut versuchen',
  ],
  'Next stream': [
    'Siguiente transmisión',
    'Próxima transmissão',
    'Flux suivant',
    'अगली स्ट्रीम',
    'Nächster Stream',
  ],
  'Try next stream': [
    'Probar siguiente transmisión',
    'Tentar próxima transmissão',
    'Essayer le flux suivant',
    'अगली स्ट्रीम आज़माएँ',
    'Nächsten Stream versuchen',
  ],
  'Open externally': [
    'Abrir externamente',
    'Abrir externamente',
    'Ouvrir ailleurs',
    'बाहरी प्लेयर में खोलें',
    'Extern öffnen',
  ],
  'No playable sources yet': [
    'Aún no hay fuentes reproducibles',
    'Ainda não há fontes reproduzíveis',
    'Aucune source lisible pour le moment',
    'अभी चलाने योग्य स्रोत नहीं हैं',
    'Noch keine abspielbaren Quellen',
  ],
  'No playable stream found': [
    'No se encontró una transmisión reproducible',
    'Nenhuma transmissão reproduzível encontrada',
    'Aucun flux lisible trouvé',
    'चलाने योग्य स्ट्रीम नहीं मिली',
    'Kein abspielbarer Stream gefunden',
  ],
  'No stream source is ready': [
    'No hay ninguna fuente lista',
    'Nenhuma fonte está pronta',
    'Aucune source n’est prête',
    'कोई स्ट्रीम स्रोत तैयार नहीं है',
    'Keine Streamquelle ist bereit',
  ],
  'Opening the selected stream…': [
    'Abriendo la transmisión elegida…',
    'Abrindo a transmissão selecionada…',
    'Ouverture du flux sélectionné…',
    'चुनी हुई स्ट्रीम खुल रही है…',
    'Ausgewählter Stream wird geöffnet…',
  ],
  'Could not start this stream: {value1}': [
    'No se pudo iniciar esta transmisión: {value1}',
    'Não foi possível iniciar esta transmissão: {value1}',
    'Impossible de lancer ce flux : {value1}',
    'यह स्ट्रीम शुरू नहीं हो सकी: {value1}',
    'Dieser Stream konnte nicht gestartet werden: {value1}',
  ],
  'Cached releases normally complete in a few seconds.': [
    'Las versiones en caché suelen estar listas en pocos segundos.',
    'As versões em cache geralmente ficam prontas em poucos segundos.',
    'Les versions en cache sont généralement prêtes en quelques secondes.',
    'कैश की गई रिलीज़ आम तौर पर कुछ सेकंड में तैयार हो जाती हैं।',
    'Zwischengespeicherte Veröffentlichungen sind meist in wenigen Sekunden bereit.',
  ],
  'Back to streams': [
    'Volver a las transmisiones',
    'Voltar às transmissões',
    'Retour aux flux',
    'स्ट्रीम पर वापस',
    'Zurück zu den Streams',
  ],
  'Add a release': [
    'Añadir una versión',
    'Adicionar uma versão',
    'Ajouter une version',
    'रिलीज़ जोड़ें',
    'Veröffentlichung hinzufügen',
  ],
  'Paste a magnet': [
    'Pegar un enlace magnet',
    'Colar um link magnet',
    'Coller un lien magnet',
    'मैग्नेट लिंक पेस्ट करें',
    'Magnet-Link einfügen',
  ],
  'Magnet URI': [
    'URI magnet',
    'URI magnet',
    'URI magnet',
    'मैग्नेट URI',
    'Magnet-URI',
  ],
  'Enter magnet URI': [
    'Introducir URI magnet',
    'Inserir URI magnet',
    'Saisir l’URI magnet',
    'मैग्नेट URI दर्ज करें',
    'Magnet-URI eingeben',
  ],
  'Select to type or paste a magnet link': [
    'Selecciona para escribir o pegar un enlace magnet',
    'Selecione para digitar ou colar um link magnet',
    'Sélectionnez pour saisir ou coller un lien magnet',
    'मैग्नेट लिंक लिखने या पेस्ट करने के लिए चुनें',
    'Zum Eingeben oder Einfügen eines Magnet-Links auswählen',
  ],
  'Use a magnet for content you are authorized to access.': [
    'Usa un enlace magnet de contenido al que tengas derecho de acceder.',
    'Use um link magnet de conteúdo que você tem autorização para acessar.',
    'Utilisez un lien magnet pour du contenu auquel vous êtes autorisé à accéder.',
    'केवल उस सामग्री का मैग्नेट लिंक इस्तेमाल करें जिसे देखने की आपको अनुमति है।',
    'Verwende einen Magnet-Link für Inhalte, auf die du zugreifen darfst.',
  ],
  'Automatic matching did not return a playable stream. You can provide a magnet manually.': [
    'La búsqueda automática no encontró una transmisión reproducible. Puedes introducir un enlace magnet manualmente.',
    'A busca automática não encontrou uma transmissão reproduzível. Você pode inserir um link magnet manualmente.',
    'La recherche automatique n’a trouvé aucun flux lisible. Vous pouvez saisir un lien magnet manuellement.',
    'अपने आप की गई खोज में चलाने योग्य स्ट्रीम नहीं मिली। आप मैग्नेट लिंक खुद दे सकते हैं।',
    'Die automatische Suche fand keinen abspielbaren Stream. Du kannst einen Magnet-Link manuell eingeben.',
  ],
  'No torrent source is configured. Add a source manifest in Marketplace, or paste a magnet for content you are authorized to access.': [
    'No hay una fuente torrent configurada. Añade un manifiesto en Marketplace o pega un enlace magnet de contenido al que tengas derecho de acceder.',
    'Nenhuma fonte torrent está configurada. Adicione um manifesto no Marketplace ou cole um link magnet de conteúdo autorizado.',
    'Aucune source torrent n’est configurée. Ajoutez un manifeste dans Marketplace ou collez un lien magnet pour du contenu autorisé.',
    'कोई टॉरेंट स्रोत कॉन्फ़िगर नहीं है। Marketplace में स्रोत मैनिफ़ेस्ट जोड़ें या अधिकृत सामग्री का मैग्नेट लिंक पेस्ट करें।',
    'Keine Torrent-Quelle ist eingerichtet. Füge ein Manifest im Marketplace hinzu oder einen Magnet-Link für erlaubte Inhalte.',
  ],
  'Play direct torrent': [
    'Reproducir torrent directo',
    'Reproduzir torrent direto',
    'Lire le torrent directement',
    'टॉरेंट सीधे चलाएँ',
    'Torrent direkt abspielen',
  ],
  'Send to {value1}': [
    'Enviar a {value1}',
    'Enviar para {value1}',
    'Envoyer à {value1}',
    '{value1} को भेजें',
    'An {value1} senden',
  ],
  'Search sources': [
    'Buscar fuentes',
    'Pesquisar fontes',
    'Rechercher des sources',
    'स्रोत खोजें',
    'Quellen suchen',
  ],
  'Search this stream list': [
    'Buscar en esta lista',
    'Pesquisar nesta lista',
    'Rechercher dans cette liste',
    'इस स्ट्रीम सूची में खोजें',
    'Diese Streamliste durchsuchen',
  ],
  'Release, group, quality, codec…': [
    'Versión, grupo, calidad, códec…',
    'Versão, grupo, qualidade, codec…',
    'Version, groupe, qualité, codec…',
    'रिलीज़, समूह, गुणवत्ता, कोडेक…',
    'Veröffentlichung, Gruppe, Qualität, Codec…',
  ],
  'Filters ({value1})': [
    'Filtros ({value1})',
    'Filtros ({value1})',
    'Filtres ({value1})',
    'फ़िल्टर ({value1})',
    'Filter ({value1})',
  ],
  'Filters': ['Filtros', 'Filtros', 'Filtres', 'फ़िल्टर', 'Filter'],
  'ALL': ['TODOS', 'TODOS', 'TOUS', 'सभी', 'ALLE'],
  'ANY': ['CUALQUIERA', 'QUALQUER', 'TOUT', 'कोई भी', 'BELIEBIG'],
  'BEST': ['MEJOR', 'MELHOR', 'MEILLEUR', 'सर्वश्रेष्ठ', 'BESTE'],
  'LARGEST': [
    'MAYOR TAMAÑO',
    'MAIOR TAMANHO',
    'PLUS VOLUMINEUX',
    'सबसे बड़ा',
    'GRÖSSTE',
  ],
  'SMALLEST': [
    'MENOR TAMAÑO',
    'MENOR TAMANHO',
    'MOINS VOLUMINEUX',
    'सबसे छोटा',
    'KLEINSTE',
  ],
  'SEEDERS': ['COMPARTIENDO', 'SEMEADORES', 'SEEDERS', 'सीडर', 'SEEDER'],
  'SUB': ['SUB', 'LEG', 'ST', 'उपशीर्षक', 'UT'],
  'DUB': ['DOBLAJE', 'DUBLADO', 'DOUBLAGE', 'डब', 'SYNCHRO'],
  'BATCH': ['PAQUETE', 'PACOTE', 'LOT', 'बैच', 'PAKET'],
  'BATCHES OFF': [
    'PAQUETES NO',
    'PACOTES NÃO',
    'LOTS NON',
    'बैच बंद',
    'PAKETE AUS',
  ],
  'BATCHES ON': [
    'PAQUETES SÍ',
    'PACOTES SIM',
    'LOTS OUI',
    'बैच चालू',
    'PAKETE AN',
  ],
  'RECOMMENDED': [
    'RECOMENDADO',
    'RECOMENDADO',
    'RECOMMANDÉ',
    'सुझाया गया',
    'EMPFOHLEN',
  ],
  'TV SAFE': [
    'APTO PARA TV',
    'COMPATÍVEL COM TV',
    'ADAPTÉ À LA TV',
    'टीवी के अनुकूल',
    'TV-GEEIGNET',
  ],
  'SUBTITLES': [
    'SUBTÍTULOS',
    'LEGENDAS',
    'SOUS-TITRES',
    'उपशीर्षक',
    'UNTERTITEL',
  ],
  'PROVIDERS • {value1}': [
    'PROVEEDORES • {value1}',
    'PROVEDORES • {value1}',
    'FOURNISSEURS • {value1}',
    'प्रदाता • {value1}',
    'ANBIETER • {value1}',
  ],
  'Retry failed ({value1})': [
    'Reintentar fallidos ({value1})',
    'Tentar falhas novamente ({value1})',
    'Réessayer les échecs ({value1})',
    'विफल स्रोत फिर आज़माएँ ({value1})',
    'Fehlgeschlagene wiederholen ({value1})',
  ],
  '{value1} • Available results can be selected now.': [
    '{value1} • Ya puedes elegir los resultados disponibles.',
    '{value1} • Os resultados disponíveis já podem ser selecionados.',
    '{value1} • Vous pouvez déjà sélectionner les résultats disponibles.',
    '{value1} • उपलब्ध परिणाम अभी चुने जा सकते हैं।',
    '{value1} • Verfügbare Ergebnisse können bereits ausgewählt werden.',
  ],
  'Open accounts': [
    'Abrir cuentas',
    'Abrir contas',
    'Ouvrir les comptes',
    'खाते खोलें',
    'Konten öffnen',
  ],
  'Open marketplace': [
    'Abrir Marketplace',
    'Abrir Marketplace',
    'Ouvrir Marketplace',
    'Marketplace खोलें',
    'Marketplace öffnen',
  ],
  'Manage media sources': [
    'Gestionar fuentes multimedia',
    'Gerenciar fontes de mídia',
    'Gérer les sources multimédias',
    'मीडिया स्रोत प्रबंधित करें',
    'Medienquellen verwalten',
  ],
  'A local media server is unavailable': [
    'Un servidor multimedia local no está disponible',
    'Um servidor de mídia local está indisponível',
    'Un serveur multimédia local est indisponible',
    'स्थानीय मीडिया सर्वर उपलब्ध नहीं है',
    'Ein lokaler Medienserver ist nicht verfügbar',
  ],
  'This episode is not in your local sources': [
    'Este episodio no está en tus fuentes locales',
    'Este episódio não está nas suas fontes locais',
    'Cet épisode n’est pas dans vos sources locales',
    'यह एपिसोड आपके स्थानीय स्रोतों में नहीं है',
    'Diese Folge ist nicht in deinen lokalen Quellen',
  ],
  'Downloads': [
    'Descargas',
    'Downloads',
    'Téléchargements',
    'डाउनलोड',
    'Downloads',
  ],
  'Download': [
    'Descargar',
    'Baixar',
    'Télécharger',
    'डाउनलोड करें',
    'Herunterladen',
  ],
  'Download season': [
    'Descargar temporada',
    'Baixar temporada',
    'Télécharger la saison',
    'सीज़न डाउनलोड करें',
    'Staffel herunterladen',
  ],
  'Add to Downloads': [
    'Añadir a descargas',
    'Adicionar aos downloads',
    'Ajouter aux téléchargements',
    'डाउनलोड में जोड़ें',
    'Zu Downloads hinzufügen',
  ],
  'Cancel season': [
    'Cancelar temporada',
    'Cancelar temporada',
    'Annuler la saison',
    'सीज़न रद्द करें',
    'Staffel abbrechen',
  ],
  'No offline episodes yet': [
    'Aún no hay episodios sin conexión',
    'Ainda não há episódios offline',
    'Aucun épisode hors ligne',
    'अभी कोई ऑफ़लाइन एपिसोड नहीं है',
    'Noch keine Offline-Folgen',
  ],
  'Long-press a torrent or web source, or choose Download season on a show.': [
    'Mantén pulsada una fuente torrent o web, o elige Descargar temporada en una serie.',
    'Pressione uma fonte torrent ou web por alguns instantes, ou escolha Baixar temporada em uma série.',
    'Appuyez longuement sur une source torrent ou web, ou choisissez Télécharger la saison sur une série.',
    'टॉरेंट या वेब स्रोत पर देर तक दबाएँ, या शो में सीज़न डाउनलोड करें चुनें।',
    'Halte eine Torrent- oder Webquelle gedrückt oder wähle bei einer Serie „Staffel herunterladen“.',
  ],
  'Preparing season download…': [
    'Preparando descarga de temporada…',
    'Preparando download da temporada…',
    'Préparation du téléchargement de la saison…',
    'सीज़न डाउनलोड तैयार हो रहा है…',
    'Staffeldownload wird vorbereitet…',
  ],
  'Downloading season • {value1} of {value2}': [
    'Descargando temporada • {value1} de {value2}',
    'Baixando temporada • {value1} de {value2}',
    'Téléchargement de la saison • {value1} sur {value2}',
    'सीज़न डाउनलोड हो रहा है • {value2} में से {value1}',
    'Staffel wird heruntergeladen • {value1} von {value2}',
  ],
  'Downloaded episode {value1}': [
    'Episodio {value1} descargado',
    'Episódio {value1} baixado',
    'Épisode {value1} téléchargé',
    'एपिसोड {value1} डाउनलोड किया गया',
    'Heruntergeladene Folge {value1}',
  ],
  '{value1} • Episode {value2}': [
    '{value1} • Episodio {value2}',
    '{value1} • Episódio {value2}',
    '{value1} • Épisode {value2}',
    '{value1} • एपिसोड {value2}',
    '{value1} • Folge {value2}',
  ],
  'Download this episode?': [
    '¿Descargar este episodio?',
    'Baixar este episódio?',
    'Télécharger cet épisode ?',
    'यह एपिसोड डाउनलोड करें?',
    'Diese Folge herunterladen?',
  ],
  'Download without Debrid?': [
    '¿Descargar sin Debrid?',
    'Baixar sem Debrid?',
    'Télécharger sans Debrid ?',
    'Debrid के बिना डाउनलोड करें?',
    'Ohne Debrid herunterladen?',
  ],
  'Download from public torrent peers?': [
    '¿Descargar de pares torrent públicos?',
    'Baixar de pares torrent públicos?',
    'Télécharger depuis des pairs torrent publics ?',
    'सार्वजनिक टॉरेंट पीयर से डाउनलोड करें?',
    'Von öffentlichen Torrent-Peers herunterladen?',
  ],
  'Download directly': [
    'Descargar directamente',
    'Baixar diretamente',
    'Télécharger directement',
    'सीधे डाउनलोड करें',
    'Direkt herunterladen',
  ],
  'Direct torrent downloads connect to peers. Your public IP address may be visible to them. This choice applies to the entire season.': [
    'Las descargas torrent directas se conectan a otros pares. Estos pueden ver tu dirección IP pública. Esta elección se aplica a toda la temporada.',
    'Downloads torrent diretos conectam você a outros pares. Eles podem ver seu endereço IP público. Esta escolha vale para toda a temporada.',
    'Les téléchargements torrent directs vous connectent à des pairs. Votre adresse IP publique peut leur être visible. Ce choix s’applique à toute la saison.',
    'सीधे टॉरेंट डाउनलोड में आप दूसरे पीयर से जुड़ते हैं। उन्हें आपका सार्वजनिक IP पता दिख सकता है। यह विकल्प पूरे सीज़न पर लागू होगा।',
    'Direkte Torrent-Downloads verbinden dich mit Peers. Diese können deine öffentliche IP-Adresse sehen. Die Auswahl gilt für die gesamte Staffel.',
  ],
  'Best available': [
    'Mejor disponible',
    'Melhor disponível',
    'Meilleure disponible',
    'उपलब्ध सर्वश्रेष्ठ',
    'Beste verfügbare',
  ],
  'Web streams': [
    'Transmisiones web',
    'Transmissões web',
    'Flux web',
    'वेब स्ट्रीम',
    'Webstreams',
  ],
  'Direct torrent': [
    'Torrent directo',
    'Torrent direto',
    'Torrent direct',
    'सीधा टॉरेंट',
    'Direkter Torrent',
  ],
  'Configured Debrid first, then Web streams': [
    'Primero Debrid configurado, después fuentes web',
    'Primeiro o Debrid configurado, depois fontes web',
    'Debrid configuré d’abord, puis flux web',
    'पहले कॉन्फ़िगर किया गया Debrid, फिर वेब स्ट्रीम',
    'Zuerst eingerichtetes Debrid, danach Webstreams',
  ],
  'Use the configured Debrid service': [
    'Usar el servicio Debrid configurado',
    'Usar o serviço Debrid configurado',
    'Utiliser le service Debrid configuré',
    'कॉन्फ़िगर की गई Debrid सेवा इस्तेमाल करें',
    'Eingerichteten Debrid-Dienst verwenden',
  ],
  'Use installed Web providers': [
    'Usar proveedores web instalados',
    'Usar provedores web instalados',
    'Utiliser les fournisseurs web installés',
    'इंस्टॉल किए गए वेब प्रदाता इस्तेमाल करें',
    'Installierte Webanbieter verwenden',
  ],
  'Download through peers without Debrid': [
    'Descargar mediante pares sin Debrid',
    'Baixar por pares sem Debrid',
    'Télécharger via des pairs sans Debrid',
    'Debrid के बिना पीयर से डाउनलोड करें',
    'Über Peers ohne Debrid herunterladen',
  ],
  'Enable direct torrent streaming in Settings': [
    'Activa la reproducción torrent directa en Ajustes',
    'Ative a transmissão torrent direta nas configurações',
    'Activez les torrents directs dans les paramètres',
    'सेटिंग में सीधी टॉरेंट स्ट्रीमिंग चालू करें',
    'Direktes Torrent-Streaming in den Einstellungen aktivieren',
  ],
  'This downloaded episode is missing or incomplete.': [
    'Este episodio descargado falta o está incompleto.',
    'Este episódio baixado está ausente ou incompleto.',
    'Cet épisode téléchargé est absent ou incomplet.',
    'यह डाउनलोड किया गया एपिसोड गायब या अधूरा है।',
    'Diese heruntergeladene Folge fehlt oder ist unvollständig.',
  ],
  'Queued': ['En cola', 'Na fila', 'En attente', 'कतार में', 'Warteschlange'],
  'Resolving': [
    'Buscando enlace',
    'Obtendo link',
    'Résolution',
    'लिंक मिल रहा है',
    'Wird aufgelöst',
  ],
  'Downloading': [
    'Descargando',
    'Baixando',
    'Téléchargement',
    'डाउनलोड हो रहा है',
    'Wird heruntergeladen',
  ],
  'Paused': ['Pausado', 'Pausado', 'En pause', 'रुका हुआ', 'Pausiert'],
  'Completed': [
    'Completado',
    'Concluído',
    'Terminé',
    'पूरा हुआ',
    'Abgeschlossen',
  ],
  'Failed': ['Error', 'Falhou', 'Échec', 'विफल', 'Fehlgeschlagen'],
  'Cancelled': [
    'Cancelado',
    'Cancelado',
    'Annulé',
    'रद्द किया गया',
    'Abgebrochen',
  ],
  'OPEN': ['ABRIR', 'ABRIR', 'OUVRIR', 'खोलें', 'ÖFFNEN'],
  'Your media': [
    'Tu contenido',
    'Sua mídia',
    'Vos médias',
    'आपका मीडिया',
    'Deine Medien',
  ],
  'Media sources': [
    'Fuentes multimedia',
    'Fontes de mídia',
    'Sources multimédias',
    'मीडिया स्रोत',
    'Medienquellen',
  ],
  'LOCAL FILES': [
    'ARCHIVOS LOCALES',
    'ARQUIVOS LOCAIS',
    'FICHIERS LOCAUX',
    'स्थानीय फ़ाइलें',
    'LOKALE DATEIEN',
  ],
  'Add local video': [
    'Añadir video local',
    'Adicionar vídeo local',
    'Ajouter une vidéo locale',
    'स्थानीय वीडियो जोड़ें',
    'Lokales Video hinzufügen',
  ],
  'Choose video': [
    'Elegir video',
    'Escolher vídeo',
    'Choisir une vidéo',
    'वीडियो चुनें',
    'Video auswählen',
  ],
  'Play {value1}': [
    'Reproducir {value1}',
    'Reproduzir {value1}',
    'Lire {value1}',
    '{value1} चलाएँ',
    '{value1} abspielen',
  ],
  'Choose a video with Android’s secure file picker. Android does not let apps silently scan your device.': [
    'Elige un video con el selector seguro de Android. Android no permite que las aplicaciones escaneen tu dispositivo sin avisarte.',
    'Escolha um vídeo com o seletor seguro do Android. O Android não permite que apps examinem seu dispositivo silenciosamente.',
    'Choisissez une vidéo avec le sélecteur sécurisé d’Android. Android n’autorise pas les applications à parcourir votre appareil en silence.',
    'Android के सुरक्षित फ़ाइल चयनकर्ता से वीडियो चुनें। Android ऐप को बिना बताए आपका डिवाइस स्कैन नहीं करने देता।',
    'Wähle ein Video mit Androids sicherer Dateiauswahl. Android erlaubt Apps kein heimliches Durchsuchen deines Geräts.',
  ],
  'Add videos with Android’s secure file picker. Matching episodes appear in the normal source picker.': [
    'Añade videos con el selector seguro de Android. Los episodios coincidentes aparecerán en el selector habitual de fuentes.',
    'Adicione vídeos com o seletor seguro do Android. Os episódios correspondentes aparecem no seletor normal de fontes.',
    'Ajoutez des vidéos avec le sélecteur sécurisé d’Android. Les épisodes correspondants apparaissent parmi les sources habituelles.',
    'Android के सुरक्षित फ़ाइल चयनकर्ता से वीडियो जोड़ें। मेल खाने वाले एपिसोड सामान्य स्रोत चयन में दिखेंगे।',
    'Füge Videos mit Androids sicherer Dateiauswahl hinzu. Passende Folgen erscheinen in der normalen Quellenauswahl.',
  ],
  '{value1} was added as an episode-source candidate.': [
    '{value1} se añadió como posible fuente de episodios.',
    '{value1} foi adicionado como possível fonte de episódios.',
    '{value1} a été ajouté comme source possible d’épisodes.',
    '{value1} को संभावित एपिसोड स्रोत के रूप में जोड़ा गया।',
    '{value1} wurde als mögliche Folgenquelle hinzugefügt.',
  ],
  'JELLYFIN SERVER': [
    'SERVIDOR JELLYFIN',
    'SERVIDOR JELLYFIN',
    'SERVEUR JELLYFIN',
    'JELLYFIN सर्वर',
    'JELLYFIN-SERVER',
  ],
  'PLEX MEDIA SERVER': [
    'SERVIDOR MULTIMEDIA PLEX',
    'SERVIDOR DE MÍDIA PLEX',
    'SERVEUR MULTIMÉDIA PLEX',
    'PLEX मीडिया सर्वर',
    'PLEX-MEDIENSERVER',
  ],
  'Connect Jellyfin': [
    'Conectar Jellyfin',
    'Conectar Jellyfin',
    'Connecter Jellyfin',
    'Jellyfin जोड़ें',
    'Jellyfin verbinden',
  ],
  'Connect Plex': [
    'Conectar Plex',
    'Conectar Plex',
    'Connecter Plex',
    'Plex जोड़ें',
    'Plex verbinden',
  ],
  'Disconnect': [
    'Desconectar',
    'Desconectar',
    'Déconnecter',
    'डिस्कनेक्ट करें',
    'Trennen',
  ],
  'Test & refresh': [
    'Probar y actualizar',
    'Testar e atualizar',
    'Tester et actualiser',
    'जाँचें और रीफ़्रेश करें',
    'Testen und aktualisieren',
  ],
  'Server address': [
    'Dirección del servidor',
    'Endereço do servidor',
    'Adresse du serveur',
    'सर्वर का पता',
    'Serveradresse',
  ],
  'Username': [
    'Usuario',
    'Nome de usuário',
    'Nom d’utilisateur',
    'उपयोगकर्ता नाम',
    'Benutzername',
  ],
  'Password': ['Contraseña', 'Senha', 'Mot de passe', 'पासवर्ड', 'Passwort'],
  'Jellyfin server address': [
    'Dirección del servidor Jellyfin',
    'Endereço do servidor Jellyfin',
    'Adresse du serveur Jellyfin',
    'Jellyfin सर्वर का पता',
    'Jellyfin-Serveradresse',
  ],
  'Jellyfin username': [
    'Usuario de Jellyfin',
    'Usuário do Jellyfin',
    'Nom d’utilisateur Jellyfin',
    'Jellyfin उपयोगकर्ता नाम',
    'Jellyfin-Benutzername',
  ],
  'Jellyfin password': [
    'Contraseña de Jellyfin',
    'Senha do Jellyfin',
    'Mot de passe Jellyfin',
    'Jellyfin पासवर्ड',
    'Jellyfin-Passwort',
  ],
  'Plex server address': [
    'Dirección del servidor Plex',
    'Endereço do servidor Plex',
    'Adresse du serveur Plex',
    'Plex सर्वर का पता',
    'Plex-Serveradresse',
  ],
  'Plex access token': [
    'Token de acceso Plex',
    'Token de acesso Plex',
    'Jeton d’accès Plex',
    'Plex एक्सेस टोकन',
    'Plex-Zugriffstoken',
  ],
  'Connect to a Jellyfin server on your home network or an HTTPS server. Your password is used once and is never saved. HTTPS is recommended.': [
    'Conecta un servidor Jellyfin de tu red doméstica o un servidor HTTPS. Tu contraseña se usa una vez y nunca se guarda. Se recomienda HTTPS.',
    'Conecte um servidor Jellyfin da sua rede doméstica ou um servidor HTTPS. Sua senha é usada uma vez e nunca é salva. HTTPS é recomendado.',
    'Connectez un serveur Jellyfin de votre réseau domestique ou un serveur HTTPS. Votre mot de passe est utilisé une seule fois et jamais enregistré. HTTPS est recommandé.',
    'अपने घरेलू नेटवर्क के Jellyfin सर्वर या HTTPS सर्वर से जुड़ें। पासवर्ड एक बार इस्तेमाल होता है और कभी सहेजा नहीं जाता। HTTPS सुझाया जाता है।',
    'Verbinde einen Jellyfin-Server im Heimnetz oder einen HTTPS-Server. Dein Passwort wird einmal verwendet und nie gespeichert. HTTPS wird empfohlen.',
  ],
  'Connect with a Plex server address and X-Plex-Token. The token is stored in Android secure storage and is never placed in a media or artwork URL.': [
    'Conecta con la dirección del servidor Plex y X-Plex-Token. El token se guarda de forma segura en Android y nunca se incluye en una URL de video o imagen.',
    'Conecte com o endereço do servidor Plex e X-Plex-Token. O token fica no armazenamento seguro do Android e nunca é incluído em URLs de mídia ou imagens.',
    'Connectez-vous avec l’adresse du serveur Plex et X-Plex-Token. Le jeton est conservé dans le stockage sécurisé Android, jamais dans une URL de média ou d’image.',
    'Plex सर्वर के पते और X-Plex-Token से जुड़ें। टोकन Android के सुरक्षित भंडारण में रहता है और कभी मीडिया या चित्र URL में नहीं जोड़ा जाता।',
    'Verbinde dich mit Plex-Serveradresse und X-Plex-Token. Das Token liegt in Androids sicherem Speicher und niemals in einer Medien- oder Bild-URL.',
  ],
  'Use an unencrypted local connection?': [
    '¿Usar una conexión local sin cifrar?',
    'Usar uma conexão local sem criptografia?',
    'Utiliser une connexion locale non chiffrée ?',
    'बिना एन्क्रिप्शन वाला स्थानीय कनेक्शन इस्तेमाल करें?',
    'Unverschlüsselte lokale Verbindung verwenden?',
  ],
  'Connect on private network': [
    'Conectar en red privada',
    'Conectar na rede privada',
    'Connecter sur le réseau privé',
    'निजी नेटवर्क पर जोड़ें',
    'Im privaten Netzwerk verbinden',
  ],
  'HTTP is limited to a numeric private-network address, but your Jellyfin password and video traffic are not encrypted. Use HTTPS when your server supports it.': [
    'HTTP se limita a una dirección numérica de red privada, pero tu contraseña de Jellyfin y el video no se cifran. Usa HTTPS si tu servidor lo permite.',
    'HTTP é limitado a um endereço numérico de rede privada, mas a senha do Jellyfin e o vídeo não são criptografados. Use HTTPS se o servidor permitir.',
    'HTTP est limité à une adresse numérique de réseau privé, mais votre mot de passe Jellyfin et la vidéo ne sont pas chiffrés. Utilisez HTTPS si possible.',
    'HTTP केवल निजी नेटवर्क के संख्यात्मक पते तक सीमित है, लेकिन Jellyfin पासवर्ड और वीडियो एन्क्रिप्ट नहीं होते। सर्वर समर्थन करे तो HTTPS इस्तेमाल करें।',
    'HTTP ist auf numerische Adressen privater Netzwerke begrenzt. Jellyfin-Passwort und Videodaten sind jedoch unverschlüsselt. Nutze HTTPS, wenn der Server es unterstützt.',
  ],
  'HTTP is limited to a numeric private-network address, but your Plex access token and video traffic are not encrypted. Use HTTPS when your server supports it.': [
    'HTTP se limita a una dirección numérica de red privada, pero tu token Plex y el video no se cifran. Usa HTTPS si tu servidor lo permite.',
    'HTTP é limitado a um endereço numérico de rede privada, mas o token Plex e o vídeo não são criptografados. Use HTTPS se o servidor permitir.',
    'HTTP est limité à une adresse numérique de réseau privé, mais votre jeton Plex et la vidéo ne sont pas chiffrés. Utilisez HTTPS si possible.',
    'HTTP केवल निजी नेटवर्क के संख्यात्मक पते तक सीमित है, लेकिन Plex टोकन और वीडियो एन्क्रिप्ट नहीं होते। सर्वर समर्थन करे तो HTTPS इस्तेमाल करें।',
    'HTTP ist auf numerische Adressen privater Netzwerke begrenzt. Plex-Token und Videodaten sind jedoch unverschlüsselt. Nutze HTTPS, wenn der Server es unterstützt.',
  ],
  'Load more ({value1} of {value2})': [
    'Cargar más ({value1} de {value2})',
    'Carregar mais ({value1} de {value2})',
    'Charger plus ({value1} sur {value2})',
    'और लोड करें ({value2} में से {value1})',
    'Mehr laden ({value1} von {value2})',
  ],
  '{value1} library items are available to episode matching.': [
    'Hay {value1} elementos de biblioteca disponibles para buscar episodios.',
    '{value1} itens da biblioteca estão disponíveis para buscar episódios.',
    '{value1} éléments de bibliothèque sont disponibles pour la recherche d’épisodes.',
    'एपिसोड मिलान के लिए लाइब्रेरी में {value1} आइटम उपलब्ध हैं।',
    '{value1} Bibliothekseinträge stehen für den Folgenabgleich bereit.',
  ],
  'SEARCH YOUR MEDIA': [
    'BUSCAR EN TU CONTENIDO',
    'PESQUISAR SUA MÍDIA',
    'RECHERCHER VOS MÉDIAS',
    'अपना मीडिया खोजें',
    'DEINE MEDIEN DURCHSUCHEN',
  ],
  'Search your media libraries': [
    'Buscar en tus bibliotecas',
    'Pesquisar nas suas bibliotecas',
    'Rechercher dans vos bibliothèques',
    'अपनी मीडिया लाइब्रेरी खोजें',
    'Deine Medienbibliotheken durchsuchen',
  ],
  'Title or keyword': [
    'Título o palabra clave',
    'Título ou palavra-chave',
    'Titre ou mot-clé',
    'शीर्षक या मुख्य शब्द',
    'Titel oder Suchwort',
  ],
  'Search connected Jellyfin and Plex libraries together. Your recently selected device video is included when its name matches.': [
    'Busca a la vez en las bibliotecas Jellyfin y Plex conectadas. También se incluye el video local elegido recientemente si coincide su nombre.',
    'Pesquise nas bibliotecas Jellyfin e Plex conectadas ao mesmo tempo. O vídeo local selecionado recentemente é incluído se o nome corresponder.',
    'Recherchez ensemble dans vos bibliothèques Jellyfin et Plex connectées. La vidéo locale récemment sélectionnée est incluse si son nom correspond.',
    'जुड़ी हुई Jellyfin और Plex लाइब्रेरी में एक साथ खोजें। हाल में चुना गया स्थानीय वीडियो भी नाम मिलने पर शामिल होगा।',
    'Durchsuche verbundene Jellyfin- und Plex-Bibliotheken gemeinsam. Das zuletzt ausgewählte lokale Video wird bei passendem Namen einbezogen.',
  ],
  'Movies': ['Películas', 'Filmes', 'Films', 'फ़िल्में', 'Filme'],
  'TV shows': ['Series', 'Séries', 'Séries', 'टीवी शो', 'Serien'],
  'Private media could not be prepared safely.': [
    'No se pudo preparar el contenido privado de forma segura.',
    'Não foi possível preparar a mídia privada com segurança.',
    'Impossible de préparer ce média privé de façon sécurisée.',
    'निजी मीडिया सुरक्षित रूप से तैयार नहीं हो सका।',
    'Private Medien konnten nicht sicher vorbereitet werden.',
  ],
  'This library video could not be opened.': [
    'No se pudo abrir este video de la biblioteca.',
    'Não foi possível abrir este vídeo da biblioteca.',
    'Impossible d’ouvrir cette vidéo de bibliothèque.',
    'यह लाइब्रेरी वीडियो नहीं खुल सका।',
    'Dieses Bibliotheksvideo konnte nicht geöffnet werden.',
  ],
  'This library video could not be played by the selected engine.': [
    'El reproductor elegido no pudo reproducir este video de biblioteca.',
    'O reprodutor selecionado não conseguiu reproduzir este vídeo da biblioteca.',
    'Le lecteur sélectionné n’a pas pu lire cette vidéo de bibliothèque.',
    'चुना गया प्लेयर यह लाइब्रेरी वीडियो नहीं चला सका।',
    'Der gewählte Player konnte dieses Bibliotheksvideo nicht abspielen.',
  ],
  'Watch Party': [
    'Watch Party',
    'Watch Party',
    'Watch Party',
    'Watch Party',
    'Watch Party',
  ],
  'Start Watch Party': [
    'Iniciar Watch Party',
    'Iniciar Watch Party',
    'Démarrer Watch Party',
    'Watch Party शुरू करें',
    'Watch Party starten',
  ],
  'Watch Party room': [
    'Sala Watch Party',
    'Sala Watch Party',
    'Salon Watch Party',
    'Watch Party कमरा',
    'Watch-Party-Raum',
  ],
  'Creating a private room…': [
    'Creando una sala privada…',
    'Criando uma sala privada…',
    'Création d’un salon privé…',
    'निजी कमरा बन रहा है…',
    'Privater Raum wird erstellt…',
  ],
  'Playback keeps running. Closing this panel does not end the room.': [
    'La reproducción continúa. Cerrar este panel no termina la sala.',
    'A reprodução continua. Fechar este painel não encerra a sala.',
    'La lecture continue. Fermer ce panneau ne ferme pas le salon.',
    'प्लेबैक चलता रहेगा। यह पैनल बंद करने से कमरा बंद नहीं होगा।',
    'Die Wiedergabe läuft weiter. Dieses Fenster zu schließen beendet den Raum nicht.',
  ],
  'The host controls playback. Open Watch Party or Exit.': [
    'El anfitrión controla la reproducción. Abre Watch Party o sal.',
    'O anfitrião controla a reprodução. Abra Watch Party ou saia.',
    'L’hôte contrôle la lecture. Ouvrez Watch Party ou quittez.',
    'होस्ट प्लेबैक नियंत्रित करता है। Watch Party खोलें या बाहर जाएँ।',
    'Der Gastgeber steuert die Wiedergabe. Öffne Watch Party oder verlasse das Video.',
  ],
  'Room timing, public show identity, and a privacy-preserving source hint are synchronized. Stream URLs, tokens, headers, and video data stay on each viewer’s device.': [
    'Se sincronizan el tiempo de la sala, la identidad pública de la serie y una referencia privada de la fuente. Las URL, tokens, cabeceras y videos permanecen en el dispositivo de cada persona.',
    'São sincronizados o tempo da sala, a identificação pública da série e uma referência de fonte que preserva a privacidade. URLs, tokens, cabeçalhos e vídeos ficam no dispositivo de cada pessoa.',
    'Le temps du salon, l’identité publique de la série et un indice de source respectueux de la vie privée sont synchronisés. URL, jetons, en-têtes et vidéos restent sur chaque appareil.',
    'कमरे का समय, शो की सार्वजनिक पहचान और गोपनीयता सुरक्षित रखने वाला स्रोत संकेत सिंक होते हैं। स्ट्रीम URL, टोकन, हेडर और वीडियो हर दर्शक के डिवाइस पर रहते हैं।',
    'Raumzeit, öffentliche Serienkennung und ein datenschutzfreundlicher Quellenhinweis werden synchronisiert. Stream-URLs, Tokens, Header und Videodaten bleiben auf jedem Gerät.',
  ],
  'Resync party': [
    'Resincronizar sala',
    'Ressincronizar sala',
    'Resynchroniser le salon',
    'पार्टी फिर सिंक करें',
    'Raum neu synchronisieren',
  ],
  'Resyncing…': [
    'Resincronizando…',
    'Ressincronizando…',
    'Resynchronisation…',
    'फिर सिंक हो रहा है…',
    'Wird neu synchronisiert…',
  ],
  'Reset sync': [
    'Restablecer sincronización',
    'Redefinir sincronização',
    'Réinitialiser la synchronisation',
    'सिंक रीसेट करें',
    'Synchronisierung zurücksetzen',
  ],
  '5s earlier': [
    '5 s antes',
    '5 s antes',
    '5 s plus tôt',
    '5 सेकंड पहले',
    '5 s früher',
  ],
  '5s later': [
    '5 s después',
    '5 s depois',
    '5 s plus tard',
    '5 सेकंड बाद',
    '5 s später',
  ],
  'Copy code': [
    'Copiar código',
    'Copiar código',
    'Copier le code',
    'कोड कॉपी करें',
    'Code kopieren',
  ],
  'Share this room code to invite someone from TetoTV or the Watch Party website.': [
    'Comparte este código para invitar a alguien desde TetoTV o la web de Watch Party.',
    'Compartilhe este código para convidar alguém pelo TetoTV ou pelo site Watch Party.',
    'Partagez ce code pour inviter quelqu’un depuis TetoTV ou le site Watch Party.',
    'TetoTV या Watch Party वेबसाइट से किसी को बुलाने के लिए यह कमरे का कोड साझा करें।',
    'Teile diesen Raumcode, um jemanden über TetoTV oder die Watch-Party-Website einzuladen.',
  ],
  'Participant profiles will appear here as people join.': [
    'Los perfiles aparecerán aquí cuando se unan participantes.',
    'Os perfis aparecerão aqui conforme as pessoas entrarem.',
    'Les profils apparaîtront ici lorsque des participants rejoindront le salon.',
    'लोगों के जुड़ने पर उनकी प्रोफ़ाइल यहाँ दिखेंगी।',
    'Profile erscheinen hier, sobald Personen beitreten.',
  ],
  'Manage {value1}': [
    'Gestionar a {value1}',
    'Gerenciar {value1}',
    'Gérer {value1}',
    '{value1} प्रबंधित करें',
    '{value1} verwalten',
  ],
  'Make host': [
    'Hacer anfitrión',
    'Tornar anfitrião',
    'Nommer hôte',
    'होस्ट बनाएँ',
    'Zum Gastgeber machen',
  ],
  'Transfer makes this person the only playback host. Remove disconnects them from this room.': [
    'La transferencia convierte a esta persona en el único anfitrión de reproducción. Quitar la desconecta de esta sala.',
    'Transferir torna esta pessoa o único anfitrião da reprodução. Remover a desconecta desta sala.',
    'Le transfert fait de cette personne l’unique hôte de lecture. Retirer la déconnecte du salon.',
    'स्थानांतरण से यह व्यक्ति प्लेबैक का एकमात्र होस्ट बन जाएगा। हटाने से वह इस कमरे से डिस्कनेक्ट हो जाएगा।',
    'Die Übertragung macht diese Person zum einzigen Wiedergabe-Gastgeber. Entfernen trennt sie von diesem Raum.',
  ],
  'Leaving…': [
    'Saliendo…',
    'Saindo…',
    'Déconnexion…',
    'बाहर निकल रहे हैं…',
    'Raum wird verlassen…',
  ],
  'Leave room': [
    'Salir de la sala',
    'Sair da sala',
    'Quitter le salon',
    'कमरा छोड़ें',
    'Raum verlassen',
  ],
  'Leave this room?': [
    '¿Salir de esta sala?',
    'Sair desta sala?',
    'Quitter ce salon ?',
    'यह कमरा छोड़ें?',
    'Diesen Raum verlassen?',
  ],
  'End room': [
    'Terminar sala',
    'Encerrar sala',
    'Fermer le salon',
    'कमरा समाप्त करें',
    'Raum beenden',
  ],
  'End Watch Party room?': [
    '¿Terminar la sala Watch Party?',
    'Encerrar a sala Watch Party?',
    'Fermer le salon Watch Party ?',
    'Watch Party कमरा समाप्त करें?',
    'Watch-Party-Raum beenden?',
  ],
  'This ends the room for every participant. Playback on your device keeps running.': [
    'Esto termina la sala para todos los participantes. La reproducción en tu dispositivo continúa.',
    'Isso encerra a sala para todos. A reprodução no seu dispositivo continua.',
    'Cela ferme le salon pour tous les participants. La lecture continue sur votre appareil.',
    'इससे सभी प्रतिभागियों के लिए कमरा समाप्त होगा। आपके डिवाइस पर प्लेबैक चलता रहेगा।',
    'Dies beendet den Raum für alle Teilnehmer. Die Wiedergabe auf deinem Gerät läuft weiter.',
  ],
  'You will stop following the host. Playback on your device keeps running.': [
    'Dejarás de seguir al anfitrión. La reproducción en tu dispositivo continúa.',
    'Você deixará de seguir o anfitrião. A reprodução no seu dispositivo continua.',
    'Vous cesserez de suivre l’hôte. La lecture continue sur votre appareil.',
    'आप होस्ट का अनुसरण बंद कर देंगे। आपके डिवाइस पर प्लेबैक चलता रहेगा।',
    'Du folgst dem Gastgeber nicht mehr. Die Wiedergabe auf deinem Gerät läuft weiter.',
  ],
  'Filler data is unavailable. Playing Episode {value1} normally.': [
    'Los datos de relleno no están disponibles. Se reproducirá el episodio {value1} normalmente.',
    'Os dados de filler estão indisponíveis. O episódio {value1} será reproduzido normalmente.',
    'Les données de fillers sont indisponibles. Lecture normale de l’épisode {value1}.',
    'फ़िलर डेटा उपलब्ध नहीं है। एपिसोड {value1} सामान्य रूप से चलेगा।',
    'Filler-Daten sind nicht verfügbar. Folge {value1} wird normal abgespielt.',
  ],
};

final playbackTranslations = <String, Map<String, String>>{
  for (final (index, locale) in const ['es', 'pt', 'fr', 'hi', 'de'].indexed)
    locale: {
      for (final entry in playbackTranslationRows.entries)
        entry.key: entry.value[index],
    },
};

const _playbackStatusTranslations = <String, List<String>>{
  '192.168.1.20:32400 or https://plex.example.com': [
    '192.168.1.20:32400 o https://plex.example.com',
    '192.168.1.20:32400 ou https://plex.example.com',
    '192.168.1.20:32400 ou https://plex.example.com',
    '192.168.1.20:32400 या https://plex.example.com',
    '192.168.1.20:32400 oder https://plex.example.com',
  ],
  '192.168.1.20:8096 or https://jellyfin.example.com': [
    '192.168.1.20:8096 o https://jellyfin.example.com',
    '192.168.1.20:8096 ou https://jellyfin.example.com',
    '192.168.1.20:8096 ou https://jellyfin.example.com',
    '192.168.1.20:8096 या https://jellyfin.example.com',
    '192.168.1.20:8096 oder https://jellyfin.example.com',
  ],
  '{source}\n\n{details}\n\nThe episode will appear in Download Manager and, once finished, as the first source for this episode.': [
    '{source}\n\n{details}\n\nEl episodio aparecerá en el gestor de descargas y, al terminar, como primera fuente de este episodio.',
    '{source}\n\n{details}\n\nO episódio aparecerá no gerenciador de downloads e, ao terminar, como primeira fonte deste episódio.',
    '{source}\n\n{details}\n\nL’épisode apparaîtra dans les téléchargements puis, une fois terminé, comme première source de cet épisode.',
    '{source}\n\n{details}\n\nएपिसोड डाउनलोड प्रबंधक में दिखेगा और पूरा होने पर इस एपिसोड के पहले स्रोत के रूप में दिखाई देगा।',
    '{source}\n\n{details}\n\nDie Folge erscheint im Downloadmanager und nach Abschluss als erste Quelle dieser Folge.',
  ],
  'Your Debrid service could not prepare this release.': [
    'Tu servicio Debrid no pudo preparar esta versión.',
    'Seu serviço Debrid não preparou esta versão.',
    'Votre service Debrid n’a pas pu préparer cette version.',
    'आपकी Debrid सेवा यह रिलीज़ तैयार नहीं कर सकी।',
    'Dein Debrid-Dienst konnte diese Veröffentlichung nicht vorbereiten.',
  ],
  'A direct torrent download makes your public IP address visible to peers and trackers and may upload data while the download runs. Only continue for content you are legally allowed to access.': [
    'Una descarga torrent directa expone tu dirección IP pública a pares y rastreadores y puede subir datos durante la descarga. Continúa solo con contenido al que tengas derecho legal de acceder.',
    'Um download torrent direto expõe seu IP público a pares e rastreadores e pode enviar dados durante o download. Continue apenas com conteúdo que você tem direito legal de acessar.',
    'Un téléchargement torrent direct rend votre IP publique visible aux pairs et trackers et peut envoyer des données pendant le téléchargement. Continuez uniquement pour du contenu auquel vous avez légalement accès.',
    'सीधा टॉरेंट डाउनलोड आपका सार्वजनिक IP पता पीयर और ट्रैकर को दिखाता है और डाउनलोड के दौरान डेटा अपलोड भी कर सकता है। केवल कानूनी रूप से अधिकृत सामग्री के लिए आगे बढ़ें।',
    'Ein direkter Torrent-Download macht deine öffentliche IP-Adresse für Peers und Tracker sichtbar und kann Daten hochladen. Fahre nur bei Inhalten fort, auf die du rechtmäßig zugreifen darfst.',
  ],
  'TetoTV could not search {servers}. Check the connection in Media sources and try again.': [
    'TetoTV no pudo buscar en {servers}. Comprueba la conexión en Fuentes multimedia e inténtalo de nuevo.',
    'O TetoTV não conseguiu pesquisar em {servers}. Verifique a conexão em Fontes de mídia e tente novamente.',
    'TetoTV n’a pas pu rechercher dans {servers}. Vérifiez la connexion dans Sources multimédias et réessayez.',
    'TetoTV {servers} में खोज नहीं सका। मीडिया स्रोत में कनेक्शन जाँचें और फिर कोशिश करें।',
    'TetoTV konnte {servers} nicht durchsuchen. Prüfe die Verbindung unter Medienquellen und versuche es erneut.',
  ],
  'The host changed episodes, but TetoTV could not choose a playable source automatically. Choose a source manually or retry; you remain in the Watch Party.': [
    'El anfitrión cambió de episodio, pero TetoTV no pudo elegir una fuente automáticamente. Elige una fuente o reintenta; sigues en Watch Party.',
    'O anfitrião mudou de episódio, mas o TetoTV não escolheu uma fonte automaticamente. Escolha uma fonte ou tente novamente; você continua na Watch Party.',
    'L’hôte a changé d’épisode, mais TetoTV n’a pas trouvé de source lisible automatiquement. Choisissez une source ou réessayez ; vous restez dans Watch Party.',
    'होस्ट ने एपिसोड बदला, लेकिन TetoTV अपने आप चलाने योग्य स्रोत नहीं चुन सका। स्रोत खुद चुनें या फिर कोशिश करें; आप Watch Party में बने हुए हैं।',
    'Der Gastgeber hat die Folge gewechselt, aber TetoTV fand automatisch keine abspielbare Quelle. Wähle eine Quelle oder versuche es erneut; du bleibst in der Watch Party.',
  ],
  'Automatic playback checked every available source. Try the search again or go back to the episode page.': [
    'La reproducción automática comprobó todas las fuentes disponibles. Repite la búsqueda o vuelve a la página del episodio.',
    'A reprodução automática verificou todas as fontes. Pesquise novamente ou volte à página do episódio.',
    'La lecture automatique a vérifié toutes les sources disponibles. Relancez la recherche ou revenez à la page de l’épisode.',
    'अपने आप चलाने के लिए सभी उपलब्ध स्रोत जाँचे गए। फिर खोजें या एपिसोड पेज पर वापस जाएँ।',
    'Die automatische Wiedergabe hat alle verfügbaren Quellen geprüft. Suche erneut oder gehe zur Folgenseite zurück.',
  ],
  'TetoTV checked the connected Jellyfin/Plex libraries using the catalog title aliases and exact episode number. Check Media sources in Settings if the library name needs attention.': [
    'TetoTV buscó en las bibliotecas Jellyfin/Plex conectadas con los títulos alternativos del catálogo y el número exacto de episodio. Revisa Fuentes multimedia en Ajustes si el nombre necesita cambios.',
    'O TetoTV verificou as bibliotecas Jellyfin/Plex usando os nomes alternativos do catálogo e o número exato do episódio. Confira Fontes de mídia nas configurações se o nome precisar de atenção.',
    'TetoTV a vérifié les bibliothèques Jellyfin/Plex avec les titres alternatifs du catalogue et le numéro exact de l’épisode. Vérifiez Sources multimédias dans les paramètres si le nom est incorrect.',
    'TetoTV ने वैकल्पिक कैटलॉग शीर्षकों और सही एपिसोड नंबर से जुड़ी Jellyfin/Plex लाइब्रेरी जाँचीं। नाम सही करना हो तो सेटिंग में मीडिया स्रोत देखें।',
    'TetoTV hat verbundene Jellyfin-/Plex-Bibliotheken mit alternativen Katalogtiteln und genauer Folgennummer geprüft. Prüfe Medienquellen in den Einstellungen, falls der Name angepasst werden muss.',
  ],
  'Direct torrent playback is unavailable on this device or CPU. Connect a supported debrid service instead.': [
    'La reproducción torrent directa no está disponible en este dispositivo o CPU. Conecta un servicio debrid compatible.',
    'Torrent direto não está disponível neste dispositivo ou CPU. Conecte um serviço debrid compatível.',
    'La lecture torrent directe n’est pas disponible sur cet appareil ou processeur. Connectez un service debrid compatible.',
    'इस डिवाइस या CPU पर सीधा टॉरेंट प्लेबैक उपलब्ध नहीं है। कोई समर्थित debrid सेवा जोड़ें।',
    'Direkte Torrent-Wiedergabe ist auf diesem Gerät oder Prozessor nicht verfügbar. Verbinde einen unterstützten Debrid-Dienst.',
  ],
  'Connect a supported debrid service, or install a compatible Web Stream provider from Marketplace.': [
    'Conecta un servicio debrid compatible o instala un proveedor web compatible desde Marketplace.',
    'Conecte um serviço debrid compatível ou instale um provedor web compatível pelo Marketplace.',
    'Connectez un service debrid compatible ou installez un fournisseur web compatible depuis Marketplace.',
    'समर्थित debrid सेवा जोड़ें या Marketplace से समर्थित वेब स्ट्रीम प्रदाता इंस्टॉल करें।',
    'Verbinde einen unterstützten Debrid-Dienst oder installiere einen kompatiblen Webanbieter aus dem Marketplace.',
  ],
  'Connect a supported debrid service, or explicitly enable Direct torrent in Streaming sources. Direct peer playback is off by default and shows a privacy warning before it is enabled.': [
    'Conecta un servicio debrid compatible o activa Torrent directo en Fuentes de streaming. La reproducción por pares está desactivada de forma predeterminada y muestra un aviso de privacidad antes de activarse.',
    'Conecte um serviço debrid compatível ou ative Torrent direto em Fontes de streaming. Reprodução por pares vem desativada e mostra um aviso de privacidade antes de ser ativada.',
    'Connectez un service debrid compatible ou activez Torrent direct dans les sources de streaming. La lecture par pairs est désactivée par défaut et affiche un avertissement de confidentialité avant activation.',
    'समर्थित debrid सेवा जोड़ें या स्ट्रीमिंग स्रोत में सीधा टॉरेंट चालू करें। सीधा पीयर प्लेबैक डिफ़ॉल्ट रूप से बंद है और चालू करने से पहले गोपनीयता चेतावनी दिखाता है।',
    'Verbinde einen unterstützten Debrid-Dienst oder aktiviere Direkter Torrent unter Streamingquellen. Direkte Peer-Wiedergabe ist standardmäßig aus und zeigt vor der Aktivierung einen Datenschutzhinweis.',
  ],
  'Preparing Watch Party…': [
    'Preparando Watch Party…',
    'Preparando Watch Party…',
    'Préparation de Watch Party…',
    'Watch Party तैयार हो रहा है…',
    'Watch Party wird vorbereitet…',
  ],
  '{count} person watching': [
    '{count} persona viendo',
    '{count} pessoa assistindo',
    '{count} personne regarde',
    '{count} व्यक्ति देख रहा है',
    '{count} Person schaut zu',
  ],
  '{count} people watching': [
    '{count} personas viendo',
    '{count} pessoas assistindo',
    '{count} personnes regardent',
    '{count} लोग देख रहे हैं',
    '{count} Personen schauen zu',
  ],
  '{count} guest ready': [
    '{count} invitado listo',
    '{count} convidado pronto',
    '{count} invité prêt',
    '{count} मेहमान तैयार है',
    '{count} Gast bereit',
  ],
  '{count} guests ready': [
    '{count} invitados listos',
    '{count} convidados prontos',
    '{count} invités prêts',
    '{count} मेहमान तैयार हैं',
    '{count} Gäste bereit',
  ],
  '{timeline} • local adjustment {offset}s': [
    '{timeline} • ajuste local {offset} s',
    '{timeline} • ajuste local {offset} s',
    '{timeline} • réglage local {offset} s',
    '{timeline} • स्थानीय समायोजन {offset} सेकंड',
    '{timeline} • lokale Anpassung {offset} s',
  ],
  'joined the party': [
    'se unió a la sala',
    'entrou na sala',
    'a rejoint le salon',
    'पार्टी में शामिल हुए',
    'ist dem Raum beigetreten',
  ],
  'left the party': [
    'salió de la sala',
    'saiu da sala',
    'a quitté le salon',
    'पार्टी छोड़ दी',
    'hat den Raum verlassen',
  ],
  'was kicked from the party': [
    'fue expulsado de la sala',
    'foi removido da sala',
    'a été exclu du salon',
    'पार्टी से हटाए गए',
    'wurde aus dem Raum entfernt',
  ],
  'is now the host': [
    'ahora es el anfitrión',
    'agora é o anfitrião',
    'est maintenant l’hôte',
    'अब होस्ट हैं',
    'ist jetzt Gastgeber',
  ],
  'Host timeline • everyone follows this player': [
    'Tiempo del anfitrión • todos siguen este reproductor',
    'Tempo do anfitrião • todos seguem este reprodutor',
    'Temps de l’hôte • tout le monde suit ce lecteur',
    'होस्ट का समय • सभी इस प्लेयर का अनुसरण करते हैं',
    'Gastgeber-Zeit • alle folgen diesem Player',
  ],
  'Exact source • scene timing verified': [
    'Misma fuente • tiempo de escenas verificado',
    'Mesma fonte • tempo das cenas verificado',
    'Même source • minutage des scènes vérifié',
    'सटीक स्रोत • दृश्य का समय सत्यापित',
    'Identische Quelle • Szenenzeiten geprüft',
  ],
  'Different source • matching timeline': [
    'Otra fuente • tiempos coincidentes',
    'Outra fonte • tempos correspondentes',
    'Source différente • minutage correspondant',
    'अलग स्रोत • समय मेल खाता है',
    'Andere Quelle • passende Zeitlinie',
  ],
  'Different source • intro/outro timing aligned': [
    'Otra fuente • introducción y final sincronizados',
    'Outra fonte • abertura e encerramento alinhados',
    'Source différente • génériques alignés',
    'अलग स्रोत • इंट्रो और आउट्रो का समय मिला हुआ',
    'Andere Quelle • Intro-/Outro-Zeiten angepasst',
  ],
  'Different cut • use the sync adjustment if scenes do not match': [
    'Otro montaje • ajusta la sincronización si las escenas no coinciden',
    'Outra edição • ajuste a sincronização se as cenas não corresponderem',
    'Montage différent • ajustez la synchronisation si les scènes diffèrent',
    'अलग कट • दृश्य न मिलें तो सिंक समायोजित करें',
    'Andere Fassung • Synchronisierung anpassen, falls Szenen abweichen',
  ],
  'Verifying this episode and source': [
    'Verificando este episodio y fuente',
    'Verificando este episódio e fonte',
    'Vérification de cet épisode et de sa source',
    'इस एपिसोड और स्रोत की जाँच हो रही है',
    'Folge und Quelle werden geprüft',
  ],
  'Watch Party is not active': [
    'Watch Party no está activa',
    'Watch Party não está ativa',
    'Watch Party n’est pas active',
    'Watch Party सक्रिय नहीं है',
    'Watch Party ist nicht aktiv',
  ],
  'Skipped filler {episodes}. Playing Episode {next}.': [
    'Se omitió el relleno {episodes}. Reproduciendo el episodio {next}.',
    'Filler {episodes} pulado. Reproduzindo o episódio {next}.',
    'Fillers {episodes} passés. Lecture de l’épisode {next}.',
    'फ़िलर {episodes} छोड़ दिए। एपिसोड {next} चल रहा है।',
    'Filler {episodes} übersprungen. Folge {next} wird abgespielt.',
  ],
  '{episodes} is marked as filler. There are no later non-filler episodes available.': [
    '{episodes} está marcado como relleno. No hay episodios posteriores sin relleno disponibles.',
    '{episodes} está marcado como filler. Não há episódios posteriores sem filler disponíveis.',
    '{episodes} est marqué comme filler. Aucun épisode suivant hors filler n’est disponible.',
    '{episodes} फ़िलर के रूप में चिह्नित है। इसके बाद कोई गैर-फ़िलर एपिसोड उपलब्ध नहीं है।',
    '{episodes} ist als Filler markiert. Keine späteren Folgen ohne Filler verfügbar.',
  ],
  '{episodes} are marked as filler. There are no later non-filler episodes available.': [
    '{episodes} están marcados como relleno. No hay episodios posteriores sin relleno disponibles.',
    '{episodes} estão marcados como filler. Não há episódios posteriores sem filler disponíveis.',
    '{episodes} sont marqués comme fillers. Aucun épisode suivant hors filler n’est disponible.',
    '{episodes} फ़िलर के रूप में चिह्नित हैं। इनके बाद कोई गैर-फ़िलर एपिसोड उपलब्ध नहीं है।',
    '{episodes} sind als Filler markiert. Keine späteren Folgen ohne Filler verfügbar.',
  ],
  'Web discovery is disabled': [
    'La búsqueda web está desactivada',
    'A busca web está desativada',
    'La recherche web est désactivée',
    'वेब खोज बंद है',
    'Websuche ist deaktiviert',
  ],
  'Searching providers: {done}/{total}': [
    'Buscando proveedores: {done}/{total}',
    'Pesquisando provedores: {done}/{total}',
    'Recherche des fournisseurs : {done}/{total}',
    'प्रदाता खोजे जा रहे हैं: {done}/{total}',
    'Anbieter werden durchsucht: {done}/{total}',
  ],
  'Finding providers...': [
    'Buscando proveedores...',
    'Encontrando provedores...',
    'Recherche des fournisseurs...',
    'प्रदाता ढूँढे जा रहे हैं...',
    'Anbieter werden gesucht...',
  ],
  '{count} source': [
    '{count} fuente',
    '{count} fonte',
    '{count} source',
    '{count} स्रोत',
    '{count} Quelle',
  ],
  '{count} sources': [
    '{count} fuentes',
    '{count} fontes',
    '{count} sources',
    '{count} स्रोत',
    '{count} Quellen',
  ],
  '{count} unavailable': [
    '{count} no disponibles',
    '{count} indisponíveis',
    '{count} indisponibles',
    '{count} अनुपलब्ध',
    '{count} nicht verfügbar',
  ],
  '{count} paused': [
    '{count} en pausa',
    '{count} pausados',
    '{count} en pause',
    '{count} रुके हुए',
    '{count} pausiert',
  ],
  '{count} no match': [
    '{count} sin coincidencia',
    '{count} sem correspondência',
    '{count} sans résultat',
    '{count} का मिलान नहीं',
    '{count} ohne Treffer',
  ],
  '{count} notice': [
    '{count} avisos',
    '{count} avisos',
    '{count} avis',
    '{count} सूचनाएँ',
    '{count} Hinweise',
  ],
  'Web {done}/{total} background': [
    'Web {done}/{total} en segundo plano',
    'Web {done}/{total} em segundo plano',
    'Web {done}/{total} en arrière-plan',
    'वेब {done}/{total} पृष्ठभूमि में',
    'Web {done}/{total} im Hintergrund',
  ],
  'Web {done}/{total}': [
    'Web {done}/{total}',
    'Web {done}/{total}',
    'Web {done}/{total}',
    'वेब {done}/{total}',
    'Web {done}/{total}',
  ],
  'Local sources ready': [
    'Fuentes locales listas',
    'Fontes locais prontas',
    'Sources locales prêtes',
    'स्थानीय स्रोत तैयार हैं',
    'Lokale Quellen bereit',
  ],
  'Local sources': [
    'Fuentes locales',
    'Fontes locais',
    'Sources locales',
    'स्थानीय स्रोत',
    'Lokale Quellen',
  ],
  'Still checking {providers}': [
    'Comprobando todavía {providers}',
    'Ainda verificando {providers}',
    'Vérification toujours en cours : {providers}',
    '{providers} अभी जाँचे जा रहे हैं',
    '{providers} werden noch geprüft',
  ],
  'Waiting for {providers}': [
    'Esperando a {providers}',
    'Aguardando {providers}',
    'En attente de {providers}',
    '{providers} की प्रतीक्षा है',
    'Warten auf {providers}',
  ],
  'Starting providers': [
    'Iniciando proveedores',
    'Iniciando provedores',
    'Démarrage des fournisseurs',
    'प्रदाता शुरू हो रहे हैं',
    'Anbieter werden gestartet',
  ],
  'Retrying failed Web providers': [
    'Reintentando proveedores web fallidos',
    'Tentando provedores web com falha novamente',
    'Nouvel essai des fournisseurs web en échec',
    'विफल वेब प्रदाता फिर आज़माए जा रहे हैं',
    'Fehlgeschlagene Webanbieter werden erneut versucht',
  ],
  'no match': [
    'sin coincidencia',
    'sem correspondência',
    'aucun résultat',
    'मिलान नहीं',
    'kein Treffer',
  ],
  'repository warning': [
    'aviso del repositorio',
    'aviso do repositório',
    'avertissement du dépôt',
    'रिपॉज़िटरी चेतावनी',
    'Repository-Warnung',
  ],
  'unavailable': [
    'no disponible',
    'indisponível',
    'indisponible',
    'अनुपलब्ध',
    'nicht verfügbar',
  ],
  'paused': ['en pausa', 'pausado', 'en pause', 'रुका हुआ', 'pausiert'],
  'error': ['error', 'erro', 'erreur', 'त्रुटि', 'Fehler'],
  '+{count} more': [
    '+{count} más',
    '+{count} mais',
    '+{count} autres',
    '+{count} और',
    '+{count} weitere',
  ],
  '{count} Direct torrent': [
    '{count} Torrent directo',
    '{count} Torrent direto',
    '{count} Torrent direct',
    '{count} सीधे टॉरेंट',
    '{count} Direkte Torrents',
  ],
  'Torrent releases off': [
    'Torrents desactivados',
    'Torrents desativados',
    'Torrents désactivés',
    'टॉरेंट रिलीज़ बंद',
    'Torrent-Veröffentlichungen aus',
  ],
  'Web off': [
    'Web desactivado',
    'Web desativado',
    'Web désactivé',
    'वेब बंद',
    'Web aus',
  ],
  '{count} Local': [
    '{count} Locales',
    '{count} Locais',
    '{count} Locaux',
    '{count} स्थानीय',
    '{count} Lokal',
  ],
  '1 Offline': [
    '1 Sin conexión',
    '1 Offline',
    '1 Hors ligne',
    '1 ऑफ़लाइन',
    '1 Offline',
  ],
  '{count} issue(s)': [
    '{count} problema(s)',
    '{count} problema(s)',
    '{count} problème(s)',
    '{count} समस्याएँ',
    '{count} Problem(e)',
  ],
  '{count} notice(s)': [
    '{count} aviso(s)',
    '{count} aviso(s)',
    '{count} avis',
    '{count} सूचनाएँ',
    '{count} Hinweis(e)',
  ],
  'Disable captions': [
    'Desactivar subtítulos',
    'Desativar legendas',
    'Désactiver les sous-titres',
    'उपशीर्षक बंद करें',
    'Untertitel deaktivieren',
  ],
  'Picture: Fill screen': [
    'Imagen: llenar pantalla',
    'Imagem: preencher tela',
    'Image : remplir l’écran',
    'चित्र: स्क्रीन भरें',
    'Bild: Bildschirm füllen',
  ],
  'Picture: Stretch': [
    'Imagen: estirar',
    'Imagem: esticar',
    'Image : étirer',
    'चित्र: खींचें',
    'Bild: Strecken',
  ],
  'Picture: Fit': [
    'Imagen: ajustar',
    'Imagem: ajustar',
    'Image : adapter',
    'चित्र: फ़िट करें',
    'Bild: Einpassen',
  ],
  'D-pad controls  |  J/L seek  |  Menu/Y options': [
    'Cruceta: controles  |  J/L: buscar  |  Menu/Y: opciones',
    'Direcional: controles  |  J/L: avançar  |  Menu/Y: opções',
    'Flèches : commandes  |  J/L : déplacement  |  Menu/Y : options',
    'दिशा बटन: नियंत्रण  |  J/L: आगे-पीछे  |  Menu/Y: विकल्प',
    'Steuerkreuz: Steuerung  |  J/L: Spulen  |  Menu/Y: Optionen',
  ],
  'Automatic (adaptive)': [
    'Automático (adaptativo)',
    'Automático (adaptável)',
    'Automatique (adaptatif)',
    'अपने आप (अनुकूल)',
    'Automatisch (adaptiv)',
  ],
  'Hardware direct': [
    'Hardware directo',
    'Hardware direto',
    'Matériel direct',
    'सीधा हार्डवेयर',
    'Direkte Hardware',
  ],
  'Software compatibility': [
    'Compatibilidad por software',
    'Compatibilidade por software',
    'Compatibilité logicielle',
    'सॉफ़्टवेयर संगतता',
    'Software-Kompatibilität',
  ],
  'Audio delay {value1}ms': [
    'Retardo de audio {value1} ms',
    'Atraso do áudio {value1} ms',
    'Décalage audio {value1} ms',
    'ऑडियो देरी {value1} मि.से.',
    'Audioverzögerung {value1} ms',
  ],
  'Audio: {value1}': [
    'Audio: {value1}',
    'Áudio: {value1}',
    'Audio : {value1}',
    'ऑडियो: {value1}',
    'Audio: {value1}',
  ],
  'Checking embedded and external captions…': [
    'Buscando subtítulos integrados y externos…',
    'Verificando legendas integradas e externas…',
    'Recherche des sous-titres intégrés et externes…',
    'अंतर्निहित और बाहरी उपशीर्षक जाँचे जा रहे हैं…',
    'Eingebettete und externe Untertitel werden geprüft…',
  ],
  'Checking every embedded audio track…': [
    'Comprobando todas las pistas de audio integradas…',
    'Verificando todas as faixas de áudio integradas…',
    'Vérification de toutes les pistes audio intégrées…',
    'सभी अंतर्निहित ऑडियो ट्रैक जाँचे जा रहे हैं…',
    'Alle eingebetteten Audiospuren werden geprüft…',
  ],
  'Checking {value1}...': [
    'Comprobando {value1}...',
    'Verificando {value1}...',
    'Vérification de {value1}...',
    '{value1} जाँचा जा रहा है...',
    '{value1} wird geprüft...',
  ],
  'Compatibility decoder is already enabled': [
    'El decodificador de compatibilidad ya está activado',
    'O decodificador de compatibilidade já está ativado',
    'Le décodeur de compatibilité est déjà activé',
    'संगतता डिकोडर पहले से चालू है',
    'Kompatibilitätsdecoder ist bereits aktiviert',
  ],
  'Could not change captions. Please try again.': [
    'No se pudieron cambiar los subtítulos. Inténtalo de nuevo.',
    'Não foi possível alterar as legendas. Tente novamente.',
    'Impossible de changer les sous-titres. Réessayez.',
    'उपशीर्षक नहीं बदले जा सके। फिर कोशिश करें।',
    'Untertitel konnten nicht geändert werden. Bitte erneut versuchen.',
  ],
  'Could not open an external player': [
    'No se pudo abrir un reproductor externo',
    'Não foi possível abrir um reprodutor externo',
    'Impossible d’ouvrir un lecteur externe',
    'बाहरी प्लेयर नहीं खुल सका',
    'Externer Player konnte nicht geöffnet werden',
  ],
  'Could not restore the saved position': [
    'No se pudo recuperar la posición guardada',
    'Não foi possível restaurar a posição salva',
    'Impossible de restaurer la position enregistrée',
    'सहेजी गई स्थिति वापस नहीं लाई जा सकी',
    'Gespeicherte Position konnte nicht wiederhergestellt werden',
  ],
  'Could not seek to that position': [
    'No se pudo saltar a esa posición',
    'Não foi possível ir para essa posição',
    'Impossible d’atteindre cette position',
    'उस स्थिति पर नहीं जा सके',
    'Diese Position konnte nicht angesprungen werden',
  ],
  'Could not skip this segment': [
    'No se pudo saltar este segmento',
    'Não foi possível pular este trecho',
    'Impossible de passer ce segment',
    'यह भाग छोड़ा नहीं जा सका',
    'Dieser Abschnitt konnte nicht übersprungen werden',
  ],
  'Default player is unavailable — using MPV': [
    'El reproductor predeterminado no está disponible — se usará MPV',
    'Reprodutor padrão indisponível — usando MPV',
    'Lecteur par défaut indisponible — utilisation de MPV',
    'डिफ़ॉल्ट प्लेयर उपलब्ध नहीं — MPV इस्तेमाल हो रहा है',
    'Standardplayer nicht verfügbar — MPV wird verwendet',
  ],
  'Episode {value1} was added to Download Manager.': [
    'El episodio {value1} se añadió al gestor de descargas.',
    'O episódio {value1} foi adicionado ao gerenciador de downloads.',
    'L’épisode {value1} a été ajouté aux téléchargements.',
    'एपिसोड {value1} डाउनलोड प्रबंधक में जोड़ा गया।',
    'Folge {value1} wurde zum Downloadmanager hinzugefügt.',
  ],
  'External captions could not be loaded': [
    'No se pudieron cargar los subtítulos externos',
    'Não foi possível carregar legendas externas',
    'Impossible de charger les sous-titres externes',
    'बाहरी उपशीर्षक लोड नहीं हो सके',
    'Externe Untertitel konnten nicht geladen werden',
  ],
  'External playback is unavailable for this source': [
    'La reproducción externa no está disponible para esta fuente',
    'Reprodução externa indisponível para esta fonte',
    'La lecture externe est indisponible pour cette source',
    'इस स्रोत के लिए बाहरी प्लेबैक उपलब्ध नहीं है',
    'Externe Wiedergabe ist für diese Quelle nicht verfügbar',
  ],
  'External player failed — using MPV': [
    'Falló el reproductor externo — se usará MPV',
    'Reprodutor externo falhou — usando MPV',
    'Échec du lecteur externe — utilisation de MPV',
    'बाहरी प्लेयर विफल — MPV इस्तेमाल हो रहा है',
    'Externer Player fehlgeschlagen — MPV wird verwendet',
  ],
  'External subtitles were blocked because they were unsafe or unsupported.': [
    'Los subtítulos externos se bloquearon por no ser seguros o compatibles.',
    'As legendas externas foram bloqueadas por serem inseguras ou incompatíveis.',
    'Les sous-titres externes ont été bloqués car ils étaient dangereux ou non pris en charge.',
    'बाहरी उपशीर्षक असुरक्षित या असमर्थित होने के कारण रोक दिए गए।',
    'Externe Untertitel wurden blockiert, da sie unsicher oder nicht unterstützt waren.',
  ],
  'High contrast subtitles off': [
    'Subtítulos de alto contraste desactivados',
    'Legendas de alto contraste desativadas',
    'Sous-titres à contraste élevé désactivés',
    'उच्च कंट्रास्ट उपशीर्षक बंद',
    'Kontrastreiche Untertitel aus',
  ],
  'High contrast subtitles on': [
    'Subtítulos de alto contraste activados',
    'Legendas de alto contraste ativadas',
    'Sous-titres à contraste élevé activés',
    'उच्च कंट्रास्ट उपशीर्षक चालू',
    'Kontrastreiche Untertitel an',
  ],
  'Intro skipped': [
    'Introducción omitida',
    'Abertura pulada',
    'Générique de début passé',
    'इंट्रो छोड़ दिया गया',
    'Intro übersprungen',
  ],
  'Outro skipped': [
    'Final omitido',
    'Encerramento pulado',
    'Générique de fin passé',
    'आउट्रो छोड़ दिया गया',
    'Outro übersprungen',
  ],
  'Skip Intro': [
    'Saltar introducción',
    'Pular abertura',
    'Passer le générique',
    'इंट्रो छोड़ें',
    'Intro überspringen',
  ],
  'Skip Outro': [
    'Saltar final',
    'Pular encerramento',
    'Passer la fin',
    'आउट्रो छोड़ें',
    'Outro überspringen',
  ],
  'Skip Recap': [
    'Saltar resumen',
    'Pular resumo',
    'Passer le résumé',
    'पुनरावलोकन छोड़ें',
    'Rückblick überspringen',
  ],
  'Skipped Intro': [
    'Introducción omitida',
    'Abertura pulada',
    'Générique de début passé',
    'इंट्रो छोड़ दिया गया',
    'Intro übersprungen',
  ],
  'Skipped Outro': [
    'Final omitido',
    'Encerramento pulado',
    'Générique de fin passé',
    'आउट्रो छोड़ दिया गया',
    'Outro übersprungen',
  ],
  'Intro/outro timing is temporarily unavailable': [
    'Los tiempos de introducción y final no están disponibles temporalmente',
    'Os tempos de abertura e encerramento estão temporariamente indisponíveis',
    'Le minutage des génériques est temporairement indisponible',
    'इंट्रो और आउट्रो का समय अभी उपलब्ध नहीं है',
    'Intro-/Outro-Zeiten sind vorübergehend nicht verfügbar',
  ],
  'No compatible external player is installed': [
    'No hay un reproductor externo compatible instalado',
    'Nenhum reprodutor externo compatível está instalado',
    'Aucun lecteur externe compatible n’est installé',
    'कोई समर्थित बाहरी प्लेयर इंस्टॉल नहीं है',
    'Kein kompatibler externer Player installiert',
  ],
  'Only the host can control playback while you are synced': [
    'Solo el anfitrión puede controlar la reproducción mientras estás sincronizado',
    'Só o anfitrião pode controlar a reprodução enquanto você está sincronizado',
    'Seul l’hôte peut contrôler la lecture pendant la synchronisation',
    'सिंक रहने पर केवल होस्ट प्लेबैक नियंत्रित कर सकता है',
    'Während der Synchronisierung steuert nur der Gastgeber die Wiedergabe',
  ],
  'Opened in external player': [
    'Abierto en reproductor externo',
    'Aberto no reprodutor externo',
    'Ouvert dans le lecteur externe',
    'बाहरी प्लेयर में खोला गया',
    'Im externen Player geöffnet',
  ],
  'Playback speed reset to 1x for Watch Party sync': [
    'Velocidad restablecida a 1x para sincronizar Watch Party',
    'Velocidade redefinida para 1x para sincronizar Watch Party',
    'Vitesse rétablie à 1x pour synchroniser Watch Party',
    'Watch Party सिंक के लिए गति 1x कर दी गई',
    'Geschwindigkeit für Watch Party auf 1x zurückgesetzt',
  ],
  'Playback speed stays at 1x during a Watch Party': [
    'La velocidad se mantiene en 1x durante Watch Party',
    'A velocidade fica em 1x durante Watch Party',
    'La vitesse reste à 1x pendant Watch Party',
    'Watch Party में गति 1x रहती है',
    'Während einer Watch Party bleibt die Geschwindigkeit bei 1x',
  ],
  'Playback speed {value1}': [
    'Velocidad de reproducción {value1}',
    'Velocidade de reprodução {value1}',
    'Vitesse de lecture {value1}',
    'प्लेबैक गति {value1}',
    'Wiedergabegeschwindigkeit {value1}',
  ],
  'Playing without the unsafe or unsupported external subtitles.': [
    'Reproduciendo sin los subtítulos externos inseguros o incompatibles.',
    'Reproduzindo sem as legendas externas inseguras ou incompatíveis.',
    'Lecture sans les sous-titres externes dangereux ou non pris en charge.',
    'असुरक्षित या असमर्थित बाहरी उपशीर्षकों के बिना चल रहा है।',
    'Wiedergabe ohne die unsicheren oder nicht unterstützten externen Untertitel.',
  ],
  'Playing {value1}': [
    'Reproduciendo {value1}',
    'Reproduzindo {value1}',
    'Lecture de {value1}',
    '{value1} चल रहा है',
    '{value1} wird abgespielt',
  ],
  'Resumed at {value1}': [
    'Reanudado en {value1}',
    'Retomado em {value1}',
    'Reprise à {value1}',
    '{value1} से फिर शुरू',
    'Bei {value1} fortgesetzt',
  ],
  'Stream restarted': [
    'Transmisión reiniciada',
    'Transmissão reiniciada',
    'Flux relancé',
    'स्ट्रीम फिर शुरू हुई',
    'Stream neu gestartet',
  ],
  'Subtitle delay {value1}ms': [
    'Retardo de subtítulos {value1} ms',
    'Atraso das legendas {value1} ms',
    'Décalage des sous-titres {value1} ms',
    'उपशीर्षक देरी {value1} मि.से.',
    'Untertitelverzögerung {value1} ms',
  ],
  'Subtitle position {value1}%': [
    'Posición de subtítulos {value1}%',
    'Posição das legendas {value1}%',
    'Position des sous-titres {value1}%',
    'उपशीर्षक स्थिति {value1}%',
    'Untertitelposition {value1}%',
  ],
  'Subtitle size {value1}': [
    'Tamaño de subtítulos {value1}',
    'Tamanho das legendas {value1}',
    'Taille des sous-titres {value1}',
    'उपशीर्षक आकार {value1}',
    'Untertitelgröße {value1}',
  ],
  'Subtitles: Off': [
    'Subtítulos: desactivados',
    'Legendas: desativadas',
    'Sous-titres : désactivés',
    'उपशीर्षक: बंद',
    'Untertitel: aus',
  ],
  'Subtitles: {track}': [
    'Subtítulos: {track}',
    'Legendas: {track}',
    'Sous-titres : {track}',
    'उपशीर्षक: {track}',
    'Untertitel: {track}',
  ],
  'Switching audio track…': [
    'Cambiando pista de audio…',
    'Alterando faixa de áudio…',
    'Changement de piste audio…',
    'ऑडियो ट्रैक बदल रहा है…',
    'Audiospur wird gewechselt…',
  ],
  'That app could not open this stream — using MPV': [
    'Esa app no pudo abrir la transmisión — se usará MPV',
    'Esse app não abriu a transmissão — usando MPV',
    'Cette appli n’a pas pu ouvrir le flux — utilisation de MPV',
    'वह ऐप स्ट्रीम नहीं खोल सका — MPV इस्तेमाल हो रहा है',
    'Diese App konnte den Stream nicht öffnen — MPV wird verwendet',
  ],
  'That decoder is unavailable for this video in Media3 on this device. Your current decoder is unchanged.': [
    'Ese decodificador no está disponible para este video en Media3 en este dispositivo. El decodificador actual no cambió.',
    'Esse decodificador está indisponível para este vídeo no Media3 neste dispositivo. O decodificador atual não foi alterado.',
    'Ce décodeur n’est pas disponible pour cette vidéo avec Media3 sur cet appareil. Le décodeur actuel n’a pas changé.',
    'इस डिवाइस पर Media3 में इस वीडियो के लिए वह डिकोडर उपलब्ध नहीं है। आपका मौजूदा डिकोडर नहीं बदला है।',
    'Dieser Decoder ist für das Video in Media3 auf diesem Gerät nicht verfügbar. Der aktuelle Decoder bleibt unverändert.',
  ],
  'That source could not start. Restored the previous stream.': [
    'Esa fuente no pudo iniciarse. Se recuperó la transmisión anterior.',
    'Essa fonte não iniciou. A transmissão anterior foi restaurada.',
    'Cette source n’a pas démarré. Le flux précédent a été restauré.',
    'वह स्रोत शुरू नहीं हुआ। पिछली स्ट्रीम वापस चला दी गई।',
    'Diese Quelle konnte nicht starten. Der vorherige Stream wurde wiederhergestellt.',
  ],
  'This file has no selectable embedded audio tracks': [
    'Este archivo no tiene pistas de audio integradas seleccionables',
    'Este arquivo não tem faixas de áudio integradas selecionáveis',
    'Ce fichier n’a aucune piste audio intégrée sélectionnable',
    'इस फ़ाइल में चुनने योग्य अंतर्निहित ऑडियो ट्रैक नहीं हैं',
    'Diese Datei hat keine auswählbaren eingebetteten Audiospuren',
  ],
  'This server audio track could not be selected': [
    'No se pudo seleccionar esta pista de audio del servidor',
    'Não foi possível selecionar esta faixa de áudio do servidor',
    'Impossible de sélectionner cette piste audio du serveur',
    'सर्वर का यह ऑडियो ट्रैक चुना नहीं जा सका',
    'Diese Server-Audiospur konnte nicht ausgewählt werden',
  ],
  'This source uses separate captions that cannot be saved in this beta. Choose another source.': [
    'Esta fuente usa subtítulos separados que esta beta no puede guardar. Elige otra fuente.',
    'Esta fonte usa legendas separadas que esta versão beta não pode salvar. Escolha outra fonte.',
    'Cette source utilise des sous-titres séparés non enregistrables dans cette bêta. Choisissez une autre source.',
    'यह स्रोत अलग उपशीर्षक इस्तेमाल करता है जो इस बीटा में सहेजे नहीं जा सकते। दूसरा स्रोत चुनें।',
    'Diese Quelle nutzt separate Untertitel, die diese Beta nicht speichern kann. Wähle eine andere Quelle.',
  ],
  'This source uses separate audio or captions that cannot be saved in this beta. Choose another source.': [
    'Esta fuente usa audio o subtítulos separados que no se pueden guardar en esta versión beta. Elige otra fuente.',
    'Esta fonte usa áudio ou legendas separados que não podem ser salvos nesta versão beta. Escolha outra fonte.',
    'Cette source utilise des pistes audio ou des sous-titres séparés qui ne peuvent pas être enregistrés dans cette version bêta. Choisissez une autre source.',
    'यह स्रोत अलग ऑडियो या उपशीर्षक इस्तेमाल करता है जिन्हें इस बीटा में सहेजा नहीं जा सकता। कोई दूसरा स्रोत चुनें।',
    'Diese Quelle verwendet separate Audio- oder Untertitelspuren, die in dieser Beta nicht gespeichert werden können. Wähle eine andere Quelle.',
  ],
  'This web source could not be prepared for download. Try another source.': [
    'No se pudo preparar esta fuente web para descargar. Prueba otra fuente.',
    'Não foi possível preparar esta fonte web para download. Tente outra fonte.',
    'Impossible de préparer cette source web au téléchargement. Essayez une autre source.',
    'यह वेब स्रोत डाउनलोड के लिए तैयार नहीं हुआ। दूसरा स्रोत आज़माएँ।',
    'Diese Webquelle konnte nicht zum Download vorbereitet werden. Versuche eine andere Quelle.',
  ],
  '{received} of {total} • {percent}%': [
    '{received} de {total} • {percent}%',
    '{received} de {total} • {percent}%',
    '{received} sur {total} • {percent}%',
    '{total} में से {received} • {percent}%',
    '{received} von {total} • {percent}%',
  ],
  '{value1} enabled': [
    '{value1} activado',
    '{value1} ativado',
    '{value1} activé',
    '{value1} चालू किया गया',
    '{value1} aktiviert',
  ],
  'DIRECT TORRENT STREAMS': [
    'TRANSMISIONES TORRENT DIRECTAS',
    'TRANSMISSÕES TORRENT DIRETAS',
    'FLUX TORRENT DIRECTS',
    'सीधी टॉरेंट स्ट्रीम',
    'DIREKTE TORRENT-STREAMS',
  ],
  'DEBRID STREAMS': [
    'TRANSMISIONES DEBRID',
    'TRANSMISSÕES DEBRID',
    'FLUX DEBRID',
    'DEBRID स्ट्रीम',
    'DEBRID-STREAMS',
  ],
  'WEB STREAMS': [
    'TRANSMISIONES WEB',
    'TRANSMISSÕES WEB',
    'FLUX WEB',
    'वेब स्ट्रीम',
    'WEBSTREAMS',
  ],
  'LOCAL SOURCES': [
    'FUENTES LOCALES',
    'FONTES LOCAIS',
    'SOURCES LOCALES',
    'स्थानीय स्रोत',
    'LOKALE QUELLEN',
  ],
  'AVAILABLE OFFLINE': [
    'DISPONIBLE SIN CONEXIÓN',
    'DISPONÍVEL OFFLINE',
    'DISPONIBLE HORS LIGNE',
    'ऑफ़लाइन उपलब्ध',
    'OFFLINE VERFÜGBAR',
  ],
  'QUALITY': ['CALIDAD', 'QUALIDADE', 'QUALITÉ', 'गुणवत्ता', 'QUALITÄT'],
  'CODEC': ['CÓDEC', 'CODEC', 'CODEC', 'कोडेक', 'CODEC'],
  'COLOR': ['COLOR', 'COR', 'COULEUR', 'रंग', 'FARBE'],
  'SORT': ['ORDENAR', 'ORDENAR', 'TRIER', 'क्रम', 'SORTIERUNG'],
  'QUEUED': ['EN COLA', 'NA FILA', 'EN ATTENTE', 'कतार में', 'WARTESCHLANGE'],
  'PREPARING': [
    'PREPARANDO',
    'PREPARANDO',
    'PRÉPARATION',
    'तैयार हो रहा है',
    'VORBEREITUNG',
  ],
  'DOWNLOADING': [
    'DESCARGANDO',
    'BAIXANDO',
    'TÉLÉCHARGEMENT',
    'डाउनलोड हो रहा है',
    'WIRD HERUNTERGELADEN',
  ],
  'PAUSED': ['PAUSADO', 'PAUSADO', 'EN PAUSE', 'रुका हुआ', 'PAUSIERT'],
  'DOWNLOADED': [
    'DESCARGADO',
    'BAIXADO',
    'TÉLÉCHARGÉ',
    'डाउनलोड किया गया',
    'HERUNTERGELADEN',
  ],
  'FAILED': ['ERROR', 'FALHOU', 'ÉCHEC', 'विफल', 'FEHLGESCHLAGEN'],
  'CANCELLED': [
    'CANCELADO',
    'CANCELADO',
    'ANNULÉ',
    'रद्द किया गया',
    'ABGEBROCHEN',
  ],
  'UNSUPPORTED': [
    'NO COMPATIBLE',
    'INCOMPATÍVEL',
    'NON PRIS EN CHARGE',
    'असमर्थित',
    'NICHT UNTERSTÜTZT',
  ],
};
